### ISSUE TITLE
file_base::flags for O_DIRECT/O_SYNC

### ISSUE THREAD

**Issue by vinipsmaker** [chriskohlhoff/asio#1002]
Windows has `FILE_FLAG_NO_BUFFERING` and `FILE_FLAG_WRITE_THROUGH` which should be equivalent to `O_DIRECT` and `O_SYNC`.

**Comment by vinipsmaker** [comment]
FWIW Golang only maps `O_SYNC` on Windows (and UNIXes): https://github.com/golang/go/blob/c9fe126c8bf25d14b233f1ccaff12c1bffbd4971/src/syscall/types_windows.go#L34-L48

This would be fine to me as `O_SYNC` is more important than `O_DIRECT` for my use cases.

**Comment by chriskohlhoff** [comment]
Added O_SYNC equivalent in 1.22.1.
