### ISSUE TITLE
Is it really necessary to have a global mutex protecting calls to SSL_accept?

### ISSUE THREAD

**Issue by dkadashev** [chriskohlhoff/asio#101]
`SSL_accept()` call inside of `ssl::detail::engine::do_accept()` is protected by a global mutex. Not surprisingly this is a huge bottleneck.

OpenSSL doc says that "Provided an application sets up the thread callback function" OpenSSL is thread-safe (https://www.openssl.org/docs/faq.html#PROG1). I think the mutex was originally added here: https://sourceforge.net/p/asio/patches/1/ - could it be the case that back then either thread locking callback was not configured [properly] or there was an error in testing? Does the OpenSSL doc lie?

The mutex contention heavily limits achievable request rates.

**Comment by acmorrow** [comment]
Only somewhat related, but related nonetheless is https://github.com/chriskohlhoff/asio/issues/73.

**Comment by dkadashev** [comment]
We did several stress tests on an 8-core box with patched ASIO that doesn't protect `SSL_accept()` with mutex. No crashes / errors / memory leaks observed after ~65M requests at ~1350 requests per second (CPU was maxed out, mostly by SSL code).

Looks like the mutex is not necessary as OpenSSL docs suggest.

**Comment by dkadashev** [comment]
Checked BoringSSL docs just in case, and there is no indication that `SSL_accept()` is not thread safe there as well. I think the mutex can be removed unconditionally.

**Comment by byllyfish** [comment]
According to this bug report from 2010, the first call to SSL_accept() from two different threads could lead to a race condition. This bug is supposed to be fixed.

https://rt.openssl.org/Ticket/Display.html?id=2208

From ssl.h:
> An SSL object represents a single TLS or DTLS connection. Although the shared SSL_CTX is thread-safe, an SSL is not thread-safe and may only be used on one thread at a time.

**Comment by dkadashev** [comment]
So that bug report is about first `SSL_accept()` call only. But the mutex is locked always. It's too high price to pay if you ask me. Also it's a long fixed bug. I wouldn't say it's an asio responsibility to work around OpenSSL bugs.

As for SSL object not being thread safe, it's not relevant here. The mutex in question is global, not per-SSL object. And it's not asio responsibility to prevent users from doing stupid things like using single SSL object concurrently. Note that only `SSL_accept()` is protected by the mutex, but most of the `engine` methods operate on SSL object. If making `engine` objects thread safe was part of the design then (almost) every method operating on `ssl_` would have to be protected by a mutex (not a global one).

**Comment by chriskohlhoff** [comment]
Fixed in 37d0d474f2562d9ec50025ecacd3613e9e406685. Conservatively, I have retained the locking for openssl < 1.0.
