### ISSUE TITLE
A question about wrapping handler

### ISSUE THREAD

**Issue by ytimenkov** [chriskohlhoff/asio#1018]
Thanks for the hard work, especially the recent one on documentation part!

The following code in `callback_wrapper` example
```c++
    // Dispatch the completion handler through the handler's associated
    // executor, using the handler's associated allocator.
    asio::dispatch(state.work_.get_executor(),
        asio::bind_allocator(d.alloc,
          [
            handler = std::move(state.handler_),
            result = std::string(result)
          ]() mutable
          {
            std::move(handler)(result);
          }));
```

made me thinking:

There is an overload of `asio::dispatch` which accepts only completion token, so code could be written as composition of `dispatch(bind_executor(ex, bind_allocator(a, ...)))`. Is there any reason/preference, especially if ASIO will introduce more traits?

Can it be just a generic "use all traits from that type" binder?

Also I noticed 2 things:

1. Is there any reason to explicitly fall back to `recycling_allocator` if handler doesn't provide any and not to whatever ASIO thinks should be a default?
2. The comment is not strictly correct: `dispatch` doesn't dispatch through handler's associated executor. It dispatches through `work` which is not exactly the same thing.

**Comment by chriskohlhoff** [comment]
> There is an overload of asio::dispatch which accepts only completion token, so code could be written as composition of dispatch(bind_executor(ex, bind_allocator(a, ...))). Is there any reason/preference, especially if ASIO will introduce more traits?

You can use the `experimental::append` adapter here which does exactly that kind of generic forwarding. However, as it's still in the `experimental` namespace I did not want to use it in this example at this time. (You may also do this yourself using the `associator` trait with your own handler wrapper/adapter.)

> Is there any reason to explicitly fall back to recycling_allocator if handler doesn't provide any and not to whatever ASIO thinks should be a default?

The so-called _default candidate_ allocator is `std::allocator<void>`. The recycling allocator works well for these simple operations that allocate a single object that exists for the lifetime of the operation.

> The comment is not strictly correct: dispatch doesn't dispatch through handler's associated executor. It dispatches through work which is not exactly the same thing.

Actually, it is strictly correct. The work guard was created from the handler, and so `state.work_.get_executor()` returns the handler's associated executor.

**Comment by ytimenkov** [comment]
> The so-called default candidate allocator is std::allocator<void>. 

Yes, I realized that later... For some reasons I thought that defaults were changed.

> Actually, it is strictly correct. The work guard was created from the handler, and so state.work_.get_executor() returns the handler's associated executor.

I see. I thought that it returns a slightly different executor which tracks work and therefore exactly handler's executor can't be used. Then `append` would be a definitely a viable alternative.
