### ISSUE TITLE
a question about experimental channel/concurrent_channel

### ISSUE THREAD

**Issue by vkhristenko** [chriskohlhoff/asio#1019]
Hello,

Given there is not much documentation yet on channels, just wanted to make sure, given the term concurrent can mean multiple different things...

Is that correct that `experimental::basic_channel` is not thread safe? i.e. It is ok to use with multiple send/receive coroutines but with a single thread...

Is that correct that `experimental::basic_concrrent_channel` is thread safe? In other words, this is multiple producer, multiple consumer queue, multiple refers here to multiple threads?

edit:
[boost channel example](https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/example/cpp20/channels/throttling_proxy.cpp)

VK

**Comment by chriskohlhoff** [comment]
> Is that correct that experimental::basic_channel is not thread safe?

Yes.

> i.e. It is ok to use with multiple send/receive coroutines but with a single thread...

Or multiple coroutines that share a strand.

> Is that correct that experimental::basic_concrrent_channel is thread safe? In other words, this is multiple producer, multiple consumer queue, multiple refers here to multiple threads?

Yes and yes.
