### ISSUE TITLE
namespace "boost::asio" has no member "awaitable"C/C++(135)

### ISSUE THREAD

**Issue by WarrenN1** [chriskohlhoff/asio#1057]
I am compiling using gcc c++20. However, it always throws the error

`namespace "boost::asio" has no member "awaitable"C/C++(135)` within VSCode

More specifically
`error: no template named 'awaitable' in namespace 'boost::asio'`

I can't get this to compile and it is driving me crazy given awaitable is said to be included in boost. I have been scouring the docs, and can't seem to figure out why this is not working. Any help would be deeply appreciated.

I compiled my program as such:
`clang++ -std=c++20 -g -Wall -o main server.cpp  -I/external_libraries/include/  -L/external_libraries/lib/ -lboost_coroutine -lboost_context -lboost_thread -pthread -lcrypto -lssl -lboost_system`

I tried setting the -fcoroutines flag, but that resulted in the error
`error: unknown argument: '-fcoroutines'`

**Comment by WarrenN1** [comment]
g++ -std=c++2a -g -Wall -o main server.cpp  -I/external_libraries/include/  -L/external_libraries/lib/ -lboost_coroutine -lboost_context -lboost_thread -pthread -lcrypto -lssl -lboost_system -fcoroutines
yields the following error
g++: error: unrecognized command line option ‘-fcoroutines’; did you mean ‘-fc-prototypes’?
make: *** [makefile:21: main] Error 1

I am g++ version
g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-13)

**Comment by kiwixz** [comment]
You need a newer GCC.
________________________________

**Comment by WarrenN1** [comment]
Thank you!
