### ISSUE TITLE
Can't make check with ssl support in MinGW64/msys2

### ISSUE THREAD

**Issue by rpavlik** [chriskohlhoff/asio#108]
It appears to be because of transitive includes: one of the OpenSSL header files ends up including `winsock.h` (not `winsock2.h` - they are incompatible), so it all falls apart in `socket_types.h`

I extracted the include tree with this command, mildly modified from the build command make was running:

``` bash
( cd src/tests/ &&  \
  /mingw64/bin/g++ -DPACKAGE_NAME=\"asio\" -DPACKAGE_TARNAME=\"asio\" -DPACKAGE_VERSION=\"1.11.0\" -DPACKAGE_STRING=\"asio\ 1.11.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"asio\" -DVERSION=\"1.11.0\" -D_REENTRANT=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I.    -I./../../include -g -O2 -mthreads -ftemplate-depth-256 \
  unit/ssl/context_base.cpp -M -H ) \
  > sslincludes.txt 2>&1
```

Here's the subset of that `-M -H` output of trying to build the test that led me to the flaw: (empty lines mean I left out un-related lines - lines that weren't direct parents)

```
.. ./../../include/asio/ssl/detail/openssl_types.hpp

... C:/msys2/mingw64/include/openssl/ssl.h

.... C:/msys2/mingw64/include/openssl/dtls1.h
..... C:/msys2/mingw64/include/openssl/pqueue.h
...... C:/msys2/mingw64/x86_64-w64-mingw32/include/string.h
....... C:/msys2/mingw64/x86_64-w64-mingw32/include/sec_api/string_s.h
........ C:/msys2/mingw64/x86_64-w64-mingw32/include/string.h
..... C:/msys2/mingw64/x86_64-w64-mingw32/include/winsock.h
```

so it's the `openssl/dtls1.h` file at fault here - and they're just including it for `struct timeval` - oh the humanity!

Unfortunately I don't immediately see any good way to work around it - no defines we could use to avoid it, etc.

The only solution short of upstream change, which isn't a great solution but does work, is to beat OpenSSL to the punch, and on Windows, include `socket_types` before `openssl/ssl.h`.

**Comment by chriskohlhoff** [comment]
Fixed on master in f3f324cbe9d805cb310f8eb3ec00a2060a433177. Fixed on asio-1-10-branch in 37f5a8d97a9eb1392812706af2f8b49a7f99fe84.
