### ISSUE TITLE
Unable to build asio with -fno-rtti

### ISSUE THREAD

**Issue by alphanso** [chriskohlhoff/asio#1101]
Hi,

I am using asio (1.22.0) without boost. I am trying to build it with -fno-rtti -fno-exception with std=c++17. I fail with lot of messages saying to build -frtti. I am filling this report because I believe asio can be used without rtti as well.

In file included from external/build/headers/asio/detail/completion_handler.hpp:21:
external/build/headers/asio/detail/handler_work.hpp:226:29: error: use of typeid requires -frtti
        ex.target_type() == typeid(typename IoContext::executor_type)
                            ^
external/build/headers/asio/detail/handler_work.hpp:318:29: error: use of typeid requires -frtti
        ex.target_type() == typeid(typename IoContext::executor_type)
                            ^
external/build/headers/asio/detail/handler_work.hpp:393:29: error: use of typeid requires -frtti
        ex.target_type() == typeid(typename IoContext::executor_type)

/external/build/headers/asio/executor.hpp:215:43: error: use of typeid requires -frtti
    return impl_ ? impl_->target_type() : typeid(void);

/external/build/headers/asio/executor.hpp:273:12: error: use of typeid requires -frtti
    return typeid(T);
                            ^

**Comment by chriskohlhoff** [comment]
Add the define `ASIO_NO_TYPEID` to your build settings.
