### ISSUE TITLE
Cope when given file descriptors not supported by epoll

### ISSUE THREAD

**Issue by dfoxfranke** [chriskohlhoff/asio#111]
Some types of file descriptor, including regular files, directories, and certain devices (notably `/dev/null`) are not supported by epoll. If you try to add one to an epoll instance, `epoll_ctl()` will return `-1` and set `errno=EPERM`. Currently, if Asio is using epoll and you try to construct a `posix::stream_descriptor` using such an fd, it'll throw a `system_error`; furthermore, although I haven't pinned down the cause, it appears that afterward the service will be left in a deadlocked, unusable state.

File descriptors that aren't supported by epoll never block. I'm not sure if there are any exceptions to this rule (possibly some weird cases involving NFS and full RAM?), but if there are, then there's no way at all to determine whether or not an I/O operation on such descriptors will block. `select()` and company will always report that the fd is ready.

So, I think the right thing for Asio to do with such descriptors is to notice the `epoll_ctl()` error, put the service back in a consistent state, and set some internal `never_blocks` flag to true. Calls to `async_read_some`/`async_write_some` on descriptors that never block should bypass epoll and dispatch the handler immediately.

The reason I've stumbled on this problem is that I have an application that does asynchronous I/O on stdin/stdout, and it broke when I started it with stdout redirected to `/dev/null`. As a workaround, I wrote a class which wraps `posix::stream_descriptor` and satisfies the type requirements for `AsyncReadStream`/`AsyncWriteStream`/`SyncReadStream`/`SyncWriteStream`. Its constructor calls `fstat()` on the file descriptor to check whether it's (to a conservative approximation) a type supported by epoll. If so, it constructs a `posix::stream_descriptor` and passes everything through to it. If not, then its I/O methods immediately invoke a handler which implements the I/O using `readv()`/`writev()`. This seems to work well enough for the time being, but it's an ugly hack that Asio shouldn't make necessary.

**Comment by chriskohlhoff** [comment]
Fixed by a9fa5bf248c091847c9d6f3ab0f15cc14074e85f.
