### ISSUE TITLE
Construct asio system_timer program stuck

### ISSUE THREAD

**Issue by inie0722** [chriskohlhoff/asio#1113]
boost version 1.79: x64
OS Windows 10
Constructing system_timer in the dll global variable will cause the program to stuck.
Compiler msvc

**Reproduce code**
Compile A.cpp to dll.

A.hpp
```cpp
int fun();
```

A.cpp
```cpp
#include <boost/asio.hpp>
#include  "A.hpp"

static bool validate = []()
{
    using namespace boost::asio
    io_context io_context;
    boost::asio::system_timer timer(io_context);
    return true;
}();

int fun()
{
    return validate;
}
```
main.cpp
```cpp
#include "A.hpp"
#include <iostream>

int main()
{
    std::cout << fun() << std::endl;
    return 0;
}
```

**Comment by Jackarain** [comment]
https://godbolt.org/z/saz14r8xE

What's the problem?

**Comment by inie0722** [comment]
> https://godbolt.org/z/saz14r8xE
> 
> What's the problem?

This bug occurs only when static members are placed in the dll.

**Comment by Jackarain** [comment]
This is not a bug, this is strictly a Windows problem.

https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/overview/implementation.html
says:
An additional thread per io_context is used to fire the timer. The thread is created when the first basic_deadline_timer or basic_waitable_timer object is constructed.

so, same problem like this:
https://stackoverflow.com/questions/32252143/stdthread-cause-deadlock-in-dllmain

**Comment by inie0722** [comment]
Yep, I didn't have this problem on linux, when i ported to windows it didn't work.
