### ISSUE TITLE
[Boost.Asio (1.80)] boost::asio::steady_timer and boost::asio::system_timer can not work properly

### ISSUE THREAD

**Issue by youngwolf-project** [chriskohlhoff/asio#1127]
I have a project uses Boost.Asio, in the past decade, whenever Boost publish new release, I update it and never met any issues, but after I updated it to 1.80, the problem occurred.

PS.
In windows, no such problem been found, it just occur in Linux (I tried Ubuntu 22.04 and Debian 11), I've not tried Unix.
When this problem occur, the io_context::run cannot return on both server and client endpoint after I closed the socket in client endpoint.
I use async connect and accept.
The newest standalone Asio (master branch) doesn't have such problem even in Linux.

**Comment by youngwolf-project** [comment]
One supplementation:
In Fedora 36, all connections (I create 16 links) can be established, but in following data transmission, the async send and recv can also get stuck just as async connect and accept, then io_context::run cannot return on both server and client endpoint after I closed the socket on client endpoint.

**Comment by youngwolf-project** [comment]
One supplementation:
In FreeBSD 13, I tried Boost 1.81 (the master branch), the link totally cannot be established, I believe with Boost 1.80, the same issue also exists.
PS.
The newest standalone Asio (master branch) doesn't have such problem in FreeBSD either.

**Comment by Jackarain** [comment]
How are you sure the problem is with asio?

**Comment by klemens-morgenstern** [comment]
Can you provide a code example? Your description doesn't make it possible to reproduce the rror.

**Comment by youngwolf-project** [comment]
> How are you sure the problem is with asio?

1. same code, stand alone asio works properly;
2. for link establishment, server calls async_accept, client calls async_connect, I have small chance to be wrong, especially I did not change my codes, just upgrade Boost.Asio from 1.79 to 1.80, then the issue comes up.

**Comment by youngwolf-project** [comment]
> Can you provide a code example? Your description doesn't make it possible to reproduce the rror.

Hi,
I found the root cause is that the timer (boost::asio::steady_timer or boost::asio::system_timer) cannot trigger timeout, but boost::asio::deadline_timer can:

void timer_handler(const boost::system::error_code& ec, const boost::shared_ptr<boost::asio::system_timer>&) {puts("receive a timeout event.");}
void main()
{
	boost::asio::io_context ctx[4];
	for (int i = 0; i < 16; ++i)
	{
		BOOST_AUTO(timer, boost::make_shared<boost::asio::system_timer>(ctx[i % 4].get_executor()));
		timer->expires_after(boost::chrono::milliseconds(50));
		timer->async_wait(boost::bind(&timer_handler, boost::asio::placeholders::error, timer));
	}
	boost::thread_group tg;
	for (int i = 0; i < 4; ++i)
		tg.create_thread(boost::bind(&boost::asio::io_context::run, &ctx[i % 4]));
	tg.join_all();
}

**Comment by youngwolf-project** [comment]
Sorry, I said that stand alone asio doesn't have such issue, it's not all of the truth.
As we knew, stand alone asio needs at least c++0x, while Boost doesn't, if I use c++0x (I actually tried c++20), with above codes, Boost.Asio works properly too (before, I used c++98).

**Comment by klemens-morgenstern** [comment]
Please format your code better. Why are you using 4 io_contexts?

**Comment by youngwolf-project** [comment]
> Please format your code better. Why are you using 4 io_contexts?

I tried many times, current format is the best I can achieve (Add code makes it worse).
Using 4 io_contexts because I used 4 io_contexts in my project, I believe this has nothing to do with the issue.

**Comment by youngwolf-project** [comment]
> So the issue is that the thread hangs end the timer doesn't expire? or are you missing the completion message?

The timer never expire (the callback timer_handler never been called), then io_context::run will not return, finally we get stuck on tg.join_all().

PS. do use c++98 to compile my codes, NOT c++0x or higher.

**Comment by youngwolf-project** [comment]
> So the issue is that the thread hangs end the timer doesn't expire? or are you missing the completion message?

If you wanna try c++0x (it should wroks properly as I mentioned before), you must change:
timer->expires_after(boost::chrono::milliseconds(50)); to
timer->expires_after(std::chrono::milliseconds(50));
Please have a try, thank you.

**Comment by klemens-morgenstern** [comment]
Can you change the completion handler signature to capture the shared pointer by value, not by const reference?

i.e.

```cpp
void timer_handler(const boost::system::error_code& ec, boost::shared_ptr<boost::asio::system_timer>) 
{
    puts("receive a timeout event.");
}
```

**Comment by youngwolf-project** [comment]
> Can you change the completion handler signature to capture the shared pointer by value, not by const reference?

Thanks for your proposal, I tried, the behavior does not change.

**Comment by klemens-morgenstern** [comment]
Weird, the code looks correct. Can you try using only one io_context? You can call `run` from multiple threads if you want.

**Comment by Jackarain** [comment]
> 1. same code, stand alone asio works properly;
> 2. for link establishment, server calls async_accept, client calls async_connect, I have small chance to be wrong, especially I did not change my codes, just upgrade Boost.Asio from 1.79 to 1.80, then the issue comes up.

I see,  @klemens-morgenstern, to reproduce can use this example:
[https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/tutorial/tuttimer2/src.html](https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/tutorial/tuttimer2/src.html)
compile with -std=c++03

**Comment by Jackarain** [comment]
In the case,
https://github.com/boostorg/asio/blob/develop/include/boost/asio/detail/timer_queue.hpp#L151
The variable 'now' appears to be an invalid value.

**Comment by youngwolf-project** [comment]
@Jackarain I built Boost without any specific customization, which is:
./bootstrap
./b2

**Comment by klemens-morgenstern** [comment]
Probably chrono, c++98 is barely supported these days. I'm surprised asio still does.

**Comment by youngwolf-project** [comment]
> Probably chrono, c++98 is barely supported these days. I'm surprised asio still does.

But library Chrono changed nothing (no release notes) in 1.80

**Comment by Jackarain** [comment]
> But library Chrono changed nothing (no release notes) in 1.80

https://www.boost.org/doc/libs/1_80_0/doc/html/chrono.html#chrono.overview

says：
**Lastly, Boost.Chrono includes [typeof](https://www.boost.org/libs/typeof) registration for [duration](https://www.boost.org/doc/libs/1_80_0/doc/html/chrono/reference.html#chrono.reference.cpp0x.duration_hpp.duration) and [time_point](https://www.boost.org/doc/libs/1_80_0/doc/html/chrono/reference.html#chrono.reference.cpp0x.time_point_hpp.time_point) to permit using emulated auto with C++03 compilers.**

**Comment by youngwolf-project** [comment]
Ill use of library Boost.Chrono, or Boost.Chrono issue.
