### ISSUE TITLE
Incorrect C++20 coroutine detection for clang-15

### ISSUE THREAD

**Issue by anarthal** [chriskohlhoff/asio#1142]
My current Asio installation is not detcting C++20 coroutine support correctly under the following circumstances:
* clang 15.0.2
* libc++ 15
* Boost version of Asio (as included in the boost-1.80.0 tag)

Investigating, it seems like libc++ 15 doesn't include the header `<experimental/coroutine>` anymore, and now includes it as plain `<coroutine>`. I will link a PR with the change I did to make it work (it's quite minimal).

**Comment by klemens-morgenstern** [comment]
Set `-stdlb=libc++`.

**Comment by anarthal** [comment]
I was missing the flag in the compiler command (just added to the linker). That solves the issue without any change in asio, thanks.

**Comment by gnaggnoyil** [comment]
@klemens-morgenstern Will ASIO support coroutine detection with Clang using libstdc++? We are using Clang 14 with libstdc++ 12.2 and ASIO set `ASIO_HAS_CO_AWAIT` not defined here.
