### ISSUE TITLE
Asio SSL full-duplex synchronization

### ISSUE THREAD

**Issue by p-jaholkowski** [chriskohlhoff/asio#1161]
This is issue is related to my post at [(https://stackoverflow.com/questions/74437185/asio-ssl-full-duplex-socket-synchronization-problem]) I was advised that in order to use SSL socket that way i need to synchronize it with explicit strand or implicit strand as stated in documentation https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/overview/ssl.html
So I rewrote my code to use explicit strand at client side and launched it as one thread which means that I have implicit and explicit strand. I was not sure that I wrote that explicit strand properly but implicit strand should provide guarantee that it will work.
After running for 10 seconds or less I get exception in SSL_read or SSL_write or I got error "sslv3 alert bad record mac (SSL routines)"
or some other error message.
Asio 1.24.0
Windows 10

I don't have any idea why it's not parsing well with that "''" code tag so I also added attachment of below code as txt file
Here is code to reproduce that bug:

#pragma once

#include <stdint.h>
#include <iostream>
#include <asio.hpp>
#include <asio/ssl.hpp>
#include <mutex>
#include <shared_mutex>

namespace test
{

namespace setup
{
	const uint32_t maxMessageSize = 1024 * 1024;
	const uint32_t maxSessionsNum = 10;
}

enum class MessageType
{
	LOG_ON = 0,
	TEXT_MESSAGE = 1
};

class MessageHeader
{
public:
	uint32_t messageType;
	uint32_t messageLength;

	MessageHeader(uint32_t messageType, uint32_t messageLength) : messageType(messageType), messageLength(messageLength) {}
};

class LogOn
{
public:
	MessageHeader header;
	uint32_t      sessionId;
	uint32_t      isClient0;
	uint32_t      isWrite;

	LogOn() : header((uint32_t)MessageType::LOG_ON, sizeof(LogOn)) {}
};

class TextMessage
{
public:
	MessageHeader header;
	uint8_t       data[];

	TextMessage() : header((uint32_t)MessageType::TEXT_MESSAGE, sizeof(TextMessage)){}
};

class ClientSocket;

class Session
{
public:
	ClientSocket* pClient0;
	ClientSocket* pClient1;
};

Session* getSession(uint32_t sessionId);

class ClientSocket : public std::enable_shared_from_this<ClientSocket>
{
public:
	bool useTLS;

	std::shared_ptr<asio::ip::tcp::socket> socket;
	std::shared_ptr<asio::ssl::stream<asio::ip::tcp::socket>> socketSSL;

	Session* pSession;
	bool     isClient0;

	std::recursive_mutex writeBufferLock;
	std::vector<char>    readBuffer;
	uint32_t             readDataIt;

	ClientSocket(asio::ip::tcp::socket& socket) :  useTLS(false)
	{
		this->socket = std::make_shared<asio::ip::tcp::socket>(std::move(socket));
		this->readBuffer.resize(setup::maxMessageSize + sizeof(MessageHeader));
		this->readDataIt = 0;
	}

	ClientSocket(asio::ssl::stream<asio::ip::tcp::socket>& socket) : useTLS(true)
	{
		this->socketSSL = std::make_shared<asio::ssl::stream<asio::ip::tcp::socket>>(std::move(socket));
		this->readBuffer.resize(setup::maxMessageSize + sizeof(MessageHeader));
		this->readDataIt = 0;
	}

	~ClientSocket()
	{
		printf("destructor ClientSocket\n");
	}

	bool writeSocket(uint8_t* pBuffer, uint32_t bufferSize)
	{
		try
		{
			std::unique_lock<std::recursive_mutex> lock(this->writeBufferLock);

			size_t writtenBytes = 0;

			if (true == this->useTLS)
			{
				writtenBytes = asio::write(*this->socketSSL, asio::buffer(pBuffer, bufferSize));
			}
			else
			{
				writtenBytes = asio::write(*this->socket, asio::buffer(pBuffer, bufferSize));
			}

			return (writtenBytes == bufferSize);
		}
		catch (asio::system_error e)
		{
			std::cout << e.what() << std::endl;
		}
		catch (std::exception e)
		{
			std::cout << e.what() << std::endl;
		}
		catch (...)
		{
			std::cout << "Some other exception" << std::endl;
		}

		return false;
	}

	void asyncReadSocket(uint32_t messageSize)
	{
		auto self(this->shared_from_this());

		auto readMessageLambda = [&, self](const asio::error_code& errorCode, std::size_t length)
		{
			this->readDataIt += (uint32_t)length;

			if (0 != errorCode.value())
			{
				printf("errorCode= %u, message=%s\n", errorCode.value(), errorCode.message().c_str());
			}

			MessageHeader* pMessageHeader = (MessageHeader*)this->readBuffer.data();

			if (pMessageHeader->messageLength > setup::maxMessageSize)
			{
				printf("Message to big -> readNewMessage threadId=%u\n", GetCurrentThreadId());
				//connection should be closed
				return;
			}

			if (this->readDataIt < pMessageHeader->messageLength)
			{
				printf("Message incomplete read rest part threadId=%u\n", GetCurrentThreadId());
				asyncReadSocket(pMessageHeader->messageLength - this->readDataIt); // bypass already read header
				return;
			}

			MessageType messageType = (MessageType)pMessageHeader->messageType;

			switch (messageType)
			{
				case MessageType::LOG_ON:
				{
					LogOn* pLogOn = (LogOn*)pMessageHeader;
					printf("LOG_ON message sessionId=%u, isClient0=%u\n", pLogOn->sessionId, pLogOn->isClient0);
					
					this->isClient0 = pLogOn->isClient0;
					this->pSession  = getSession(pLogOn->sessionId);
					
					if (this->isClient0)
						this->pSession->pClient0 = this;
					else
						this->pSession->pClient1 = this;
			
				}
				break;
				case MessageType::TEXT_MESSAGE:
				{
					TextMessage* pTextMessage = (TextMessage*)pMessageHeader;
			
					if (nullptr != pSession)
					{
						if (this->isClient0)
						{
							if (nullptr != pSession->pClient1)
							{
								pSession->pClient1->writeSocket((uint8_t*)pTextMessage, pTextMessage->header.messageLength);
							}
						}
						else
						{
							if (nullptr != pSession->pClient0)
							{
								pSession->pClient0->writeSocket((uint8_t*)pTextMessage, pTextMessage->header.messageLength);
							}
						}
					}
				}
				break;
			}

			this->readDataIt = 0; // reset buffer
			printf("Read new message readDataIt=%u, threadId=%u\n", this->readDataIt, GetCurrentThreadId());
			asyncReadSocket(sizeof(MessageHeader));
		};

		printf("adding async_read_some readIt=%u, threadId=%u\n", this->readDataIt, GetCurrentThreadId());
		if (true == this->useTLS)
		{
			asio::async_read(*this->socketSSL, asio::buffer(readBuffer.data() + this->readDataIt, messageSize), readMessageLambda);
		}
		else
		{
			asio::async_read(*this->socket, asio::buffer(readBuffer.data() + this->readDataIt, messageSize), readMessageLambda);
		}
	}
};

class SSLRelayServer
{
public:
	static SSLRelayServer* pSingleton;

	asio::io_context   ioContext;
	asio::ssl::context sslContext;

	std::vector<std::thread> workerThreads;

	asio::ip::tcp::acceptor* pAcceptor;
	asio::ip::tcp::endpoint* pEndpoint;

	bool useTLS;

	Session* sessions[setup::maxSessionsNum];

	SSLRelayServer() : pAcceptor(nullptr), pEndpoint(nullptr), sslContext(asio::ssl::context::tlsv13_server)
	{
		this->useTLS     = false;
		this->pSingleton = this;

		this->sslContext.set_password_callback(std::bind(&SSLRelayServer::getPrivateKeyPEMFilePassword, this));
		this->sslContext.use_certificate_chain_file("server_cert.pem");
		this->sslContext.use_private_key_file("server_private_key.pem", asio::ssl::context::pem);
	}

	static SSLRelayServer* getSingleton()
	{
		return pSingleton;
	}

	std::string getPrivateKeyPEMFilePassword() const
	{
		return "";
	}

	void addClientSocket(asio::ip::tcp::socket& socket)
	{
		std::make_shared<ClientSocket>(socket)->asyncReadSocket(sizeof(MessageHeader));
	}

	void addSSLClientToken(asio::ssl::stream<asio::ip::tcp::socket>& sslSocket)
	{
		std::make_shared<ClientSocket>(sslSocket)->asyncReadSocket(sizeof(MessageHeader));
	}

	void handleAccept(asio::ip::tcp::socket& socket, const asio::error_code& errorCode)
	{
		if (!errorCode)
		{
			printf("accepted\n");

			if (true == socket.is_open())
			{
				asio::ip::tcp::no_delay no_delay_option(true);
				socket.set_option(no_delay_option);

				addClientSocket(socket);
			}
		}
	}

	void handleAcceptTLS(asio::ip::tcp::socket& socket, const asio::error_code& errorCode)
	{
		if (!errorCode)
		{
			printf("accepted\n");

			if (true == socket.is_open())
			{
				asio::ip::tcp::no_delay no_delay_option(true);

				asio::ssl::stream<asio::ip::tcp::socket> sslStream(std::move(socket), this->sslContext);

				try
				{
					sslStream.handshake(asio::ssl::stream_base::server);
					sslStream.lowest_layer().set_option(no_delay_option);

					addSSLClientToken(sslStream);
				}
				catch (asio::system_error e)
				{
					std::cout << e.what() << std::endl;
					return;
				}
				catch (std::exception e)
				{
					std::cout << e.what() << std::endl;
					return;
				}
				catch (...)
				{
					std::cout << "Other exception" << std::endl;
					return;
				}

			}

		}
	}

	void startAccept()
	{
		auto acceptHandler = [this](const asio::error_code& errorCode, asio::ip::tcp::socket socket)
		{
			printf("acceptHandler\n");

			this->handleAccept(socket, errorCode);

			this->startAccept();
		};

		auto tlsAcceptHandler = [this](const asio::error_code& errorCode, asio::ip::tcp::socket socket)
		{
			printf("tlsAcceptHandler\n");

			this->handleAcceptTLS(socket, errorCode);

			this->startAccept();
		};

		if (true == this->useTLS)
		{
			this->pAcceptor->async_accept(tlsAcceptHandler);
		}
		else
		{
			this->pAcceptor->async_accept(acceptHandler);
		}
	}

	bool run(uint32_t servicePort, uint32_t threadsNum, bool useTLS)
	{
		this->useTLS = useTLS;

		this->pEndpoint = new asio::ip::tcp::endpoint(asio::ip::tcp::v4(), servicePort);
		this->pAcceptor = new asio::ip::tcp::acceptor(ioContext, *pEndpoint);

		this->pAcceptor->listen();

		this->startAccept();

		for (uint32_t threadIt = 0; threadIt < threadsNum; ++threadIt)
		{
			this->workerThreads.emplace_back([&]() {
#ifdef WINDOWS
				SetThreadDescription(GetCurrentThread(), L"SSLRelayServer worker thread");
#endif
				this->ioContext.run(); }
			);
		}

		return true;
	}

	Session* getSession(uint32_t sessionId)
	{
		if (nullptr == this->sessions[sessionId])
		{
			this->sessions[sessionId] = new Session();
		}

		return this->sessions[sessionId];
	}
};

SSLRelayServer* SSLRelayServer::pSingleton = nullptr;

Session* getSession(uint32_t sessionId)
{
	SSLRelayServer* pServer  = SSLRelayServer::getSingleton();
	Session*        pSession = pServer->getSession(sessionId);
	return pSession;
}

class Client
{
public:
	asio::ssl::context sslContext;

	std::shared_ptr<asio::ip::tcp::socket>                    socket;
	std::shared_ptr<asio::ssl::stream<asio::ip::tcp::socket>> socketSSL;

	asio::io_context ioContext;

	bool useTLS;
	bool isClient0;

	uint32_t             readDataIt;
	std::vector<uint8_t> readBuffer;

	asio::io_service::strand readWriteStrand;

	std::recursive_mutex writeMutex;
	uint32_t             bytesSent;
	uint32_t             sendBufferSize;
	std::shared_mutex    sendMutex;

	uint32_t messageCounter;

	Client() : sslContext(asio::ssl::context::tlsv13_client), readWriteStrand(ioContext)
	{
		sslContext.load_verify_file("server_cert.pem");

		using asio::ip::tcp;
		using std::placeholders::_1;
		using std::placeholders::_2;
		sslContext.set_verify_callback(std::bind(&Client::verifyCertificate, this, _1, _2));

		this->readBuffer.resize(setup::maxMessageSize);
		this->readDataIt = 0;

		this->bytesSent      = 0;
		this->sendBufferSize = 0;
		//this->readWriteStrand = std::move( asio::make_strand(this->ioContext) );
		this->messageCounter = 0;
	}

	bool verifyCertificate(bool preverified, asio::ssl::verify_context& verifyCtx)
	{
		return true;
	}

	size_t writeSSLSocket(uint8_t* pBuffer, uint32_t bufferSize)
	{
		std::unique_lock<std::recursive_mutex> lock(this->writeMutex);
		this->bytesSent      = 0;
		this->sendBufferSize = bufferSize;

		this->sendMutex.lock();

		auto writeMessageLambda = [this](const std::error_code& code, std::size_t size)
		{
			this->bytesSent += (uint32_t)size;

			if (0 != code.value())
			{
				printf("error = %u, message = %s, threadId=%u\n", code.value(), code.message(), GetCurrentThreadId());
				int32_t stop = 0;
			}

			if ((this->bytesSent == this->sendBufferSize))
			{
				this->sendMutex.unlock();
			}
		};

		asio::async_write(*this->socketSSL, asio::buffer(pBuffer, bufferSize), asio::bind_executor(readWriteStrand,writeMessageLambda));

		std::unique_lock<std::shared_mutex> waitForSend(this->sendMutex);

		return this->bytesSent;
	}

	void asyncReadSocket(uint32_t messageSize)
	{
		auto readMessageLambda = [&](const asio::error_code& errorCode, std::size_t length)
		{
			this->readDataIt += (uint32_t)length;

			if (0 != errorCode.value())
			{
				printf("errorCode= %u, message=%s\n", errorCode.value(), errorCode.message().c_str());
			}

			MessageHeader* pMessageHeader = (MessageHeader*)this->readBuffer.data();
			
			if (pMessageHeader->messageLength > setup::maxMessageSize)
			{
				printf("Message to big -> readNewMessage threadId=%u\n", GetCurrentThreadId());
				//close connection
				return;
			}

			if (this->readDataIt < pMessageHeader->messageLength)
			{
				printf("Message incomplete read rest part threadId=%u\n", GetCurrentThreadId());
				asyncReadSocket(pMessageHeader->messageLength - this->readDataIt); // bypass already read header
				return;
			}
			
			MessageType messageType = (MessageType)pMessageHeader->messageType;
			
			switch (messageType)
			{
				case MessageType::TEXT_MESSAGE:
				{
					TextMessage* pTextMessage = (TextMessage*)pMessageHeader;
			
					printf("messageLength = %u, readIt = %u\n", pTextMessage->header.messageLength, this->readDataIt);
					printf("TEXT_MESSAGE: %s, threadId=%u\n", pTextMessage->data, GetCurrentThreadId());
			
					++this->messageCounter;
				}
				break;
			}
			
			this->readDataIt = 0; // reset buffer
			printf("Read new message readDataIt=%u, threadId=%u\n", this->readDataIt, GetCurrentThreadId());
			asyncReadSocket(sizeof(MessageHeader));
		};

		printf("adding async_read_some readIt=%u, threadId=%u\n", this->readDataIt, GetCurrentThreadId());
		if (this->useTLS)
		{
			asio::async_read(*this->socketSSL, asio::buffer(readBuffer.data() + this->readDataIt, messageSize), asio::bind_executor(readWriteStrand, readMessageLambda));
		}
		else
		{
			asio::async_read(*this->socket, asio::buffer(readBuffer.data() + this->readDataIt, messageSize), readMessageLambda);
		}
	}

	void run(uint32_t sessionId, bool isClient0, bool useTLS, uint32_t servicePort)
	{
		this->useTLS    = useTLS;
		this->isClient0 = isClient0;
		
		if (useTLS)
		{
			this->socketSSL = std::make_shared<asio::ssl::stream<asio::ip::tcp::socket>>(ioContext, sslContext);
		}
		else
		{
			this->socket = std::make_shared<asio::ip::tcp::socket>(ioContext);
		}
		
		asio::ip::tcp::resolver resolver(ioContext);
		
		asio::ip::tcp::resolver::results_type endpoints = resolver.resolve(asio::ip::tcp::v4(), "127.0.0.1", std::to_string(servicePort));
		
		asio::ip::tcp::no_delay no_delay_option(true);
		
		if (true == useTLS)
		{
			asio::ip::tcp::endpoint sslEndpoint = asio::connect(socketSSL->lowest_layer(), endpoints);
			socketSSL->handshake(asio::ssl::stream_base::client);
			socketSSL->lowest_layer().set_option(no_delay_option);
		}
		else
		{
			asio::ip::tcp::endpoint endpoint = asio::connect(*socket, endpoints);
			socket->set_option(no_delay_option);
		}

		LogOn logOn;
		logOn.isClient0 = isClient0;
		logOn.sessionId = sessionId;
		
		const uint32_t logOnSize = sizeof(logOn);
		
		if (true == useTLS)
		{
			size_t transferred = asio::write(*socketSSL, asio::buffer(&logOn, sizeof(LogOn)));
		}
		else
		{
			size_t transferred = asio::write(*socket, asio::buffer(&logOn, sizeof(LogOn)));
		}

		asyncReadSocket(sizeof(MessageHeader));

		auto ioContextHandler = [&] {
#ifdef WINDOWS
			if (isClient0)
			{
				SetThreadDescription(GetCurrentThread(), L"ioContext Client0");
				printf("ioContext threadId=%u\n", GetCurrentThreadId());
			}
			else
			{
				SetThreadDescription(GetCurrentThread(), L"ioContext Client1");
				printf("ioContext threadId=%u\n", GetCurrentThreadId());
			}
#endif
			ioContext.run();
			printf("ioContext run exit\n");
		};
		std::thread thread = std::thread(ioContextHandler);

		uint32_t counter = 0;
		
		while (1 == 1)
		{
			std::string number = std::to_string(counter);
			std::string message;
		
			if (this->isClient0)
			{
				message = "Client0: " + number;
			}
			else
			{
				message = "Client1: " + number;
			}
		
			TextMessage textMessage;
			textMessage.header.messageLength += message.size() + 1;
		
			if (this->useTLS)
			{
				size_t transferred = writeSSLSocket((uint8_t*)&textMessage, sizeof(TextMessage));
				transferred        = writeSSLSocket((uint8_t*)message.c_str(), message.length() + 1);
			}
			else
			{
				size_t transferred = asio::write(*socket, asio::buffer(&textMessage, sizeof(TextMessage)));
				transferred        = asio::write(*socket, asio::buffer(message.c_str(), message.length() + 1));
			}
		
			++counter;
		}
	}
};

void clientTest(uint32_t sessionId, bool isClient0, bool useTLS, uint32_t servicePort)
{
#ifdef WINDOWS
	if (isClient0)
	{
		SetThreadDescription(GetCurrentThread(), L"Client0");
	}
	else
	{
		SetThreadDescription(GetCurrentThread(), L"Client1");
	}
#endif

	Client client;

	printf("sizeof(MessageHeader) = %u\n", sizeof(MessageHeader));
	printf("sizeof(TextMessage) = %u\n", sizeof(TextMessage));
	
	client.run(sessionId, isClient0, useTLS, servicePort);

	while (1 == 1)
	{
		Sleep(1000);
	}
}

void SSLRelayTest()
{
	SSLRelayServer relayServer;

	const uint32_t threadsNum  = 1;
	const bool     useTLS      = true;
	const uint32_t servicePort = 777;
	relayServer.run(servicePort, threadsNum, useTLS);

	Sleep(5000);

	std::vector<std::thread> threads;

	const uint32_t sessionId = 0;
	threads.emplace_back(clientTest, sessionId, true, useTLS, servicePort);
	threads.emplace_back(clientTest, sessionId, false, useTLS, servicePort);
	
	for (std::thread& threadIt : threads)
	{
		threadIt.join();
	}
}

}

[SSLRelayServer.txt](https://github.com/chriskohlhoff/asio/files/10048026/SSLRelayServer.txt)

**Comment by klemens-morgenstern** [comment]
Why are you using multiple io contexts?

**Comment by p-jaholkowski** [comment]
This is implementation of SSL relay server and client.
So to make a test and check if this work we need server and two clients.
Normally server and two clients are three diffrent host so I'm guessing each of them has
it's own iocontext because they can't share it.
I'm launchin everything on one host to check if this work so I'm using three diffrent iocontexts.
But each iocontext run on only one thread.
https://think-async.com/Asio/asio-1.24.0/doc/asio/examples/cpp14_examples.html
This samples of async_tcp_echo_server and async_tcp_echo_client also don't share iocontext
because there are two diffrent programs.
I started from implementation on normal sockets when you change variable useTLS to false it will use normal
sockets and then it works without problem.
Your implying that I can't test that this way with SSL sockets?

**Comment by p-jaholkowski** [comment]
Okay I figured it out by writting many diffrent samples of code including SSL sockets.
When asio::io_context is already running you can't simply schedule asio::async_write or asio::async_read from thread which is not
associated with strand connected to that socket. 

So when there is:
`
asio::async_write(*this->socketSSL, asio::buffer(pBuffer, bufferSize), asio::bind_executor(readWriteStrand,writeMessageLambda));
`
but thread which is executing is not running from readWriteStrand strand then it should be written as:
`
asio::post(ioContext, asio::bind_executor(readWriteStrand, [&]() {asio::async_read(*this->socketSSL, asio::buffer(readBuffer.data() + this->readDataIt, messageSize), asio::bind_executor(readWriteStrand, readMessageLambda)); }));`
