### ISSUE TITLE
pipline.cpp

### ISSUE THREAD

**Issue by yangjunrui** [chriskohlhoff/asio#122]
template <class T, class F>
std::future<void> pipeline(queue_back<T> in, F f)
{
  // Get the function's associated executor, defaulting to thread_executor.
  auto ex = get_associated_executor(f, thread_executor());

  // Run the function, and as we're the last stage return a future so that the
  // caller can wait for the pipeline to finish.
  return post(ex, package([in, f = std::move(f)]() mutable { f(in); }));
}

the call of post brings such a problem, enviroment : ubuntu,qt,
/usr/include/c++/5/bits/alloc_traits.h:530: error: 'using allocator_type = class std::allocator<void> {aka class std::allocator<void>}' has no member named 'construct'
  { __a.construct(__p, std::forward<_Args>(__args)...); }
    ^

**Comment by 2underscores-vic** [comment]
#112

**Comment by yangjunrui** [comment]
thanks then how to cope with it?
