### ISSUE TITLE
SSL headers do not compile if OpenSSL is compiled with OPENSSL_NO_DEPRECATED defined

### ISSUE THREAD

**Issue by alexeikh-promon** [chriskohlhoff/asio#126]
# How to reproduce

1. Build OpenSSL with "no-deprecated" option. As a result, in OpenSSL installation, in file opensslconf.h, OPENSSL_NO_DEPRECATED will be defined.
2. Try to compile a source file with the following include line:

    `#include <asio/ssl/stream.hpp>`

Library versions that I used to reproduce the issue:
- OpenSSL 1.0.2h
- Boost.Asio 1.61 (should correspond to non-Boost Asio 1.10.7)

# The issue

Compilation will fail, because the compiler will not be able to find the following functions:
- DH_free()
- RSA_free()
- CRYPTO_set_id_callback()

Another complaint about this issue: http://permalink.gmane.org/gmane.comp.lib.boost.asio.user/5920

# Suggested solutions

- For DH_free() and RSA_free(): A pull-request with the solution already exists: https://github.com/chriskohlhoff/asio/pull/104

- For CRYPTO_set_id_callback(): Wrap CRYPTO_set_id_callback() call and openssl_init_base::do_init::openssl_id_func() function into

    `#if (OPENSSL_VERSION_NUMBER < 0x10000000L)`

# More info

CRYPTO_set_id_callback() call does not have any effect, checked on OpenSSL 1.0.2h. Even if OPENSSL_NO_DEPRECATED is not defined (i.e. the deprecated code is compiled in), CRYPTO_set_id_callback() only sets a function pointer that is never used afterwards.

CRYPTO_set_id_callback() is deprecated since OpenSSL 1.0.0.

That's how LibAV patched similar issue: https://patches.libav.org/patch/11479/ .

**Comment by chriskohlhoff** [comment]
Fixed by 69e44a4cc6eb5ba21ede409779a7b777c0eb3869.
