### ISSUE TITLE
Status of ssl::stream::get_io_service()

### ISSUE THREAD

**Issue by 2underscores-vic** [chriskohlhoff/asio#132]
`basic_stream_socket::get_io_service()` is marked as deprecated. But what about `ssl::stream::get_io_service()`? It doesn't have `get_executor()` and doestn't compile if `ASIO_NO_DEPRECATED` is defined.

P.S. And why `get_io_service()` was deprecated? What should be used instead to obtain io_service from socket?

**Comment by vinniefalco** [comment]
How about calling `lowest_layer().get_io_service()`? That works for both sockets and SSL streams.

**Comment by 2underscores-vic** [comment]
I use `next_layer().get_executor().context()`. But I'm trying to understand why `get_io_service()`/`get_io_context()` was deprecated. Every socket has associated `io_service`/`io_context` - we need to have one to construct it. And every socket has executor, every executor has associated `io_service`/`io_context`. Why deprecate handy and short getter?

**Comment by 2underscores-vic** [comment]
Related #252

**Comment by vinniefalco** [comment]
I see the rationale, it is to trim the interface only to exactly that which is necessary. This is important to get consensus in the committee meetings for voting Net-TS into the standard. If you need a handy and short getter, you can always implement a simple free function that works with any object and calls `get_executor().context()` for you.

**Comment by 2underscores-vic** [comment]
Since ASIO 1.13 socket and other stuff can be constructed using just executor. So `get_io_service()` isn't needed anymore.
