### ISSUE TITLE
any_executor().query() segfaults instead of throwing bad_executor

### ISSUE THREAD

**Issue by ecatmur** [chriskohlhoff/asio#1322]
Motivating example (incorrect, but an easy mistake to make):
```c++
asio::any_io_executor ex;
asio::ip::tcp::socket sock(ex);
```
Prior to https://github.com/chriskohlhoff/asio/commit/9d420678b4f89d20585f42f85deb0838e3597991 this would throw `asio::execution::bad_executor`; after that commit it just segfaults.

Online example using Boost.Asio (1.80 vs 1.81): https://godbolt.org/z/WGvMEWr8P

We noticed this because clang-tidy started warning that `object_fns_` could be indirected while null.

Presumably `query`/`require`/`prefer` need to check for null `target_` the same way `execute` does?

**Comment by ecorm** [comment]
I get clang-tidy warnings whenever I initialize executors for this same reason. The warnings also occur with `asio::any_completion_executor` which I now use extensively.

**Comment by ecatmur** [comment]
Possibly fixed by 6c4a16680caa5e63e742f7041cf1fccaa30f1841, checking

**Comment by ecatmur** [comment]
Confirming fixed: https://godbolt.org/z/7c5PMchn3
