### ISSUE TITLE
WebSocket (tcp::no_delay not working) :- 2 messages concatenate at client

### ISSUE THREAD

**Issue by 625Lalit** [chriskohlhoff/asio#1335]
I am new to boost library. I am writing a WebSocket server. But facing a problem that when I send a message to a client 2 messages concatenate like first I send "Hello" and then "World". but the client received "HelloWorld". I am attaching my code as a zip file. To handle this I have done this kind of change in code:-

	ws_.async_write(m_WriteBuffer.data(),
				beast::bind_front_handler(
					&WebSocketSession::on_write,
					shared_from_this()));
	Sleep(100);

I have added the sleep after the send then it works fine.
 I have also used option TCP NO_Delay but still, the issue is there.
 
**Declaration:-**
boost::asio::io_context g_ioc{ 10 };
ssl::context g_ctx{ ssl::context::tlsv12 };
tcp::acceptor g_acceptor(net::make_strand(g_ioc));

**Used somewhere in code:-**
 g_acceptor.set_option(tcp::no_delay(true), ec);
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::WebSocketListener set_option(No delay) failed, error message: %s", ec.message().c_str());
		return;
	}

Please suggest, how I can solve this

[WebSocketServer.zip](https://github.com/chriskohlhoff/asio/files/12206424/WebSocketServer.zip)

**Comment by klemens-morgenstern** [comment]
Please dont attach zip files, but post the code verbatim. Mayeb use godbolt.

**Comment by 625Lalit** [comment]
@klemens-morgenstern 
Please find code below

**WebSocketServer.h**
#pragma once
//
// Copyright (c) 2016-2019 Vinnie Falco (vinnie dot falco at gmail dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
// Official repository: https://github.com/boostorg/beast
//

//------------------------------------------------------------------------------
//
// Example: WebSocket SSL server, asynchronous
//
//------------------------------------------------------------------------------

#include "dependencies/example/common/server_certificate.hpp"
#include "xlogger.h"
#include "TSWebSocket.h"

#include <boost/beast/core.hpp>
#include <boost/beast/ssl.hpp>
#include <boost/beast/websocket.hpp>
#include <boost/beast/websocket/ssl.hpp>
#include <boost/asio/strand.hpp>
#include <boost/asio/dispatch.hpp>
#include <boost/lexical_cast.hpp>
#include <algorithm>
#include <cstdlib>
#include <functional>
#include <iostream>
#include <memory>
#include <string>
#include <thread>
#include <vector>
#include <map>
#include <queue>

namespace beast = boost::beast;         // from <boost/beast.hpp>
namespace http = beast::http;           // from <boost/beast/http.hpp>
namespace websocket = beast::websocket; // from <boost/beast/websocket.hpp>
namespace net = boost::asio;            // from <boost/asio.hpp>
namespace ssl = boost::asio::ssl;       // from <boost/asio/ssl.hpp>
using tcp = boost::asio::ip::tcp;       // from <boost/asio/ip/tcp.hpp>

//------------------------------------------------------------------------------

// The following ifdef block is the standard way of creating macros which make exporting 
// from a DLL simpler. All files within this DLL are compiled with the WEBSOCKETSERVER_EXPORTS
// symbol defined on the command line. This symbol should not be defined on any project
// that uses this DLL. This way any other project whose source files include this file see 
// WEBSOCKETSERVER_API functions as being imported from a DLL, whereas this DLL sees symbols
// defined with this macro as being exported.
#ifdef WEBSOCKETSERVER_EXPORTS
#define WEBSOCKETSERVER_API __declspec(dllexport)
#else
#define WEBSOCKETSERVER_API __declspec(dllimport)
#endif
class WebSocketSession;
// Accepts incoming connections and launches the sessions
class WEBSOCKETSERVER_API WebSocketListener : public std::enable_shared_from_this<WebSocketListener>
{
private:
	/*net::io_context& m_ioc;
	ssl::context& m_ctx;
	tcp::acceptor m_acceptor;*/
	
	std::shared_ptr<ISocketEvents> m_pEvent;
	CRITICAL_SECTION m_hCSClientidSession;
	std::map<UINT, std::shared_ptr<WebSocketSession>> m_mapClientidSession;
public:
	WebSocketListener(tcp::endpoint endpoint);
	~WebSocketListener();
	void Run();
	void setEventHandler(std::shared_ptr<ISocketEvents> pEvent);
	bool SendMessageToClient(UINT uClientid, const char* pData, UINT uLen);
	bool RemoveClient(UINT uClientid);
private:
	void do_accept();
	void on_accept(beast::error_code ec, tcp::socket socket);
};

//------------------------------------------------------------------------------

// Echoes back all received WebSocket messages
class WebSocketSession : public std::enable_shared_from_this<WebSocketSession>
{
	websocket::stream<beast::ssl_stream<beast::tcp_stream>> ws_;
	beast::flat_buffer m_ReadBuffer;
	beast::flat_buffer m_WriteBuffer;
	std::shared_ptr<ISocketEvents> m_pEvent;
	SOCKET m_SocketDescriptor;
	//CRITICAL_SECTION m_csMessageQueue;
	std::queue<std::string> m_MessageQueue;
private:
	void SendMeassageAsync();
public:
	// Take ownership of the socket
	WebSocketSession(tcp::socket&& socket, ssl::context& ctx, std::shared_ptr<ISocketEvents> pEvent, SOCKET socketId);
	void run();
	void on_run();
	void on_handshake(beast::error_code ec);
	void on_accept(beast::error_code ec);
	void on_upgrade(beast::error_code ec, size_t);
	void do_read();
	void on_read(beast::error_code ec, std::size_t bytes_transferred);
	UINT getSocketDescriptor();
	void on_write(beast::error_code ec, std::size_t bytes_transferred);
	bool SendMessageToClient(const char* pData, UINT uLen);
};

//------------------------------------------------------------------------------

// Factory function that creates instances of the Server Protocol object.
WEBSOCKETSERVER_API std::shared_ptr<WebSocketListener> __stdcall InitializeWebSocketListener(unsigned short port, int maxThreads, std::string certificate, std::string privateKey);
//------------------------------------------------------------------------------




**WebSocketServer.cpp**

#include "stdafx.h"
#include "WebSocketServer.h"
//------------------------------------------------------------------------------

static std::shared_ptr<WebSocketListener> objWebSocketListener = nullptr;
boost::asio::io_context g_ioc{ 10 };
ssl::context g_ctx{ ssl::context::tlsv12 };
tcp::acceptor g_acceptor(net::make_strand(g_ioc));
http::request<http::string_body> g_upgrade_request;
void RunIOContextThread();

WEBSOCKETSERVER_API std::shared_ptr<WebSocketListener> __stdcall InitializeWebSocketListener(unsigned short port, int maxThreads, std::string certificate, std::string privateKey)
{
	auto const address = net::ip::make_address("0.0.0.0");

	// The io_context is required for all I/O
	//boost::asio::io_context ioc/*{ maxThreads }*/;

	// The SSL context is required, and holds certificates
	//ssl::context ctx{ ssl::context::tlsv12 };

	// This holds the self-signed certificate used by the server
	load_server_certificate(g_ctx, certificate, privateKey);

	// Create and launch a listening port
	objWebSocketListener = std::make_shared<WebSocketListener>(tcp::endpoint{ address, port });
	objWebSocketListener->Run();

	// Run the I/O service on the requested number of threads
	for (int i = 0; i < 10; ++i)
	{
		std::thread ioContextThread(&RunIOContextThread);
		ioContextThread.detach();
	}

	return objWebSocketListener->shared_from_this();
}

void RunIOContextThread()
{
	g_ioc.run();
}

//------------------------------------------------------------------------------

// Listener class
WebSocketListener::~WebSocketListener()
{
	int i = 0;
	i++;
	int j = i + 13;
}

WebSocketListener::WebSocketListener(tcp::endpoint endpoint) :
	/*: g_ioc(ioc)
	, g_ctx(ctx)
	, g_acceptor(net::make_strand(ioc))*/
	m_pEvent(NULL)
{
	InitializeCriticalSection(&m_hCSClientidSession);
	beast::error_code ec;

	// Open the acceptor
	g_acceptor.open(endpoint.protocol(), ec);
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::WebSocketListener open failed, error message: %s", ec.message().c_str());
		return;
	}

	// Allow address reuse
	g_acceptor.set_option(net::socket_base::reuse_address(true), ec);
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::WebSocketListener set_option failed, error message: %s", ec.message().c_str());
		return;
	}


	g_acceptor.set_option(tcp::no_delay(true), ec);
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::WebSocketListener set_option(No delay) failed, error message: %s", ec.message().c_str());
		return;
	}

	// Bind to the server address
	g_acceptor.bind(endpoint, ec);
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::WebSocketListener bind failed, error message: %s", ec.message().c_str());
		return;
	}

	// Start listening for connections
	g_acceptor.listen(net::socket_base::max_listen_connections, ec);
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::WebSocketListener listen failed, error message: %s", ec.message().c_str());
		return;
	}
	else
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_INFO, "WebSocketListener::WebSocketListener Started listening at %s:%hu", g_acceptor.local_endpoint().address().to_string().c_str(), g_acceptor.local_endpoint().port());
	}
}

bool WebSocketListener::RemoveClient(UINT uClientid) 
{
	EnterCriticalSection(&m_hCSClientidSession);
	auto iter = m_mapClientidSession.find(uClientid);
	if (iter != m_mapClientidSession.end())
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_INFO, "WebSocketListener::RemoveClient Removed from map uClientid : %d", uClientid);
		m_mapClientidSession.erase(iter);
		return true;
	}	
	else
	{
		return false;
	}
	LeaveCriticalSection(&m_hCSClientidSession);
}

bool WebSocketListener::SendMessageToClient(UINT uClientid, const char* pData, UINT uLen)
{
	bool bRet = false;
	auto iter = m_mapClientidSession.find(uClientid);
	if (iter != m_mapClientidSession.end())
	{
		bRet = iter->second->SendMessageToClient(pData, uLen);
	}
	else
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::SendMessageToClient ClientID: %d not found", uClientid);
	}
	return bRet;
}

void WebSocketListener::setEventHandler(std::shared_ptr<ISocketEvents> pEvent)
{
	m_pEvent = pEvent;
}


// Start accepting incoming connections
void WebSocketListener::Run()
{
	do_accept();
}

void WebSocketListener::do_accept()
{
	// The new connection gets its own strand
	g_acceptor.async_accept(
		net::make_strand(g_ioc),
		beast::bind_front_handler(
			&WebSocketListener::on_accept,
			shared_from_this()));
}

void WebSocketListener::on_accept(beast::error_code ec, tcp::socket socket)
{
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::on_accept accept failed, error SocketID: %d, message: %s", socket.native_handle(), ec.message().c_str());
	}
	else
	{
		std::string sClientIp = socket.remote_endpoint().address().to_string();
		unsigned short uiClientPort = socket.remote_endpoint().port();
		SOCKET socketId = socket.native_handle();
		// Create the WebSocketSession and run it
		std::shared_ptr<WebSocketSession> objSession = std::make_shared<WebSocketSession>(std::move(socket), g_ctx, m_pEvent, socketId);
		if (objSession != nullptr)
		{
			objSession->run();
			auto itr = m_mapClientidSession.find(socketId);
			if (itr != m_mapClientidSession.end()) 
			{
				itr->second = objSession;
				stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::on_accept update client id : %d", socketId);
			}
			else
			{
				m_mapClientidSession.insert(pair<unsigned int, std::shared_ptr<WebSocketSession >>(socketId, objSession));
				stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketListener::on_accept insert client id : %d", socketId);
			}
			
			stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_INFO, "WebSocketListener::on_accept Incoming connection request from SocketID: %d, IP: %s Port: %hu", socketId, sClientIp.c_str(), uiClientPort);
		}
	}

	// Accept another connection
	do_accept();
}

//------------------------------------------------------------------------------

// Session class
WebSocketSession::WebSocketSession(tcp::socket&& socket, ssl::context& ctx, std::shared_ptr<ISocketEvents> pEvent, SOCKET socketId)
	: ws_(std::move(socket), ctx), m_pEvent(pEvent), m_SocketDescriptor(socketId)
{
	m_WriteBuffer.reserve(1000);
	m_ReadBuffer.reserve(1000);
}

// Get on the correct executor
void WebSocketSession::run()
{
	// We need to be executing within a strand to perform async operations
	// on the I/O objects in this WebSocketSession. Although not strictly necessary
	// for single-threaded contexts, this example code is written to be
	// thread-safe by default.
	net::dispatch(ws_.get_executor(),
		beast::bind_front_handler(
			&WebSocketSession::on_run,
			shared_from_this()));
}

// Start the asynchronous operation
void WebSocketSession::on_run()
{
	// Set the timeout.
	beast::get_lowest_layer(ws_).expires_after(std::chrono::seconds(30));

	// Perform the SSL handshake
	ws_.next_layer().async_handshake(
		ssl::stream_base::server,
		beast::bind_front_handler(
			&WebSocketSession::on_handshake,
			shared_from_this()));
}

void WebSocketSession::on_handshake(beast::error_code ec)
{
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::on_handshake handshake failed, error SocketID: %d, message: %s", m_SocketDescriptor, ec.message().c_str());
		return;
	}
	// Turn off the timeout on the tcp_stream, because
	// the websocket stream has its own timeout system.
	beast::get_lowest_layer(ws_).expires_never();

	// Set suggested timeout settings for the websocket
	ws_.set_option(
		websocket::stream_base::timeout::suggested(
			beast::role_type::server));

	// Set a decorator to change the Server of the handshake
	ws_.set_option(websocket::stream_base::decorator(
		[](websocket::response_type& res)
	{
		res.set(http::field::server,
			std::string(BOOST_BEAST_VERSION_STRING) +
			" websocket-server-async-ssl");
	}));

	// Accept the websocket handshake
	/*ws_.async_accept(
		beast::bind_front_handler(
			&WebSocketSession::on_accept,
			shared_from_this()));*/

	http::async_read(ws_.next_layer(), m_ReadBuffer, g_upgrade_request,
		beast::bind_front_handler(
			&WebSocketSession::on_upgrade,
			shared_from_this()));
}

void WebSocketSession::on_upgrade(beast::error_code ec, size_t)
{
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::on_upgrade upgrade failed, error SocketID: %d, message: %s", m_SocketDescriptor, ec.message().c_str());
		return;
	}

	stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_INFO, "WebSocketSession::on_upgrade Handshake completed for SocketID: %d, WebSocket Headers: %s", m_SocketDescriptor, boost::lexical_cast<std::string>(g_upgrade_request.base()));

	if (m_pEvent != nullptr)
		m_pEvent->OnConnect(m_SocketDescriptor, true, "", 0);

	// Accept the websocket handshake
	ws_.async_accept(
		g_upgrade_request,
		beast::bind_front_handler(&WebSocketSession::on_accept, shared_from_this()));
}

void WebSocketSession::on_accept(beast::error_code ec)
{
	if (ec)
	{
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::on_accept accept failed, error SocketID: %d, message: %s", m_SocketDescriptor, ec.message().c_str());
		return;
	}
	// Read a message
	do_read();
}

void WebSocketSession::do_read()
{
	if(m_pEvent)
	m_pEvent->onHandShake(m_SocketDescriptor, true);
	// Read a message into our buffer
	ws_.async_read(
		m_ReadBuffer,
		beast::bind_front_handler(
			&WebSocketSession::on_read,
			shared_from_this()));
}

void WebSocketSession::on_read(beast::error_code ec, std::size_t bytes_transferred)
{
	boost::ignore_unused(bytes_transferred);

	// This indicates that the WebSocketSession was closed
	if (ec == websocket::error::closed)
	{
		if (m_pEvent != nullptr)
		{
			m_pEvent->OnConnect(m_SocketDescriptor, false, "", 0);
			stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_INFO, "WebSocketSession::on_read Client disconnected SocketID: %d", m_SocketDescriptor);
		}
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_INFO, "WebSocketSession::on_read Client closed  SocketID: %d", m_SocketDescriptor);
		return;
	}

	if (ec)
	{
		if (m_pEvent != nullptr)
		{
			m_pEvent->OnConnect(m_SocketDescriptor, false, "", 0);
			stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_INFO, "WebSocketSession::on_read Client disconnected SocketID: %d", m_SocketDescriptor);
		}
		stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::on_read read failed, SocketID: %d, error message: %s", m_SocketDescriptor, ec.message().c_str());
		return;
	}

	if (m_pEvent != nullptr)
	{		
		if (m_ReadBuffer.cdata().size() > 0)
		{
			unsigned int iLen = m_ReadBuffer.cdata().size();
			stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_INFO, "WebSocketSession::on_read Client SocketID: %d dataRecv: %d cpacity: %d", m_SocketDescriptor,iLen, m_ReadBuffer.capacity());
			char* pData = new char[iLen];
			memset(pData, 0, iLen);
			if (pData)
			{
				memcpy(pData, m_ReadBuffer.cdata().data(), iLen);
				m_pEvent->OnReceive(m_SocketDescriptor, pData, iLen);
				delete pData;
			}
		}
	}

	m_ReadBuffer.consume(bytes_transferred);

	//// Echo the message
	//ws_.text(ws_.got_text());
	//ws_.async_write(
	//	buffer_.data(),
	//	beast::bind_front_handler(
	//		&WebSocketSession::on_write,
	//		shared_from_this()));
}

UINT WebSocketSession::getSocketDescriptor()
{
	return m_SocketDescriptor;
}

bool WebSocketSession::SendMessageToClient(const char* pData, UINT uLen)
{
	bool bRet = false;
	if (pData != NULL && uLen > 0)
	{
			m_MessageQueue.push(pData);
			stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::sendMessage size: %d SocketID: %d, uLen: %d  capacity: %d m_MessageQueueSize: %ld", m_WriteBuffer.size(), m_SocketDescriptor, uLen, m_WriteBuffer.capacity(), m_MessageQueue.size());
			if (m_MessageQueue.size() == 1)
				SendMeassageAsync();

			return true;
		}
		
	stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::sendMessage invalid message SocketID: %d, uLen: %d", m_SocketDescriptor, uLen);
	return bRet;
}

void WebSocketSession::on_write(beast::error_code ec, std::size_t bytes_transferred)
{
	boost::ignore_unused(bytes_transferred);

	stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::on_write size: %d SocketID: %d, bytes_transferred: %d", m_WriteBuffer.size(), m_SocketDescriptor, bytes_transferred);

	if (ec)
	{
		//stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::on_write write failed, error SocketID: %d, message: %s", m_SocketDescriptor, ec.message().c_str());
		return;
	}

	// Clear the buffer
	m_WriteBuffer.consume(bytes_transferred);
	m_MessageQueue.pop();

	// Do another read
	SendMeassageAsync();
}

void WebSocketSession::SendMeassageAsync()
{
	if (m_MessageQueue.empty())
	{
		//stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::SendMeassageAsync Message queue is empty");
		do_read();
		return;
	}
	std::string strMessage = m_MessageQueue.front();

	//stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::SendMeassageAsync SocketID: %d , size: %d , uLen: %d ,capacity: %d", m_SocketDescriptor, m_WriteBuffer.size(),strMessage.length(), m_WriteBuffer.capacity());

	boost::beast::ostream(m_WriteBuffer) << strMessage;
	//stl::log::trace(stl::log::LOG_GROUP_ERROR, stl::log::LOG_LEVEL_ERROR, "WebSocketSession::SendMeassageAsync After Write SocketID: %d, size: %d ,uLen: %d capacity: %d", m_SocketDescriptor, m_WriteBuffer.size(), strMessage.length(), m_WriteBuffer.capacity());

	ws_.async_write(
		m_WriteBuffer.data(),
		beast::bind_front_handler(
			&WebSocketSession::on_write,
			shared_from_this()));
}

**Comment by klemens-morgenstern** [comment]
Please format it correctly using github markdown.

**Comment by 625Lalit** [comment]
It's done. Sorry for the inconvenience.

**Comment by klemens-morgenstern** [comment]
There's nothing looking wrong with the write.

Thanks, so I assume you logged `strMessage` and that looks correct? What client are you using? How does it go over the wire (have you use wireshark to check?). Because maybe the client concats?
