### ISSUE TITLE
How do i replace boost::thread_group in ASIO Standalone version?

### ISSUE THREAD

**Issue by sailfish009** [chriskohlhoff/asio#135]
Hi, i am using boost asio to use async io.
now i want to replace it with asio standalone version. 
but one thing i can't figured it out, 
my code using boost asio works with boost::thread, 
like boost::thread_group.

how can i replace it with asio standalone version?
without using boost library.

Thanks.

```
boost::asio::io_service work_io_service;
boost::asio::io_service::work work(work_io_service);
boost::thread_group work_threads;

int main()
{

  work_threads.create_thread(
          boost::bind(&boost::asio::io_service::run, &video_io_service));

  return 0;
}

void callback_function(...)
{
  //...
   work_io_service.post(boost::bind(io_function));
}

```

**Comment by 2underscores-vic** [comment]
asio::thread_pool ?

**Comment by sailfish009** [comment]
thank you!
i will give it a try.

**Comment by sailfish009** [comment]
it is ok, 
but i forgot to check boost lock free queue.
i think i should stay with boost library for a while.

**Comment by marekfoltyn** [comment]
@sailfish009, could you please provide code, how you use `asio::thread_pool` with `io_service`? I am not able to manage it, I tried `threadPool.use_service(ioService);`, but compilation fails on `error: no member named 'use_service' in 'asio::thread_pool'`, but the CLion clearly shows that the method is available...

**Comment by sailfish009** [comment]
@marekfoltyn , you asked too lately, i removed non-boost sample, please ask to  asio author.

BTW, most of boost:: can be replaced with asio:: namespace.

// boost::thread_group work_threads   // boost version
asio::detail::thread_group work_threads; // non-boost version

https://sourceforge.net/p/asio/mailman/message/3801222/
