### ISSUE TITLE
Could not connect to numeric port in Apple's NAT64 environment

### ISSUE THREAD

**Issue by zhuoqiang** [chriskohlhoff/asio#139]
Apple suggests to using `getaddrinfo()` to synthesize IPv6 address in Apple's NAT64 environment. 

However, Apple's `getaddrinfo()` is broken if numeric port is used as the service name. It always return port 0 in this case. So asio always failed to get the right endpoint for connection.

**Comment by chriskohlhoff** [comment]
Fixed on master in 595ff85c330d106798a56f4c0d79e733ad5ec7b1. Fixed on asio-1-10-branch in 2d33b821adad2e032ca66ce5fbac5afbc0d4d211.
