### ISSUE TITLE
QUESTION: Possibility to set priority for the handlers

### ISSUE THREAD

**Issue by KaanRF** [chriskohlhoff/asio#1420]
Hi, 

I have question regarding scheduling and priorities. 
In the single thread system is there any way to set some priorities for the completion handler ? For an example during we post we can give info to execute first and schedule maybe order the handler accordingly ? For the time critical jobs would be very useful such a feature.

**Comment by criatura2** [comment]
There are examples showing how to do this, try grepping for `priority` in asio's example dir.

**Comment by KaanRF** [comment]
Thank you @criatura2, found the related example.
