### ISSUE TITLE
Use of deprecated OSMemoryBarrier on latest MacOS

### ISSUE THREAD

**Issue by jeremyong** [chriskohlhoff/asio#144]
asio/asio/include/asio/detail/macos_fenced_block.hpp:51:5: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_thread_fence() from <atomic> instead [-Wdeprecated-declarations]
    OSMemoryBarrier();
    ^
/usr/include/libkern/OSAtomicDeprecated.h:749:9: note: 'OSMemoryBarrier' has been explicitly marked deprecated here
void    OSMemoryBarrier( void );

**Comment by jeremyong** [comment]
Actually seems like a number of things are deprecated and no longer working in latest MacOS (xcode 8.1 compiler)

**Comment by twn346** [comment]
There was an update to XCode recently, and using the header-only version that does not rely on Boost the only warning I got was this one about OSMemoryBarrier. 

Compiled with: -std=c++14 -Wall -Wextra -pedantic -g -stdlib=libc++

**Comment by chriskohlhoff** [comment]
I have applied a fix that addresses the warning when compiling for C++11 or later. No idea what we're supposed to do for C++03.

Fixed on master in ffc9dd443fc2ca1aece0bbda14f3c521ceeb7924. Fixed on asio-1-10-branch in 99c0f9239e61e215b21b226a3432e1440710df01.
