### ISSUE TITLE
Does asio support compile on qnx710 

### ISSUE THREAD

**Issue by Je2ry** [chriskohlhoff/asio#1460]
Hi,i have questions on compile asio on qnx710.
errors: 
/home/asio/asio/include/asio/detail/tss_ptr.hpp:29:3: error: #error Only Windows and POSIX are supported!
 # error Only Windows and POSIX are supported!
/home/asio/asio/include/asio/detail/signal_blocker.hpp:27:3: error: #error Only Windows and POSIX are supported!
# error Only Windows and POSIX are supported!
   ^~~~~
I add add_definitions(-DASIO_HAS_PTHREADS) in my CMakeLists.txt to solve the first problem. I wonder whether it is right.
Besides, how can i solve the second error. Does asion support compile on qnx710 and to build on qnx710,what should i do?

**Comment by Je2ry** [comment]
already done

**Comment by yuzu-ogura** [comment]
> already done

Excuse me, I got the same error when cross compile asio repository. Could you tell how do you solve this question?

**Comment by Je2ry** [comment]
Sorry, I did not notice the message. 

1. add this macro
```markdown
if (TARGET_CPU STREQUAL "QNX710")
    add_definitions(-DASIO_HAS_PTHREADS)
    set(LIBS c socket)
else()
    # set(LIBS pthread)
endif()
```
2. QNX deos not support  `SA_RESTART`, so  in socket_types.hpp refine related macro:
```c++
# if defined(__QNX__)
#  define ASIO_OS_DEF_SA_RESTART 0
# else
#  define ASIO_OS_DEF_SA_RESTART SA_RESTART
# endif
```

**Comment by Je2ry** [comment]
> > already done
> 
> Excuse me, I got the same error when cross compile asio repository. Could you tell how do you solve this question?


Sorry, I did not notice the message.

1.  add this macro
```markdown
if (TARGET_CPU STREQUAL "QNX710")
    add_definitions(-DASIO_HAS_PTHREADS)
    set(LIBS c socket)
else()
    # set(LIBS pthread)
endif()
```
2. QNX deos not support SA_RESTART, so in socket_types.hpp refine related macro:
```c++
# if defined(__QNX__)
#  define ASIO_OS_DEF_SA_RESTART 0
# else
#  define ASIO_OS_DEF_SA_RESTART SA_RESTART
# endif
```
