### ISSUE TITLE
socket_.async_read_some: less data than expected returned when callback invoked

### ISSUE THREAD

**Issue by paralleld** [chriskohlhoff/asio#154]
I meet a problem when using socket.async_read_some  in my application.  I use asio to build a proxy,  part of which converts a private protocol to redis protocol. Everything is OK with sending requests to remote redis server, but something went wrong when reading responses to these request from remote redis servers. 

The responses of all requests are supposed to be ":1\r\n".But when cpu usage of the proxy comes to 90%  , (meanwhile remote redis servers process ~7200 requests per second, and the size of each request is around ~2k bytes) the invoked callback of socket_.async_read_some (**socket_** connects to remote redis, and **aysnc_read_some** read responses)  returns "1\r\n" of size 3.  This invalid response does not occur very often , ~10 in 10m redis requests.   I use tcpdump to capture packets, but never see packet of size 3.  Actually , all packets of redis responses are of size 4. In other words, with tcpdump, I saw no reponse of size 4, but async_read_some returns an invalid response of size 3. 

I don't know why this happened.  I am wondering if it's related to the read buffer mechanism of asio, or it's a bug.

**Comment by arun11299** [comment]
@paralleld 
Was it your implementation issue which is why closed this bug ?

**Comment by paralleld** [comment]
Implementation issue.

**Comment by paralleld** [comment]
@arun11299  Implementation issue
