### ISSUE TITLE
Where is the Boost love?

### ISSUE THREAD

**Issue by vinniefalco** [chriskohlhoff/asio#155]
I see a lot of new development in stand-alone asio, for example that `const_buffer` meets the requirements of **ConstBufferSequence**. But why aren't these changes migrating into Boost?

**Comment by nuuman** [comment]
Don't expect an answer. Most issues go unanswered. And this thing is going in C++ 17? Christ...

**Comment by vinniefalco** [comment]
> And this thing is going into C++ 17

C++23 to be accurate. And this will help considerably, as the world will no longer be depending on one mostly-absent person for all of C++ networking.
