### ISSUE TITLE
To fix the 182 errors in asio.hpp I need to set up asio right? 

### ISSUE THREAD

**Issue by NahilTheDolfin** [chriskohlhoff/asio#1564]

**Comment by klemens-morgenstern** [comment]
Now you are just spamming.

**Comment by NahilTheDolfin** [comment]
> Now you are just spamming.

i just need a yes or no response, im working on a very important project, please. thank you in advance.

**Comment by klemens-morgenstern** [comment]
You are not owed any response. Please close this issue and provide an actual example project as described in #1553. 
You did not provide any details about your project, such as how you're compiling, which compiler version or which language standard you are using.
