### ISSUE TITLE
Missing headers in the tarball releases?

### ISSUE THREAD

**Issue by zorun** [chriskohlhoff/asio#157]
Hi,

A project I try to build (restbed) uses this include: `<asio/io_service_strand.hpp>`.  The project fails to compile on my system with asio 1.10.8, because this header does not exist.

However, when I look in the asio git repository, this header is present.  But it is missing from the release tarballs.

Is it expected?  Maybe this header is deprecated?

**Comment by MarcelRaad** [comment]
io_service_strand.hpp is in asio 1.11, but not in 1.10.

**Comment by zorun** [comment]
Ah, sorry, I didn't see that the master branch is following 1.11, not 1.10.
