### ISSUE TITLE
Support port unification for SSL/raw tcp

### ISSUE THREAD

**Issue by nuuman** [chriskohlhoff/asio#159]
An increasing number of server supports raw TCP traffic and SSL traffic on the same port (especially prevalent in the Java space)

This means, detect SSL hello packet, then move to SSL for that client.

Would this be hard to implement in ASIO? I suppose you need to put the hello packet back on the "read queue" so that the ssl api starts with the hello packet.

Ideas?

**Comment by vinniefalco** [comment]
This is already possible, use this overload of `ssl::stream::async_handshake`:
http://www.boost.org/doc/libs/1_62_0/doc/html/boost_asio/reference/ssl__stream/async_handshake/overload2.html

Usage example:
https://github.com/ripple/rippled/blob/develop/src/ripple/server/impl/Door.h#L118

**Comment by nuuman** [comment]
@vinniefalco Thanks a lot!

**Comment by vinniefalco** [comment]
Yep!! See:
https://forum.ripple.com/viewtopic.php?t=8313&p=57967

**Comment by vinniefalco** [comment]
@nuuman This all also works in Beast: https://github.com/vinniefalco/Beast

**Comment by nuuman** [comment]
@vinniefalco This is great news. Thank you!
