### ISSUE TITLE
performance boost: 700% faster

### ISSUE THREAD

**Issue by zhaoguojie2010** [chriskohlhoff/asio#164]
Hello guys,
   lately I've been doing some modification on asio. My fork: [https://github.com/zhaoguojie2010/asio](url)

**The idea is:**  
    _io_context.run() will spawn multiple io_contexts(no larger than the number of server's logical cores), each io_context has one scheduler and one task(aka reactor/iocp) runing in one thread. When the acceptor receives new connections, it simply distributes these connections to the spawned io_contexts. Each scheduler has its own op_queue, so no lock is needed._ 

To enable this feather, just call `io_context.set_spawn(true);` before `io_context.run();`

**Test platform:**
OS: SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz x4
RAM: 128GB

**Test case:**
 client start 200 connections, each connection send "hello world" to server and server echos.
 original version: start 40 threads runing `io_context.run();`
 my version: spawn 40 io_context.

**Result:**
1. server and client on the same machine
original version:  170,000 qps
my version:  1,300,000 qps

2. server and client on different machines
original version: 170,000 qps
my version: 470,000 qps

By the way, this feature only works on linux and mac os currently.

This feature is still under development, any suggestions will be welcomed.  
@chriskohlhoff, if you like this feature, i can issue a pull request.

Cheers,
Jesse

**Comment by arun11299** [comment]
Hello, Jesse
How different is this from creating your own pool of `io_service` running on a pool of thread (could be 1:1 mapping or 1 : N mapping between io_service and thread) ? An `io_service` can be assigned to an `io_object` using a simple roun robin algorithm or some other algorithm.

**Comment by zhaoguojie2010** [comment]
As far as i know, even you create a thread pool, there is only one scheduler and its op_queue is actually a global queue shared by all the threads and its guarded by a mutex, which prevents us from fully using the cpu resource.

**Comment by arun11299** [comment]
@zhaoguojie2010 
I am not talking about creating a thread pool and calling `io_service::run` on a single instance of `io_service`, but creating multiple instances of `io_service` which means multiple scheduler instance hence independent operation queues. 
For eg: http://www.boost.org/doc/libs/1_62_0/doc/html/boost_asio/example/cpp03/http/server2/io_service_pool.hpp

**Comment by zhaoguojie2010** [comment]
@arun11299 
I just read the example code, looks they are same. I just move the whole procedure inside the io_context and its impl, LOL.
Wish I had read this code earlier.
Thanks.

**Comment by arun11299** [comment]
No problem. Nevertheless you must have learned quite a bit of internal working of asio anyways :)
