### ISSUE TITLE
create_promise uses C++03 allocator rebinding

### ISSUE THREAD

**Issue by jwakely** [chriskohlhoff/asio#168]
```
    p_ = std::allocate_shared<std::promise<T>>(
        typename Allocator::template rebind<char>::other(a),
        std::allocator_arg,
        typename Allocator::template rebind<char>::other(a));
```

This assumes that the allocator has a nested `rebind` template, which is true for `std::allocator` but not for C++11 allocators in general. It should use `allocator_traits<Allocator>::rebind_alloc<char>`.

(This is partly my fault, for breaking the use of `allocator<void>::construct` so that rebinding is needed in the first place, which is now fixed in GCC svn, see https://gcc.gnu.org/PR78052 - sorry!)

**Comment by chriskohlhoff** [comment]
Fixed on master in 647d2dc9564fa02f2f3c171eaf6b941cb8a0e548. Fixed on asio-1-10-branch in e2361876ed577d5891d67115fcf7aff78a0b3a57.
