### ISSUE TITLE
Error building with GCC4.9, Solaris environment.

### ISSUE THREAD

**Issue by ben-crowhurst** [chriskohlhoff/asio#172]
```
/usr/bin/c++    -isystem /DevStudioProjects/restbed/dependency/asio/asio/include -isystem /DevStudioProjects/restbed/dependency/kashmir -I/DevStudioProjects/restbed/source -Wno-non-virtual-dtor -std=c++11 -O2 -Wall -Wextra -Weffc++ -pedantic -Wno-unknown-pragmas -pthread -DASIO_STANDALONE=YES -o CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o -c /DevStudioProjects/restbed/source/corvusoft/restbed/http.cpp
```
> /DevStudioProjects/restbed/dependency/asio/asio/include/asio/detail/impl/dev_poll_reactor.ipp:70:54: error: variable or field 'notify_fork' declared void
>  void dev_poll_reactor::notify_fork(asio::io_context::fork_event fork_ev)
>                                                       ^
> /DevStudioProjects/restbed/dependency/asio/asio/include/asio/detail/impl/dev_poll_reactor.ipp:70:36: error: incomplete type 'asio::io_context' used in nested name specifier
>  void dev_poll_reactor::notify_fork(asio::io_context::fork_event fork_ev)

**Comment by chriskohlhoff** [comment]
I don't currently have access to solaris, but I fixed the compile errors as best I could in cbf6876530a458ea26702f09406c8cef231cd49a.
