### ISSUE TITLE
Can't write stateful composed operations solely with associated allocators

### ISSUE THREAD

**Issue by vinniefalco** [chriskohlhoff/asio#174]
I've been writing quite a few composed operations in my HTTP/WebSocket library Beast (https://github.com/vinniefalco/Beast). They look like this:
```
template<class Handler>
struct composed_op
{
  struct state
  {
    Handler handler;
    ...
    template<class DeducedHandler, ...>
    state(DeducedHandler&& h, ...)
      : handler(std::forward<DeducedHandler>(h))
    {
      ...
    }
  };

  std::shared_ptr<state> s_;

  void operator()(...);
};
```

The constructor and destructor of `state` can use the contained handler to allocate temporary memory using the associated allocator and deallocator (`asio_handler_allocate` and `asio_handler_deallocate`).

Unfortunately this breaks the "deallocate before invocation" guarantee (http://www.boost.org/doc/libs/1_62_0/doc/html/boost_asio/overview/core/allocation.html):
_"The implementation guarantees that the deallocation will occur before the associated handler is invoked..."_

A fix for this is to store `std::shared_ptr<boost::optional<state>>` instead. This way `state` can be destructed before invoking the final handler (the handler would be moved to the stack first so it could be invoked after `state` is destroyed).

This is better, but not quite perfect. We'd like the storage for the `shared_ptr` to also be allocated using the associated allocator. One way to do that is to write a custom allocator containing the handler. Such an allocator might look like this: 
https://github.com/vinniefalco/Beast/blob/master/include/beast/core/handler_alloc.hpp#L22

Now we can call `std::allocate_shared` with an instance of `handler_alloc` as the allocator.

Sadly, this does not work, because it breaks the deallocation-before-invocation guarantee. The Asio implementation loves to make copies of handlers. It is very likely that just before a composed operation would invoke the final handler, the `use_count` on the `shared_ptr` holding the composed operation state will be above 1. We need to destroy the owned object in the `shared_ptr` but there's no way to do it.

I've tried some other approaches, such as writing my own smart pointer container that is threaded on a linked list. But they suffer from multi-threading issues. You can see that work here:
https://github.com/vinniefalco/Beast/issues/215

I have concluded the following:

It is not generally possible to write a non-trivial, stateful composed operation which relies only on the allocator associated with the final handler. Either you need to allocate some memory from the heap (bypassing the associated allocator) or you need to depend on a global mutex.

Asio's own composed operations (such as https://github.com/chriskohlhoff/asio/blob/14db6371b338339383aacaed29b0fa352259645a/asio/include/asio/impl/read.hpp#L226) avoid storing state information in dynamically allocated structures. Instead, they rely on the implementation to simply make copies. Asio composed operations are easy to copy. And moves are used where possible, for example line 275 here:
https://github.com/chriskohlhoff/asio/blob/14db6371b338339383aacaed29b0fa352259645a/asio/include/asio/impl/read.hpp#L275

I would like to be wrong - is there a way to allocate state for a composed operation using the allocator associated with the handler, in a way that preserves the deallocate-before-invocation guarantee, and that doesn't also require a traditional heap allocation or global mutex?

**Comment by vinniefalco** [comment]
n4625 13.2.7.3 states that completion handlers only need to be **Destructible** and **MoveConstructible**. I believe that will solve the problem described here.
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/n4625.pdf

**Comment by mabrarov** [comment]
As a workaround: an implementation (like `socket`) of Asio service IO object often has (business logic) limits on number of outstating operations of the same type - it's hard for Asio socket to have multiple asynchronous write operations to be pending / in progress at the same time - not from implementation side but from business logic side (what if one `async_write_some` completed? it doesn't mean that another `asyn_write_some` can start sending data because the previous one still didn't send all the data it expected to send). We could make these limits official (i.e. document and check them) and store shared state as part of IO object (Asio's `socket` or Beast's `beast::websocket::stream`). It could be still not usable for message (and not stream) oriented interface though.

**Comment by vinniefalco** [comment]
Just an update on this problem, I believe I have a solution which is "as good as it gets" for Boost.Asio.

For composed operations that have a non-trivial state (i.e. the completion handler contains objects which are not trivial to copy) I have designed a helper class called `handler_ptr`. It requires only a small allocation using `new` to hold an atomic integer and the final completion handler. The state for the composed operation is allocated using the allocator associated with the completion handler. It provides an `invoke` function to perform the upcall. Before the upcall it destroys the memory for the composed operation state, thus fulfilling the "deallocation before invocation" guarantee.

Since Asio requires handlers to be **CopyConstructible**, my implementation is similar to `shared_ptr` in that it maintains a reference count. and makes copies of the handler. However, this implementation can be improved in **[Networking-TS]** which only requires handlers to be **MoveConstructible**. A version of `beast::handler_ptr` for the new networking specification can do away with the reference count, and move the handler instead of copying it.

`handler_ptr`:
https://github.com/vinniefalco/Beast/blob/master/include/beast/core/handler_ptr.hpp

Documentation
http://vinniefalco.github.io/beast/beast/ref/handler_ptr.html

**Comment by mabrarov** [comment]
Looks like [`ma::detail::handler_ptr`](https://github.com/mabrarov/asio_samples/blob/develop/libs/ma_handler_ptr/include/ma/detail/handler_ptr.hpp) (combined with `ma::detail::raw_handler_ptr`, both are slightly modified copy of similar internal classes from old version of Asio) but with reference counter. Just want to double check that I understand `beast::handler_ptr` correctly.

**Comment by vinniefalco** [comment]
Wow that's...quite the coincidence! I have never seen that code before, but there are definite similarities. I'm not sure that they address the same use-case though. Here's a simple example of how `beast::handler_ptr` is used:
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/teardown.ipp#L22

In this code, `teardown_tcp_op` is a composed operation, templated on the final `Handler` type. The `data` struct holds the state for the operation. Its non-trivial to copy (there's a 2 kilobyte buffer). The `handler_ptr` is used to manage the memory allocated through the associated allocator (e.g. `asio_handler_allocate`). `handler_ptr` is also cheap to copy so when the composed operation is copied, the state goes with it.

To provide the "deallocation before invocation" guarantee, the implementation of `teardown_tcp_op` calls `handler_ptr::invoke`. This deallocates the state before making the upcall:
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/teardown.ipp#L119

Looking over `ma::detail::handler_ptr` and `ma::ma_handler_storage` I see significant differences:
* There's no reference counting in `ma::detail::handler_ptr`
* `ma_handler_storage` installs a service (Beast does not)

I'm not entirely sure how `ma::detail::handler_ptr` and `ma::ma_handler_storage` are used but it seems to address a different use case. I could be wrong - are these classes intended to facilitate the implementation of composed operations that use the associated allocator to manage state?

**Comment by mabrarov** [comment]
> `ma_handler_storage` installs a service (Beast does not)

It's not related to `ma::detail::handler_ptr`. I just use it there.

> There's no reference counting in `ma::detail::handler_ptr`

And now I'm looking for the way to add one more version of `handler_ptr` with reference counter - just to check if this is possible.

> are these classes intended to facilitate the implementation of composed operations that use the associated allocator to manage state?

It seems so - these classes are used to store (in exception-safe way) some data (including user defined handler for sure) which will be placed in a memory block allocated with usage of "allocation strategy" (`asio_hadler_[de]allocate`) provided by that user defined handler. It seems that `ma::detail::handler_ptr` can be transformed to support the same use case as `beast::handler_ptr` does... I'm not sure about `beast::handler_ptr` - it seems that it still [uses default memory allocator (`new` operator)](https://github.com/vinniefalco/Beast/blob/master/include/beast/core/impl/handler_ptr.ipp#L91) while `ma::detail::handler_ptr` is free of that. This is why I wanted to attract your attention to `ma::detail::handler_ptr` - probably you'll have more free time to check it (if it is possible to use the same trick in Beast) comparing to me :)

**Comment by mabrarov** [comment]
... actually, there won't be "transformation" of `ma::detail::handler_ptr` but probably just one more class which will use `ma::detail::handler_ptr` while reference counter will be located at `Value` type used in `ma::detail::handler_alloc_traits`.

**Comment by vinniefalco** [comment]
You're right that `beast::handler_ptr` uses the default memory allocator. That is the one problem with the design. However, in Networking-TS this is easily solved as I described earlier. I could not come up with any technique for eliminating this allocation in regular Boost.Asio. Specifically, as long as handlers must be **CopyConstructible** there doesn't seem to be a way to avoid it.

In `ma::detail::handler_alloc_traits`, the `AllocContext` is the handler, and `Value` is a type describing the composed operation state? In Beast these are `Handler` and `T`? Its not clear to me how `ma::detail::handler_ptr` could be used to write a composed operation. Could you perhaps show me how `beast::websocket::detail::teardown_tcp_op` might be adapted to instead use it?

**Comment by vinniefalco** [comment]
It looks like `raw_handler_ptr` and `handler_ptr` were detail classes used in the implementation of Asio's reactor pattern. In the most recent commits, they have been removed and instead replaced with this implementation macro:
https://github.com/chriskohlhoff/asio/blob/asio-1-10-branch/asio/include/asio/detail/handler_alloc_helpers.hpp#L54

Since `ma::detail::handler_ptr` is based on these obsolete classes that were implementation specific, I don't think they solve the general problem I describe in this issue. Especially because they are not **CopyConstructible**, and cannot be used as members of a **CompletionHandler**.

**Comment by mabrarov** [comment]
1. I was wrong and there is no way to make `ma::detail::handler_ptr` reference-countable without using a dedicated (operator `new` in `beast::handler_ptr`) block of memory for storing of reference counter because of reference counter has different life scope (while any copy of this handler exists) comparing to the block of memory allocated through "allocation strategy" of user defined handler (through `asio_hadler_[de]allocate`) - till user defined handler is called or the last copy of this handler was destroyed - what happens first. So `beast::handler_ptr` does exactly what described above - it uses some dedicated block of memory (allocated with operator `new`) shared across all copies of handler and used for storing of reference counter.
1. > they have been removed and instead replaced with this implementation macro

    I know but personally prefer classes (could be templates) over macro :)
1. While `beast::handler_ptr` seems to solve initial task with some tradeoff (like using of global memory allocator) I'm still looking at `beast::websocket::stream` - does it support (is it possible to support that when underlying layer is stream-oriented?) multiple asynchronous read operations (or multiple asynchronous write operations) pending at the same time? If not then could we add a check for that into `beast::websocket::stream` and store in `beast::websocket::stream` some memory block (with usage of `shared_ptr` for example) which will be shared among all (composed operation) handlers used for asynchronous read operations (or write operations - one dedicated block per each type of asynchronous operations)? This way we could allocate (with global allocator) this block once - when we instantiate `beast::websocket::stream` - and not for each `beast::websocket::stream::async_read` call. Not sure it's the best idea but for me it seems to have smaller tradeoff comparing to `beast::handler_ptr`.

**Comment by vinniefalco** [comment]
>I'm still looking at beast::websocket::stream - does it support...multiple asynchronous read operations (or multiple asynchronous write operations) pending at the same time?

No. From http://vinniefalco.github.io/beast/beast/ref/websocket__stream/async_read.html
_"The program must ensure that the stream performs no other reads until this operation completes."_

> If not then could we add a check for that into beast::websocket::stream and store in beast::websocket::stream some memory block (with usage of shared_ptr for example) which will be shared among all (composed operation) handlers used for asynchronous read operations (or write operations - one dedicated block per each type of asynchronous operations)? This way we could allocate (with global allocator) this block once - when we instantiate beast::websocket::stream - and not for each beast::websocket::stream::async_read call. Not sure it's the best idea but for me it seems to have smaller tradeoff comparing to beast::handler_ptr.

This is a great idea but unfortunately, won't work. There's only one physical read allowed at a time but with your suggestion, you cannot created composed operations. For example, the implementation of the composed operation which writes an entire websocket message repeatedly calls into `async_write_frame`:
https://github.com/vinniefalco/Beast/blob/master/include/beast/websocket/impl/write.ipp#L843

There are two instances of `handler_ptr` in existence at the same time, which wouldn't work with your scheme. Nice idea though.

**Comment by vinniefalco** [comment]
Networking-TS relaxation of handler requirements to be only **MoveConstructible** allows the implementation of Beast's `handler_ptr` to achieve the goals described in the original issue. Therefore, this will be automatically resolved, and I will close this issue.
