### ISSUE TITLE
Weird issue with Visual Studio 2015.3: "no instance of overloaded function asio::basic_socket_acceptor"

### ISSUE THREAD

**Issue by rhulha** [chriskohlhoff/asio#182]
The code compiles fine using the IDE, but the IDE editor shows the follwoing notification:

![Warning](https://i.imgur.com/qsHL3AI.png)

I get similar notifications when using the async_tcp_echo_server.cpp

When using asio with boost I do not get these markings in the IDE.

Any ideas on how to make Visual Studio happy with just standalone asio ?

**Comment by chriskohlhoff** [comment]
I believe this is fixed by a8f9b3cedce25cefb88cca8195f538f7e97b93f4 (master) and 5c7faf2c97a84f865dcc77923242f8d6bbc58088 (asio-1-10-branch).
