### ISSUE TITLE
Does the socket will be closed automatically ?

### ISSUE THREAD

**Issue by pengweichu** [chriskohlhoff/asio#185]
Hi, if I bind a UDP socket in ASIO, and post an asyn recv_from request on io_service, then that application keeps running 1-2 months or more days, during that days, the socket doesn't received any data,  then the ASIO will close that socket or cancel that recv_from request automatically ?

Thanks

**Comment by chriskohlhoff** [comment]
The socket should remain open. If you want it to close, use a timer.

If I have misunderstood your comment and it is closing automatically when you don't want it to, please reopen this with some source code to reproduce the issue.
