### ISSUE TITLE
async_write_some never calls back on connection refused on windows

### ISSUE THREAD

**Issue by blastrock** [chriskohlhoff/asio#189]
Hi,

I have an issue with async_write_some never calling me back when I call it after a non-blocking connect on a closed port on windows. I managed to write a minimal example:

```cpp
#include <boost/asio.hpp>

#include <iostream>

int main()
{
  boost::asio::io_service io;

  boost::asio::ip::tcp::socket sock(io);
  sock.open(boost::asio::ip::tcp::v4());
  auto const fd = sock.native_handle();

  int ret;

  // make the socket non-blocking
  unsigned long on = 1;
  ret = ioctlsocket(fd, FIONBIO, &on);
  if (ret != NO_ERROR)
    throw std::runtime_error("ioctl");

  // connect to 127.0.0.1:1 which should be a closed port
  struct sockaddr_in serv_addr;
  serv_addr.sin_family = AF_INET;
  serv_addr.sin_port = htons(1);
  ret = inet_pton(AF_INET, "127.0.0.1", &serv_addr.sin_addr);
  if (ret <= 0)
    throw std::runtime_error("pton error");

  // do the connect and ignore "connection in progress" error
  ret = connect(fd, (struct sockaddr*)&serv_addr, sizeof(serv_addr));
  if (ret < 0)
  {
    auto const err = GetLastError();
    if (err != 10035) // EWOULDBLOCK-like
    {
      std::cout << err << std::endl;
      throw std::runtime_error("connect error");
    }
  }

  bool finished = false;
#if 1 // this doesn't work
  sock.async_write_some(
#else // this works
  boost::asio::async_write(sock,
#endif
      boost::asio::null_buffers(),
      [&](boost::system::error_code ec, std::size_t s)
      {
        std::cout << ec << std::endl;
        finished = true;
      });

  while (!finished)
    io.run_one();

  std::cout << "FINISHED" << std::endl;
}
```

This code never terminates for me. Replacing the async_write_some with asio::async_write fixes the issue and the callback is called with no error (which may be a bug too...).

I saw the bug in boost 1.61 and 1.63, but I tested this snippet only on 1.61.
I am using windows 8.1 and visual 2015 update 2.
A similar code without the windows-specific stuff works on linux and mac os.

**Comment by chriskohlhoff** [comment]
When handling EINPROGRESS connects on Windows, you have to check for an "except" condition in addition to "writeable". The `async_write_some` function is not enough for this.

Assuming you have a really good reason for not using `async_connect`, you'll have to use the `async_wait` function on master branch for this.

If you want to be portable, just use `async_connect`.

**Comment by blastrock** [comment]
Thanks for you answer.

I am not using async_connect because I am using boost asio as a backend to curl. Curl allows us to specify asynchronous read and write functions, but not connect. The connect is done by curl in a manner similar to my example.

Since asio::async_write does work (at least it calls me back), does it mean that it checks for that "except" condition? Do I have the guarantee that asio::async_write will always call me back when using it without async_connect?
