### ISSUE TITLE
All the images are missing on boost.org

### ISSUE THREAD

**Issue by akimd** [chriskohlhoff/asio#191]
None of the images show on this page:

http://www.boost.org/doc/libs/1_63_0/doc/html/boost_asio.html

**Comment by vinniefalco** [comment]
1_63_0 built the docs incorrectly. I believe it is fixed in 1_64_0. This issue should be closed.

**Comment by akimd** [comment]
It's hard to say if it's fixed everywhere, since now instead of a single page, it's a web of pages.  But I agree that at least looking at the first pages, they appear to be correct.
