### ISSUE TITLE
build  ERROR

### ISSUE THREAD

**Issue by MrChang0** [chriskohlhoff/asio#195]
## LOG
depbase=`echo http/server2/io_context_pool.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"asio\" -DPACKAGE_TARNAME=\"asio\" -DPACKAGE_VERSION=\"1.11.0\" -DPACKAGE_STRING=\"asio\ 1.11.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"asio\" -DVERSION=\"1.11.0\" -D_REENTRANT=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I.    -I./../../../include -g -O2 -pthread -ftemplate-depth-256 -lboost_system -MT http/server2/io_context_pool.o -MD -MP -MF $depbase.Tpo -c -o http/server2/io_context_pool.o http/server2/io_context_pool.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from ./../../../include/asio/detail/work_dispatcher.hpp:21:0,
                 from ./../../../include/asio/impl/post.hpp:21,
                 from ./../../../include/asio/post.hpp:105,
                 from ./../../../include/asio/basic_socket.hpp:25,
                 from ./../../../include/asio/basic_datagram_socket.hpp:20,
                 from ./../../../include/asio.hpp:21,
                 from http/server2/server.hpp:14,
                 from http/server2/io_context_pool.cpp:11:
/usr/include/c++/4.8.2/bits/vector.tcc: In instantiation of ‘void std::vector<_Tp, _Alloc>::_M_insert_aux(std::vector<_Tp, _Alloc>::iterator, const _Tp&) [with _Tp = asio::executor_work_guard<asio::io_context::executor_type>; _Alloc = std::allocator<asio::executor_work_guard<asio::io_context::executor_type> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<asio::executor_work_guard<asio::io_context::executor_type>*, std::vector<asio::executor_work_guard<asio::io_context::executor_type> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = asio::executor_work_guard<asio::io_context::executor_type>*]’:
/usr/include/c++/4.8.2/bits/stl_vector.h:913:28:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = asio::executor_work_guard<asio::io_context::executor_type>; _Alloc = std::allocator<asio::executor_work_guard<asio::io_context::executor_type> >; std::vector<_Tp, _Alloc>::value_type = asio::executor_work_guard<asio::io_context::executor_type>]’
http/server2/io_context_pool.cpp:31:55:   required from here
./../../../include/asio/executor_work_guard.hpp:105:24: error: ‘asio::executor_work_guard<Executor>& asio::executor_work_guard<Executor>::operator=(const asio::executor_work_guard<Executor>&) [with Executor = asio::io_context::executor_type]’ is private
   executor_work_guard& operator=(const executor_work_guard&);
                        ^
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from ./../../../include/asio/detail/impl/service_registry.ipp:19,
                 from ./../../../include/asio/detail/service_registry.hpp:161,
                 from ./../../../include/asio/impl/execution_context.hpp:20,
                 from ./../../../include/asio/execution_context.hpp:406,
                 from ./../../../include/asio/detail/scheduler.hpp:21,
                 from ./../../../include/asio/system_executor.hpp:19,
                 from ./../../../include/asio/associated_executor.hpp:21,
                 from ./../../../include/asio.hpp:19,
                 from http/server2/server.hpp:14,
                 from http/server2/io_context_pool.cpp:11:
/usr/include/c++/4.8.2/bits/vector.tcc:335:16: error: within this context
    *__position = __x_copy;
                ^
In file included from ./../../../include/asio/detail/work_dispatcher.hpp:21:0,
                 from ./../../../include/asio/impl/post.hpp:21,
                 from ./../../../include/asio/post.hpp:105,
                 from ./../../../include/asio/basic_socket.hpp:25,
                 from ./../../../include/asio/basic_datagram_socket.hpp:20,
                 from ./../../../include/asio.hpp:21,
                 from http/server2/server.hpp:14,
                 from http/server2/io_context_pool.cpp:11:
/usr/include/c++/4.8.2/bits/stl_algobase.h: In instantiation of ‘static _BI2 std::__copy_move_backward<false, false, std::random_access_iterator_tag>::__copy_move_b(_BI1, _BI1, _BI2) [with _BI1 = asio::executor_work_guard<asio::io_context::executor_type>*; _BI2 = asio::executor_work_guard<asio::io_context::executor_type>*]’:
/usr/include/c++/4.8.2/bits/stl_algobase.h:587:18:   required from ‘_BI2 std::__copy_move_backward_a(_BI1, _BI1, _BI2) [with bool _IsMove = false; _BI1 = asio::executor_work_guard<asio::io_context::executor_type>*; _BI2 = asio::executor_work_guard<asio::io_context::executor_type>*]’
/usr/include/c++/4.8.2/bits/stl_algobase.h:596:33:   required from ‘_BI2 std::__copy_move_backward_a2(_BI1, _BI1, _BI2) [with bool _IsMove = false; _BI1 = asio::executor_work_guard<asio::io_context::executor_type>*; _BI2 = asio::executor_work_guard<asio::io_context::executor_type>*]’
/usr/include/c++/4.8.2/bits/stl_algobase.h:631:17:   required from ‘_BI2 std::copy_backward(_BI1, _BI1, _BI2) [with _BI1 = asio::executor_work_guard<asio::io_context::executor_type>*; _BI2 = asio::executor_work_guard<asio::io_context::executor_type>*]’
/usr/include/c++/4.8.2/bits/vector.tcc:331:4:   required from ‘void std::vector<_Tp, _Alloc>::_M_insert_aux(std::vector<_Tp, _Alloc>::iterator, const _Tp&) [with _Tp = asio::executor_work_guard<asio::io_context::executor_type>; _Alloc = std::allocator<asio::executor_work_guard<asio::io_context::executor_type> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<asio::executor_work_guard<asio::io_context::executor_type>*, std::vector<asio::executor_work_guard<asio::io_context::executor_type> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = asio::executor_work_guard<asio::io_context::executor_type>*]’
/usr/include/c++/4.8.2/bits/stl_vector.h:913:28:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = asio::executor_work_guard<asio::io_context::executor_type>; _Alloc = std::allocator<asio::executor_work_guard<asio::io_context::executor_type> >; std::vector<_Tp, _Alloc>::value_type = asio::executor_work_guard<asio::io_context::executor_type>]’
http/server2/io_context_pool.cpp:31:55:   required from here
./../../../include/asio/executor_work_guard.hpp:105:24: error: ‘asio::executor_work_guard<Executor>& asio::executor_work_guard<Executor>::operator=(const asio::executor_work_guard<Executor>&) [with Executor = asio::io_context::executor_type]’ is private
   executor_work_guard& operator=(const executor_work_guard&);
                        ^
In file included from /usr/include/c++/4.8.2/memory:62:0,
                 from ./../../../include/asio/associated_allocator.hpp:19,
                 from ./../../../include/asio.hpp:18,
                 from http/server2/server.hpp:14,
                 from http/server2/io_context_pool.cpp:11:
/usr/include/c++/4.8.2/bits/stl_algobase.h:537:18: error: within this context
      *--__result = *--__last;
## Platform
CentOS Linux release 7.3.1611 (Core)
## Asio Version
git clone from master
## boost version
boost 1.63.0
## gcc -v
ing built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

**Comment by abilbaotm** [comment]
I have the same error. Any updates?

**Comment by MrChang0** [comment]
I can build successfully in ubuntu17.04 by gcc6.3.0, you could try again.

**Comment by chriskohlhoff** [comment]
Fixed in 246f387e74f91de4b8e67011fe0ad6b1c32822d6.
