### ISSUE TITLE
how can i use socket::async_read_some api without boost?

### ISSUE THREAD

**Issue by yandaren** [chriskohlhoff/asio#198]
how can i use socket::async_read_some api without boost?

**Comment by arun11299** [comment]
If you are using C++11 you can pretty much use all the APIs without boost.

**Comment by yandaren** [comment]
in fact, I am using c++11, i use the api asio::async_read like this:
`        asio::async_read(socket_, asio::buffer(dst->data(), dst->max_capacity()),
                         strand_.wrap(std::bind(&tcp_channel::async_receive_handler,
                                               shared_from_this(),
                                               dst,
                                               std::placeholders::_1,
                                               std::placeholders::_2)));`
but it seems that the receive handler will not fired util the received bytes reach the dst->max_capacity(), but  what i want is that if any byte received from the socket, trigger the receive handler, how can i get this effect by using c++11 ?

**Comment by yandaren** [comment]
i find that this asio lib has not broken out of its dependence on boost completely
