### ISSUE TITLE
yield and fork interfere with their counterpart in <thread>

### ISSUE THREAD

**Issue by mehdioa** [chriskohlhoff/asio#201]
OS: ArchLinux
GCC

---------------------
#include <asio/yield.hpp>
#include < thread>

int main(int, char* [])
{
    return 0;
}
-----------------------

g++ -c -pipe -std=c++11 -g -std=gnu++11 -Wall -W -fPIC -DQT_QML_DEBUG -I../../../../test3 -I. -I/usr/lib/qt/mkspecs/linux-g++ -o main.o ../../../../test3/main.cpp
In file included from /usr/include/asio/yield.hpp:11:0,
                 from ../../../../test3/main.cpp:1:
/usr/include/c++/6.3.1/thread:298:5: error: expected unqualified-id before ‘for’
     yield() noexcept
     ^
/usr/include/c++/6.3.1/thread:298:5: error: expected unqualified-id before ‘)’ token
     yield() noexcept
     ^
/usr/include/c++/6.3.1/thread:298:5: error: expected unqualified-id before ‘else’
     yield() noexcept
     ^
/usr/include/c++/6.3.1/thread:298:5: error: expected unqualified-id before ‘)’ token
     yield() noexcept
     ^
/usr/include/c++/6.3.1/thread:298:5: error: expected unqualified-id before ‘else’
     yield() noexcept
     ^
/usr/include/c++/6.3.1/thread:298:5: error: expected unqualified-id before ‘)’ token
     yield() noexcept
     ^
/usr/include/c++/6.3.1/thread:298:5: error: expected unqualified-id before ‘else’
     yield() noexcept

**Comment by 2underscores-vic** [comment]
What is counterpart of `fork` in `<thread>`?

**Comment by 2underscores-vic** [comment]
Use `#include <asio/coroutine.hpp>` instead of `#include <asio/yield.hpp>` and `ASIO_CORO_YIELD` instead of `yield`

**Comment by mehdioa** [comment]
Using <asio/coroutine.hpp> solved the problem.

By fork counterpart I meant this: I tried to rename "yield" in "yield.hpp" to "asio_yield". Then another error occurs related to a "fork" function in the thread library.

**Comment by chriskohlhoff** [comment]
Include the pair of header files (`asio/yield.hpp`, `asio/unyield.hpp`) for the [pseudo-keywords](http://think-async.com/Asio/asio-1.10.6/doc/asio/reference/coroutine.html#asio.reference.coroutine.pseudo_keywords) around your coroutine only, as shown in the [HTTP server 4 example](http://think-async.com/Asio/asio-1.10.6/src/examples/cpp03/http/server4/server.cpp).
