### ISSUE TITLE
asio::async_write() with 1 million gather buffers is very slow on Windows and POSIX

### ISSUE THREAD

**Issue by ned14** [chriskohlhoff/asio#203]
I recently had a client where we did a gather write of 1 million dispersed 128 byte buffers.

It works (despite what other issue #194 says) but good god is it unbelievably slow. It would appear ASIO is calling malloc and free per buffer, and running IOCP per buffer sent too :(

I replaced asio::async_write() which this code:

```
        std::shared_ptr<std::vector<WSABUF>> reply = std::make_shared<std::vector<WSABUF>>();
        reply->reserve(_cl.size());
        for(auto &i : _cl)
        {
          // Note the fact we are gathering from the original, single copy storing the instrument
          // in file backed memory so it can be DMA locked
          // We do NOT make copies!
          reply->push_back(WSABUF{sizeof(instrument), (CHAR *) &i});
        }
        asio::windows::overlapped_ptr ol(_service, [this, reply](const asio::error_code &ec, size_t bytes_transferred) {
          (void) reply;
          write_handler(ec, bytes_transferred);
        });
        DWORD sent = 0;
        BOOL ok = WSASend(_socket.native_handle(), reply->data(), (DWORD) reply->size(), &sent, 0, ol.get(), nullptr);
        DWORD last_error = GetLastError();
        if(!ok && last_error != ERROR_IO_PENDING)
        {
          asio::error_code ec(last_error, asio::error::get_system_category());
          ol.complete(ec, 0);
        }
        else
          ol.release();
```

... and voila, ~8Mb/sec turns into 1350Mb/sec :)

Of course, if ASIO used Windows RIO with its lovely scatter-gather support, that would be even better, but even just using the code above would be a serious performance win.

**Comment by ned14** [comment]
I've just discovered that the same problem applies to POSIX too, asio::async_write() is unusably slow there too. I'll copy and paste in a solution for POSIX here shortly.

**Comment by chriskohlhoff** [comment]
Closing as "works for me".

In the absence of test code, I infer from the described symptoms that you were passing a `vector<const_buffer>` as the buffer sequence, where `size()` == 1M. The documentation states that the buffer sequence "may be copied", so don't pass such heavyweight objects.

The following test program uses a lightweight iterator range over a `vector<const_buffer>` to send 1M buffers in a single async_write operation:

    #include <algorithm>
    #include <array>
    #include <boost/asio.hpp>
    #include <boost/range.hpp>
    #include <chrono>
    #include <iostream>
    #include <random>
    #include <vector>
    
    const std::size_t buf_size = 128;
    const std::size_t buf_count = 1000000;
    
    namespace asio = boost::asio;
    
    int main()
    {
      std::random_device rd;
      std::mt19937 rng(rd());
    
      // Generate some random data in small chunks.
      std::vector<std::array<unsigned char, 128>> send_data(buf_count);
      for (std::size_t i = 0; i < buf_count; ++i)
      {
        std::iota(send_data[i].begin(), send_data[i].end(), 0);
        std::shuffle(send_data[i].begin(), send_data[i].end(), rng);
      }
    
      // Generate a random send order.
      std::vector<std::size_t> send_order(buf_count);
      std::iota(send_order.begin(), send_order.end(), 0);
      std::shuffle(send_order.begin(), send_order.end(), rng);
    
      // Make a buffer sequence used to send the data in this order.
      std::vector<asio::const_buffer> send_bufs(buf_count);
      for (std::size_t i = 0; i < buf_count; ++i)
        send_bufs[i] = asio::buffer(send_data[send_order[i]]);
    
      // Make a single contiguous buffer to receive the data.
      std::vector<char> recv_buf(buf_size * buf_count);
    
      asio::io_service ios{1};
    #if 1
      asio::local::stream_protocol::socket socket1(ios);
      asio::local::stream_protocol::socket socket2(ios);
      connect_pair(socket1, socket2);
    #else
      asio::ip::tcp::socket socket1(ios);
      asio::ip::tcp::socket socket2(ios);
      asio::ip::tcp::acceptor acceptor(ios, {asio::ip::tcp::v4(), 55557});
      socket1.connect({asio::ip::address_v4::loopback(), 55557});
      acceptor.accept(socket2);
    #endif
    
      for (std::size_t i = 0; i < 10; ++i)
      {
        auto start = std::chrono::steady_clock::now();
    
        asio::async_write(socket1,
            boost::make_iterator_range(send_bufs.begin(), send_bufs.end()),
            [](auto ec, auto n)
            {
              std::cout << "sent " << n << "\n";
            });
    
        asio::async_read(socket2, asio::buffer(recv_buf),
            [](auto ec, auto n)
            {
              std::cout << "received " << n << "\n";
            });
    
        ios.reset();
        ios.run();
    
        auto end = std::chrono::steady_clock::now();
    
        std::chrono::duration<float> elapsed = end - start;
        std::cout << elapsed.count() << " seconds\n";
        std::cout << (buf_size * buf_count / elapsed.count() / 1024 / 1024 / 1024) << " GB/s\n";
      }
    }

With the following output on my home Linux system:

    sent 128000000
    received 128000000
    0.131167 seconds
    0.908835 GB/s

**Comment by ned14** [comment]
This issue should remain open: ASIO should be using a much less stupid implementation strategy when passed say a vector of 1M buffers. Like the code examples given which demonstrate a much saner approach.

Using iterators to "borrow" a view of the scatter-gather buffers is a workaround for this issue, not a solution to this issue.

**Comment by vinniefalco** [comment]
Preserving for posterity

>This issue should remain open: ASIO should be using a much less stupid implementation strategy when passed say a vector of 1M buffers. Like the code examples given which demonstrate a much saner approach.

>Using iterators to "borrow" a view of the scatter-gather buffers is a workaround for this issue, not a solution to this issue.

**Comment by ned14** [comment]
> Preserving for posterity

I'm sure what you mean here. ASIO could use a more efficient storage mechanism when fed a large scatter-gather buffer list. The code I supplied creates a shared state and then indexes through that shared list. If ASIO is fed a buffer list exceeding some length or other, it could do exactly the same implementation and thus very significantly improve performance for very large buffer lists. I don't get the downvotes, this is hardly difficult to implement.

**Comment by sebt3** [comment]
![palmface](http://vignette2.wikia.nocookie.net/cardfight/images/f/f6/The_face_palm_of_agrivation..png/revision/latest?cb=20130609050634)

**Comment by ned14** [comment]
Ok, instead of the cryptic comments, please explain what's the problem?

**Comment by vinniefalco** [comment]
_"They cannot see the things that will hurt them."_

**Comment by ned14** [comment]
@vinniefalco Spell it out. I don't think you're being anything like as clever as you think you are.

**Comment by vinniefalco** [comment]
>Here is a far faster implementation

If you think the implementation of Asio may be improved, submit a pull request so that your changes may be evaluated and benchmarked.

**Comment by sebt3** [comment]
@ned14 if you want this to be reopened, dont whine, provide the test code @chriskohlhoff requested. Your test code have to desmonstrate the actual flaw.
Beside he provided you a code using the current version of ASIO that doesnt seems to have the issue you're telling.

**Comment by ned14** [comment]
> Beside he provided you a code using the current version of ASIO that doesnt seems to have the issue you're telling.

No, he worked around the issue by borrowing a reference to the vector of buffers via an iterator range:

```
asio::async_write(socket1,
        boost::make_iterator_range(send_bufs.begin(), send_bufs.end()),
        [](auto ec, auto n)
        {
          std::cout << "sent " << n << "\n";
        });
```

Because it guarantees to send the entire input, async_write() will take a copy of its input buffers if it was not able to send them all. That is unavoidable given the guarantee. Unfortunately right now it would appear that it will make another copy if the next socket fill couldn't send them all, then another copy if it couldn't send them all, then another copy and so on. That's the cause of the slowdown.

By using `boost::make_iterator_range(send_bufs.begin(), send_bufs.end())` he insteads gives async_write a lightweight reference to the original vector. Copying that frequently is not a slowdown. But now you have a lifetime issue because the lifetime of the async_write() will exceed the borrowed reference to its input vector of buffers.

What my issue reported is that when you really want async_write() to take a copy of a really large input of buffers because you're about to exit scope and its lifetime needs to last the length of the async_write(), it should not be repeatedly copying that array per socket fill. Just use `std::move()`, it does the right thing. Before C++ 11 then shared_ptr is probably easier.

Does this make more sense now?

**Comment by vinniefalco** [comment]
>Does this make more sense now?

Nope, it doesn't make sense at all because the documentation clearly states that `const&` parameters to initiating functions will be copied. Did you read the docs? Or maybe you think the docs are "wrong". Or to use your terminology "stupid."

>you're about to exit scope and its lifetime needs to last the length of the async_write()

It sounds like you're too lazy to write a wrapper so I'll do it for you
```
// Copyright 2017 Vinnie Falco
// Provided under the Boost Software License, see LICENSE.txt
template<class ConstBufferSequence>
class shared_buffers
{
    std::shared_ptr<ConstBufferSequence> buffers_;

public:
    using value_type =
        typename ConstBufferSequence::value_type;

    using const_iterator =
        typename ConstBufferSequence::const_iterator;

    shared_buffers(shared_buffers const&) = default;
    shared_buffers& operator=(shared_buffers const&) = default;

    template<class DeducedBuffers>
    shared_buffers(DeducedBuffers&& buffers)
        : buffers_(std::make_shared<ConstBufferSequence>(
            std::forward<DeducedBuffers>(buffers)
    {
    }

    const_iterator
    begin() const
    {
        return buffers_->begin();
    }

    const_iterator
    end() const
    {
        return buffers_->end();
    }
};
```

See? What was so hard about that? Now off to bed :)

**Comment by ned14** [comment]
Ok, I give up. Too much hostility and unpleasantness here. Not a way to manage an open source project :(

**Comment by mabrarov** [comment]
Sorry for continuation of this discussion. Just wanted to note that current design of Asio is cleaner in terms of memory allocation. If one needs to use expensive-to-copy buffers then some ref-counting solution (like @vinniefalco provided) has to be used. I'd prefer Asio (because it's about networking so it has to be efficient in terms of memory allocation) to avoid such (internal, implicit) memory allocation if possible. Current design of Asio makes me able to:

1. avoid usage of heap (with Asio's custom memory allocation) at all when I perform IO on established connection (i.e. I can pre-allocate all the required space once connection is established, I can use pools),
1. use "expensive-to-copy buffers" with help of adapter class if I really ready for that (understand pros and cons and find that "expensive-to-copy buffers" are better choice for the task I'm solving). 

Even with ref-counting adapter I can use some pre-allocation / recycling / pooling and Asio's design doesn't prevent me from doing this and doesn't repeat the same inside its internals. If I use [`enable_shared_from_this` approach](http://www.boost.org/doc/libs/1_64_0/doc/html/boost_asio/example/cpp03/chat/chat_server.cpp) for managing lifecycle of my data then I already have counter for my buffers (but that counter is decoupled from buffers concept) and I don't want Asio to repeat the same (with new allocations of memory).

**Comment by vinniefalco** [comment]
>I can use some pre-allocation / recycling / pooling

I've created an allocator which you can use to wrap your completion handlers, declare one of these on your "connection" object and then call `wrap()` on your completion handlers. You can also use it as an allocator if you have any AllocatorAwareContainer. It recycles memory quite efficiently, what do you think?
https://github.com/vinniefalco/Beast/blob/93061b76801cf77d2f176db820b26b5812d5288e/example/common/session_alloc.hpp

If you want to try it I can help. I'm curious to know how much it will boost performance in other programs.

**Comment by vinniefalco** [comment]
@chriskohlhoff I was just reviewing this issue yet again, and something occurred to me. It was suggested by the OP that there were lifetime issues which necessitated either a move of the buffers or some alternate method of managing lifetime such as the `shared_buffers` wrapper I provided above but what if we just do the exact opposite of his advice?

I'm thinking, what if instead of passing a **ConstBufferSequence** we create a wrapper that wraps the original buffer sequence using a non-owning reference? In other words a `std::reference_wrapper` which is a **ConstBufferSequence**. It would look something like this (see the code at the end of this issue).

What could be the purpose of such a thing? Well, consider this non-owning buffer sequence which happens to be over 200 bytes in size:

    using ch3_t = consuming_buffers<buffer_cat_view<
        typename Fields::reader::const_buffers_type,// header
        detail::chunk_header,                       // chunk-header
        boost::asio::const_buffers_1,               // chunk-ext
        boost::asio::const_buffers_1,               // crlf
        typename reader::const_buffers_type,        // body
        boost::asio::const_buffers_1,               // crlf
        boost::asio::const_buffers_1,               // chunk-final
        boost::asio::const_buffers_1,               // trailers 
        boost::asio::const_buffers_1>>;             // crlf

We call the visitor with it and pass a reference to the buffer. But instead we could use the function `make_buffers_ref` (equivalent of `std::ref` for buffer sequences) and pass that instead. The result is that a previously 200+ byte copied buffer sequence is now the size of a pointer. This change was trivial to implement in `beast::http::serializer` and results in a **6% performance gain in http-server-fast**.

----------
Code listing:

```
// Copyright 2017 Vinnie Falco
// Provided under the Boost Software License, see LICENSE.txt
//
// A very lightweight reference to a buffer sequence
template<class BufferSequence>
class buffers_ref
{
    BufferSequence const& buffers_;

public:
    using value_type =
        typename BufferSequence::value_type;

    using const_iterator =
        typename BufferSequence::const_iterator;

    buffers_ref(buffers_ref const&) = default;

    explicit
    buffers_ref(BufferSequence const& buffers)
        : buffers_(buffers)
    {
    }

    const_iterator
    begin() const
    {
        return buffers_.begin();
    }

    const_iterator
    end() const
    {
        return buffers_.end();
    }
};

// Return a reference to a buffer sequence
template<class BufferSequence>
buffers_ref<BufferSequence>
make_buffers_ref(BufferSequence const& buffers)
{
    return buffers_ref<BufferSequence>(buffers);
}
```

**Comment by lethe555** [comment]
why async_write take a const lvalue reference , not a forward reference? 
then wen can move BufferSequence into internal operations,
with 5d9d01729 internal operations can move buffers instead copy

**Comment by vinniefalco** [comment]
_BufferSequence_ has the same lightweight copy/move semantics as _Iterator_.

**Comment by lethe555** [comment]
a move seams not harmful , and can avoid `buffers_ref` or `shared_ptr` workaround in some case. :)

**Comment by vinniefalco** [comment]
Yes a move is harmful, because arguments passed to completion handlers can be relocated by the asio implementation. For example, this could never work as a copyable or movable buffer:
```
struct simple_buffer {
  std::size_t size_;
  unsigned char data_[1024];
  ...
```

Because the address of the object is not stable (asio can move it).  The changes in https://github.com/chriskohlhoff/asio/commit/5d9d01729db8957bb2db65b668c45dfe02db721a permit an implementation of _BufferSequence_ to use `unique_ptr` instead of `shared_ptr`.

**Comment by lethe555** [comment]
sorry , I can't fully understand your explanation, use unique_ptr then async_write just can't work, because unique_ptr can't copy without some workarounds, because  async_write take a const reference


> Yes a move is harmful, because arguments passed to completion handlers can be relocated by the asio implementation. For example, this could never work as a copyable or movable buffer:
> 
> ```
> struct simple_buffer {
>   std::size_t size_;
>   unsigned char data_[1024];
>   ...
> ```
> 
> Because the address of the object is not stable (asio can move it). The changes in [5d9d017](https://github.com/chriskohlhoff/asio/commit/5d9d01729db8957bb2db65b668c45dfe02db721a) permit an implementation of _BufferSequence_ to use `unique_ptr` instead of `shared_ptr`.

**Comment by vinniefalco** [comment]
> async_write take a const reference

Yeah, I don't know what's going on there, I think Chris just hasn't fixed it yet. All of those routines should receive the buffer as `ConstBufferSequence` or `ConstBufferSequence&&`.
