### ISSUE TITLE
Missing features now that MSVC is more standard conformant

### ISSUE THREAD

**Issue by mizvekov** [chriskohlhoff/asio#205]
The following features should be supported by current MSVC:

ASIO_HAS_VARIADIC_TEMPLATES
ASIO_DELETED
ASIO_CONSTEXPR
ASIO_HAS_STD_STRING_VIEW

**Comment by chriskohlhoff** [comment]
Fixed on master in ac89cf0ba28776e314584c622f8e36aa5816c471.
