### ISSUE TITLE
socket does not go to TIME-WAIT when closed with pending data

### ISSUE THREAD

**Issue by nunojpg** [chriskohlhoff/asio#209]
Current master on Linux 4.8.

CONSIDER:

data_ is a small buffer:

`std::array<uint8_t, 10> data_;`

And I am registering a async_read:

`asio::async_read(socket_, asio::buffer(data_),...`

After this call back I finish operations and call the socket destructor.

Because I initiate the close the socket must go to TIME-WAIT.

WHAT I DO:

I use NC to connect to the socket and send some data on a single burst.

I do 2 tests: sending 10 bytes and sending 15 bytes

WHAT HAPPENS:

When sending 10 bytes, the callback is invoked with length 10, and after it terminates the socket is destroyed and goes to TIME-WAIT.

When sending 15 bytes, the callback is invoked with length 10, and after it terminates the socket is destroyed and does NOT GO to TIME-WAIT.

Essentially it seems that if a open socket is destroyed(shutdown/close) when socket::available>0, it will not go to TIME-WAIT.

**Comment by chriskohlhoff** [comment]
This is TCP behaviour as implemented by the OS, not asio. The OS sends a TCP RST to the peer if you close the socket with unread data. If for some reason you can't read all the data, close the sender side of the connection using `shutdown`.
