### ISSUE TITLE
Which ASIO should I use if developing new code?

### ISSUE THREAD

**Issue by akoolenbourke** [chriskohlhoff/asio#222]
I was looking on think-async and noticed a 1.11 version of ASIO which looks like it's following the networking standard. The source forge zip however has a last modified of 2015 so I'm confused as to whether it's being maintained or whether work has moved over to some other implementation.

So my question is, which version of ASIO would it be recommended I invest in if I'm looking to develop a new framework based on ASIO that will be future proof?

Cheers
Aaron

**Comment by chriskohlhoff** [comment]
I advise you to use the master branch if starting a new project. This keeps you closer to the networking TS interfaces.

Now that the TS interface is finally set in stone, I will be making a new release off the master branch in the not too distant future.

**Comment by akoolenbourke** [comment]
Thanks Chris. As someone relatively new to ASIO (I have only done a few simple benchmarks) it's been very hard trying to get to grips with all the versions floating around.

Also, whilst I asked about future proofed-ness here, my other post was a little more concerned with how production ready it is. Do you consider the master (TS) branch to be production ready, primarily from a defect point of view? We will be using this in a commercial product.

Many thanks

**Comment by chriskohlhoff** [comment]
I make no guarantees, but I am not aware of any showstoppers and the master branch is now receiving the same testing automatically as previous releases were getting manually.

**Comment by akoolenbourke** [comment]
Many thanks Chris, and thank you for your massive contribution to C++ over the years.
