### ISSUE TITLE
why the buffer's type is const in read_some()

### ISSUE THREAD

**Issue by happieme** [chriskohlhoff/asio#226]
look at this function: size_t read_some( const MutableBufferSequence & buffers), also in receive, etc.
Why there's a const ???
The buffer is mutable, and we intend to modify it. So the "const" is not appropriate present here.
Do you think this is better : size_t read_some(MutableBufferSequence & buffers) ?

**Comment by Iwa13** [comment]
IMO, no. (That const stands for the immutable buffer list, however elements are too)
I think its appropriate here. Since mutable_buffer holds pointer to mutable memory and size, and const just implies that only pointer and size are immutable, not necessarily the memory that pointer points to.

**Comment by chriskohlhoff** [comment]
You pass the function a sequence of buffers to use, and the function promises not to modify the sequence itself, only the target memory. The constness of the sequence is "shallow" and doesn't extend to this target memory.

The POSIX scatter-gather functions do a similar thing:

http://pubs.opengroup.org/onlinepubs/009695399/functions/readv.html

Note the `const` in the `const struct iovec *` argument.

**Comment by happieme** [comment]
Ok. At last this won't affect anything.It can be used correctly. BUT !! The "const" implies the contents cannot be changed, but you tell the only pointer and size are immutable.  I think you are wrong.
the parameter "const struct iovec *iov ",  in http://pubs.opengroup.org/onlinepubs/009695399/functions/readv.html , I think this a misuse.It is not right!
Just think about below:
int a = 10;
const int* n=&a;
What do you think of this const?? only pointer and size ???
We should make the "const" have a consistent semantics. Maybe this is not a very important point for the  asio project. But please think twice about it. We should be more strict to make a GREAT PROJECT - ASIO. I like it!
