### ISSUE TITLE
Question: How to Run Blocking Tasks in thread pool using asio?

### ISSUE THREAD

**Issue by kamlesh-nb** [chriskohlhoff/asio#243]
@chriskohlhoff Could you please share example on how to run blocking tasks in thread pool using asio?

**Comment by arun11299** [comment]
@kamlesh-bambarde This helps ?
https://stackoverflow.com/questions/17648725/long-running-blocking-operations-in-boost-asio-handlers

**Comment by kamlesh-nb** [comment]
works
