### ISSUE TITLE
Spelling: DynamicBufferSequence

### ISSUE THREAD

**Issue by vinniefalco** [chriskohlhoff/asio#247]
quickref.xml and the documentation exposition calls it **DynamicBufferSequence** and "dynamic buffer sequence":
http://think-async.com/Asio/asio-1.11.0/doc/asio/reference/DynamicBufferSequence.html

The code uses the name **DynamicBuffer** and "dynamic buffer sequence".

Suggested: Use **DynamicBuffer** and "dynamic buffer" in quickref.xml and the rest of the documentation.

Beast uses `DynamicBuffer` for the type name, `buffer` for the formal parameter name, and "dynamic buffer" in exposition.

**Comment by ljluestc** [comment]
```

#include <boost/asio.hpp>
#include <iostream>

namespace asio = boost::asio;

// DynamicBuffer class to handle dynamic buffers
class DynamicBuffer {
public:
    DynamicBuffer(size_t size) : buffer_(size) {}

    // Other member functions for buffer management...

private:
    std::vector<char> buffer_; // Internal storage
};

// Function using DynamicBuffer
void process_buffer(DynamicBuffer& buffer) {
    // Processing logic here
    std::cout << "Processing buffer of size: " << buffer.size() << std::endl;
}

// Example usage
int main() {
    DynamicBuffer dynamic_buffer(1024); // Create a dynamic buffer of size 1024
    process_buffer(dynamic_buffer); // Process the buffer
    return 0;
}
```
