### ISSUE TITLE
Handler requires CopyConstructible (doc error)

### ISSUE THREAD

**Issue by vinniefalco** [chriskohlhoff/asio#275]
According to the net.ts specification **Handler** should only require **MoveConstructible**

See:
http://think-async.com/Asio/asio-1.10.6/doc/asio/reference/Handler.html
http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/Handler.html

And:
13.2.7.2 [async.reqmts.async.token] clause 3:
http://cplusplus.github.io/networking-ts/draft.pdf

**Comment by chriskohlhoff** [comment]
Fixed by 479a0c51f450bdccf5221b90f3814064fab34714.
