### ISSUE TITLE
Documentations for 1.66 failed to show codes

### ISSUE THREAD

**Issue by hoang408** [chriskohlhoff/asio#284]
I was following Boost 1.66 tutorial for ASIO Timer 1 to Timer 3 (http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/tutorial/tuttimer3.html).  I was quite intrigued as the documentations seemed to have missing info.  Searching around got me to the old documentations where I could see the whole thing.  I switch to 1.65 and it is good.  However, I still get the recommendation to switch to the latest page, which has missing info.  Can someone notify the dev team about this error?  Am I the first one to notice this?

**Comment by chriskohlhoff** [comment]
Fixed by 9eaa2a2e558a05d06066882072e3af941fb92cf1.
