### ISSUE TITLE
Unable to compile on Android NDK 15 due to missing pthread_cond_timedwait_relative_np

### ISSUE THREAD

**Issue by mstyura** [chriskohlhoff/asio#287]
The function `pthread_cond_timedwait_relative_np` was removed since `Android NDK 15`, the conditional compilation check used around this function has missing condition `defined(HAVE_PTHREAD_COND_TIMEDWAIT_RELATIVE)`.

The example of correct conditioning around function `pthread_cond_timedwait_relative_np` can be found in `Android` itself, for example:
https://android.googlesource.com/platform/frameworks/native/+/23c2fcbbf4be87580e64132150aa554b764425c2/include/utils/Condition.h#109

Similar non-portable function `pthread_cond_timedwait_monotonic_np` is also used with proper `defined(HAVE_PTHREAD_COND_TIMEDWAIT_MONOTONIC)` check within `Chromium`, example: 
https://chromium.googlesource.com/chromium/src/+/master/base/synchronization/condition_variable_posix.cc#116

Currently `asio` compilation failed when Android NDK 15 tool chain is used.

```
asio/asio/include/asio/detail/posix_event.hpp:123:9: error: no member named 'pthread_cond_timedwait_relative_np' in the global namespace
       ::pthread_cond_timedwait_relative_np(
       ~~^
```

**Comment by chriskohlhoff** [comment]
Fix applied in 173871f8551c1447b20000c8a354f2f44c000230.
