### ISSUE TITLE
Compile errors wenn using with boost headers

### ISSUE THREAD

**Issue by ClausKlein** [chriskohlhoff/asio#289]
bash-4.4$ ninja -j1
[1/4] Building CXX object src/examples/cpp11/CMakeFiles/asio_cpp11_iostreams_http_client.dir/iostreams/http_client.cpp.o
FAILED: src/examples/cpp11/CMakeFiles/asio_cpp11_iostreams_http_client.dir/iostreams/http_client.cpp.o 

/opt/local/bin/ccache /opt/local/bin/clang++  -DASIO_ENABLE_HANDLER_TRACKING \
-DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_DONT_PROVIDE_HYBRID_ERROR_HANDLING \
-DHAVE_OPENSSL -I/opt/local/include \
-I/Users/clausklein/Workspace/cpp/asio/asio/include -std=gnu++11 -MD -MT \
src/examples/cpp11/CMakeFiles/asio_cpp11_iostreams_http_client.dir/iostreams/http_client.cpp.o \
-MF src/examples/cpp11/CMakeFiles/asio_cpp11_iostreams_http_client.dir/iostreams/http_client.cpp.o.d \
-o src/examples/cpp11/CMakeFiles/asio_cpp11_iostreams_http_client.dir/iostreams/http_client.cpp.o \
-c /Users/clausklein/Workspace/cpp/asio/asio/src/examples/cpp11/iostreams/http_client.cpp

/Users/clausklein/Workspace/cpp/asio/asio/src/examples/cpp11/iostreams/http_client.cpp:36:21: error: no viable conversion from 'std::chrono::seconds' (aka 'duration<long long>') to 'const asio::basic_socket_iostream<asio::ip::tcp, boost::posix_time::ptime, asio::time_traits<boost::posix_time::ptime> >::duration' (aka 'const boost::posix_time::time_duration')
    s.expires_after(std::chrono::seconds(60));
                    ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/boost/date_time/posix_time/posix_time_config.hpp:57:30: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::chrono::seconds' (aka 'duration<long long>') to 'const boost::posix_time::time_duration &' for 1st argument
  class BOOST_SYMBOL_VISIBLE time_duration :
                             ^
/opt/local/include/boost/date_time/posix_time/posix_time_config.hpp:57:30: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::chrono::seconds' (aka 'duration<long long>') to 'boost::posix_time::time_duration &&' for 1st argument
/opt/local/include/boost/date_time/posix_time/posix_time_config.hpp:79:5: note: candidate constructor not viable: no known conversion from 'std::chrono::seconds' (aka 'duration<long long>') to 'boost::date_time::special_values' for 1st argument
    time_duration(boost::date_time::special_values sv) :
    ^
/Users/clausklein/Workspace/cpp/asio/asio/include/asio/basic_socket_iostream.hpp:375:38: note: passing argument to parameter 'expiry_time' here
  void expires_after(const duration& expiry_time)
                                     ^
1 error generated.
ninja: build stopped: subcommand failed.
bash-4.4$

**Comment by chriskohlhoff** [comment]
Fixed by d8387c93b3acfab403ab27efaa4f413d71e60194.
