### ISSUE TITLE
AsyncReadStream::async_read_some errors with optimization

### ISSUE THREAD

**Issue by tomaszjonak** [chriskohlhoff/asio#298]
Hi Chris,

I've recently run into issue with using AsyncReadStream concept in form of boost::process::async_pipe. Sample program provided on boost bugtracker (https://svn.boost.org/trac10/ticket/13515​). Sample is dockerized, I've also tested this on bare hardware with same results.

Using gcc without optimization return correct results - data in buffer and size of data written. Enabling any optimization returns constant zero size reads while modifying buffer. Strace on sample program shows that underlying readv calls return size in both cases.

Moreover this sample code results in sigill on clang 3.8.0-2ubuntu4 regardless of optimization settings.

Looks like this issue was previously reported:
#261 
https://github.com/klemens-morgenstern/boost-process/issues/130

**Comment by chriskohlhoff** [comment]
The Boost.Process library is missing the `return` keyword in a couple of places. Perhaps that's the cause of the problem here.

```
diff --git a/include/boost/process/detail/posix/async_pipe.hpp b/include/boost/process/detail/posix/async_pipe.hpp
index 8f138bd..e3057d7 100644
--- a/include/boost/process/detail/posix/async_pipe.hpp
+++ b/include/boost/process/detail/posix/async_pipe.hpp
@@ -136,7 +136,7 @@ public:
         const MutableBufferSequence & buffers,
               ReadHandler &&handler)
     {
-        _source.async_read_some(buffers, std::forward<ReadHandler>(handler));
+        return _source.async_read_some(buffers, std::forward<ReadHandler>(handler));
     }
 
     template<typename ConstBufferSequence,
@@ -147,7 +147,7 @@ public:
         const ConstBufferSequence & buffers,
         WriteHandler&& handler)
     {
-        _sink.async_write_some(buffers, std::forward<WriteHandler>(handler));
+        return _sink.async_write_some(buffers, std::forward<WriteHandler>(handler));
     }
```

**Comment by tomaszjonak** [comment]
Checked and can confirm this fixes the issue. Somehow I have overlooked that part. Thanks for help Chris!
