### ISSUE TITLE
Why are error codes being deprecated?

### ISSUE THREAD

**Issue by ruipacheco** [chriskohlhoff/asio#302]
I've noticed this in the file io_context.ipp:

```
io_context::count_type io_context::run()
{
  asio::error_code ec;
  count_type s = impl_.run(ec);
  asio::detail::throw_error(ec);
  return s;
}

#if !defined(ASIO_NO_DEPRECATED)
io_context::count_type io_context::run(asio::error_code& ec)
{
  return impl_.run(ec);
}
#endif // !defined(ASIO_NO_DEPRECATED)
```
Why is the use of `std::error_code` being deprecated?

**Comment by ruipacheco** [comment]
I wonder if this is linked to issue (143)[https://github.com/chriskohlhoff/asio/issues/143]

**Comment by vinniefalco** [comment]
It isn't all error codes being deprecated but rather, some functions are now exclusively indicating errors using exceptions. This makes sense. Remember that functions which have `error_code&` in their signature can still throw exceptions, the most common one being `std::bad_alloc`. What I think this change signifies is that `io_context::run` will not return errors which do not indicate exceptional circumstances.

You also see this with `basic_io_object::cancel`. In my opinion, this is a good change.

**Comment by ruipacheco** [comment]
What happens to code that compiles with -fno-exceptions?

**Comment by vinniefalco** [comment]
> What happens to code that compiles with -fno-exceptions?

That's up to you. You should define `ASIO_NO_EXCEPTIONS=1` and then provide your own implementation of `throw_exception` that does whatever you want:

https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/detail/throw_exception.hpp#L33

**Comment by vinniefalco** [comment]
@chriskohlhoff 

If we change

    "Only define the throw_exception function..." 

to

    "Asio will only define the throw_exception function..."

it could be more clear.

**Comment by ruipacheco** [comment]
Can you provide any examples of a custom definition of `throw_exception` when `ASIO_NO_EXCEPTIONS` is defined?

**Comment by vinniefalco** [comment]
```
template <typename Exception>
void throw_exception(const Exception& e)
{
    std::cerr << "Your app just shit the bed, because: " << e.what() << std::endl;
    std::terminate();
}
```

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by ruipacheco** [comment]
Done!
