### ISSUE TITLE
Missing tag 1.12.1

### ISSUE THREAD

**Issue by Code7R** [chriskohlhoff/asio#309]
FYI, the website http://think-async.com/Asio/Download has a newer version 1.12.1 but I cannot see a such release on Github.

**Comment by ruipacheco** [comment]
Any news on this?

**Comment by KindDragon** [comment]
@chriskohlhoff please publish tag

**Comment by DarthGandalf** [comment]
Also b73dc1d2c0ecb9452a87c26544d7f71e24342df6 which claims to be the 1.12.1 is on citest-master branch instead of master.

**Comment by anthraxx** [comment]
@chriskohlhoff ping. please push proper commits and tag

**Comment by Lord-Kamina** [comment]
Wonder what happened...

**Comment by podsvirov** [comment]
The tag [asio-1-12-1](https://github.com/chriskohlhoff/asio/releases/tag/asio-1-12-1) added.

Looks like we can close this issue now.

**Comment by Code7R** [comment]
Yes, we can.

**Comment by podsvirov** [comment]
@Code7R, thanks for quick reaction!
