### ISSUE TITLE
how can i use deadline_timer_service without boost?

### ISSUE THREAD

**Issue by yandaren** [chriskohlhoff/asio#310]
how can i use deadline_timer_service without boost,  such as we use 'asio::detail::chrono_time_traits' as default TimeTraits for deadline_timer_service ?

**Comment by ruipacheco** [comment]
Have you tried building with ASIO_STANDALONE defined?

**Comment by yandaren** [comment]
yeah, i use the asio with ASIO_STANDALONE define, but the class deadline_timer_service only compiled when ASIO_HAS_BOOST_DATE_TIME was defined...

`#ifndef ASIO_DEADLINE_TIMER_SERVICE_HPP
#define ASIO_DEADLINE_TIMER_SERVICE_HPP

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
# pragma once
#endif // defined(_MSC_VER) && (_MSC_VER >= 1200)

#include "asio/detail/config.hpp"

#if defined(ASIO_HAS_BOOST_DATE_TIME) \
  || defined(GENERATING_DOCUMENTATION)

#include <cstddef>
#include "asio/async_result.hpp"
#include "asio/detail/deadline_timer_service.hpp"
#include "asio/io_service.hpp"
#include "asio/time_traits.hpp"
#include "asio/detail/timer_queue_ptime.hpp"

#include "asio/detail/push_options.hpp"

namespace asio {

/// Default service implementation for a timer.
template <typename TimeType,
    typename TimeTraits = asio::time_traits<TimeType> >
class deadline_timer_service
#if defined(GENERATING_DOCUMENTATION)
  : public asio::io_service::service
#else
  : public asio::detail::service_base<
      deadline_timer_service<TimeType, TimeTraits> >
#endif`

**Comment by 2underscores-vic** [comment]
Why can't you use waitable_timer instead? steady_timer or system_timer . They are std::chrono-compatible

**Comment by yandaren** [comment]
ok, thanks, i'll try it!
