### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by MikeGitb** [chriskohlhoff/asio#329]
Are there any plans to add CMake support? 

There is a PR from two years ago (https://github.com/chriskohlhoff/asio/pull/128) but there hasn't been any official reaction to it.

**Comment by MikeGitb** [comment]
Best I can tell, chris is completely unresponsive to github issues, so it probably makes no sense to ask for future plans or features here.

**Comment by podsvirov** [comment]
Hello @MikeGitb, I'm author of #128. May be you can tell there what best place to promote this issue?

**Comment by MikeGitb** [comment]
@podsvirov: Unfortunately I have no idea. Maybe directly via email? But IIRC even fellow boost maintainers like @vinniefalco have problems reaching chris. I guess he is completely occupied with the standardization effort. Very sad that it is so hard to interact with the maintainer(s) of such an importent c++ library.

**Comment by vinniefalco** [comment]
>  I guess he is completely occupied with the standardization effort
I wish
