### ISSUE TITLE
Can I configure asio to use other SSL libraries besides OpenSSL?

### ISSUE THREAD

**Issue by ruipacheco** [chriskohlhoff/asio#350]
Is there a way to configure Asio to use other SSL libraries like BearSSL or Botan?

**Comment by mabrarov** [comment]
https://konradzemek.com/2015/08/16/asio-ssl-and-scalability/
https://github.com/chriskohlhoff/asio/issues/52
https://github.com/chriskohlhoff/asio/issues/74

**Comment by ruipacheco** [comment]
I guess libraries like Botan would require some serious rewriting.

**Comment by reneme** [comment]
Sorry for pulling out closed tickets, but I stumbled over this by accident.
In fact Botan offers an adapter for Boost ASIO that is pretty much a drop-in replacement for ASIO's ssl_stream.

https://botan.randombit.net/handbook/api_ref/tls.html#tls-stream
