### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by fawdlstty** [chriskohlhoff/asio#359]
我近期发现了一个问题，boost1.69，关于boost::asio::io_context对象的问题，有如下定义：
```
boost::asio::io_context				m_io_context;
boost::asio::ip::tcp::socket		m_socket { m_io_context };
```
然后，下面有两块代码，分别取名为“代码段1”和“代码段2”
代码段1：
```
while (true) {
	std::chrono::system_clock::time_point _tp = std::chrono::system_clock::now () + std::chrono::milliseconds (200);
	m_io_context.run_until (_tp);
	std::this_thread::sleep_until (_tp);
}
```
代码段2：
```
boost::asio::ip::tcp::resolver _resolver (m_io_context);
auto endpoints = _resolver.resolve ("testimcore.9shows.com", "9999");
boost::asio::async_connect (m_socket, endpoints, [this] (error_code ec, tcp::endpoint) {...});
```
其中，代码段1我放到一个单独的线程中执行。假如我先执行了代码段2，再创建线程执行代码段1，那么就没任何问题；假如我先创建线程执行代码段1，然后我过一会再执行代码段2，那么异步函数boost::asio::async_connect里面传入的lambda表达式将永远不被调用到。其次，假如我把connect改为同步，那么连接是没问题的，但其他异步读写函数async_xxx里面传入的lambda表达式都将永远不被调用到。

**Comment by fawdlstty** [comment]
另外提供一个建议：async_write函数假如这样写：
```
boost::asio::async_write (m_socket, boost::asio::buffer ((void*) m_str.c_str (), m_str.size ()), [this] (error_code ec, std::size_t) {
	...
});
```
将会有一个问题：假如函数调用完之后即释放m_str，将导致最终发送的数据全部为错误数据。

**Comment by fawdlstty** [comment]
建议是调用async_write后拷贝一份发送的内容，避免因释放缓冲区导致数据发送错误

**Comment by lz89** [comment]
Please use English to describe your issue.
请使用英文描述你的问题。
