### ISSUE TITLE
memory leaks occur when SSL is used in multithreading,even if it's just declaring ssl::context objects

### ISSUE THREAD

**Issue by zhllxt** [chriskohlhoff/asio#368]
`int main(int argc, char* argv[])
{
#if defined(WIN32) || defined(_WIN32) || defined(_WIN64) || defined(_WINDOWS_)
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
#endif

	// 1,Memory leaks occur when ssl::context objects are used in threads,
	// as you can see in Windows Task Manager, memory usage continues to grow.
	for (int i = 0; i < 0x7fff; i++)
	{
		std::thread([]()
		{
			asio::ssl::context ctx(asio::ssl::context::sslv23);
		}).join();
	}

	// 2.But if you don't use ssl::context in threads, there won't be a memory leak,
	// and memory usage will not increase.
	//for (int i = 0; i < 0x7ffff; i++)
	//{
	//	asio::ssl::context ctx(asio::ssl::context::sslv23);
	//}

	return 0;
}`

This problem has been bothering me for a long time. Please help me.

**Comment by mabrarov** [comment]
It could be some set / map where ID of thread is used as a key to implement thread local data.

**Comment by madmongo1** [comment]
Why would you create more than one ssl::context in a program? All connections can share the same one.

**Comment by zhllxt** [comment]
I actually did only create one ssl::context in a program, but even then, there's still a memory leak, so i'm just giving this example just to make it more obvious.

**Comment by paresy** [comment]
You are probably impacted by this:
https://github.com/curl/curl/issues/5282
https://github.com/openssl/openssl/issues/6081
