### ISSUE TITLE
asio::dispatch documentation is wrong

### ISSUE THREAD

**Issue by tilsche** [chriskohlhoff/asio#374]
The documentation for the free function `asio::dispatch` is identical to the one of `asio::post`.

> ...
> The function object is queued for execution, and is never called from the current thread prior to returning from dispatch().
> ...

The documentations of `io_context::post` and `io_context::dispatch` differ exactly in this critical point.

`asio::defer` is also documented exactly like the other two, but I don't know whats correct there...

**Comment by chriskohlhoff** [comment]
Addressed in asio version 1.13.0.
