### ISSUE TITLE
Object per io_context worker thread

### ISSUE THREAD

**Issue by chreniuc** [chriskohlhoff/asio#379]
Hi,
I have a question related to asio.

Let's say I have some thread workers in an `io_context`, I want each worker thread to have one object that contains some informations(ex: configuration parameters) that will be used in the worker method(handler). So we would have something like this:

```c++
thread([]{
    class configuration_obj_per_thread;
    io_context.run();
});

//post work
io_context.post(&worker_method, ...);

// Handler
void worker_method(...)
{
    // use configuration_obj_per_thread that was created specifically for this thread
}
```

One implementation is to create a global `std::map<int,class>`, where the `key` is the `thread_id` of one specific worker thread and the `value` is the object for that specific thread(`configuration_obj_per_thread`). This way for each worker thread we will have one distinct object.

```c++
thread([]{
    class configuration_obj_per_thread;
    global_map[this_thread::get_id()]] = configuration_obj_per_thread;
    io_context.run();
});
```

So in the handler you would do something like this:

```c++
void worker_method(...)
{
    class& configuration_obj_per_thread = global_map.[this_thread::get_id()];
  // use it
}
```

I was wondering if there is another method of doing this, nicer, maybe via `io_context` somehow(when calling `run` on an `io_context`), but I couldn't find any informations. Has anyone been in a simillar situation?

**Comment by arun11299** [comment]
Can't you use a thread local storage for storing the configuration per thread ?

**Comment by chreniuc** [comment]
That could work :smile: 

I'll close this issue.
