### ISSUE TITLE
ip multicast tests fail under pbuilder

### ISSUE THREAD

**Issue by mwanner** [chriskohlhoff/asio#38]
The test suite (of the non-boost asio) fails under restricted environments, where setsockopt returns ENODEV when given the IP_ADD_MEMBERSHIP argument. This led to the following Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769306

The following patch tries to circumvent this by ignoring join failures due to ENODEV and makes the leave_group tests conditional on join_group success:
http://anonscm.debian.org/cgit/collab-maint/asio.git/plain/debian/patches/relax-ip-multicast-tests.diff

**Comment by chriskohlhoff** [comment]
Fixed in 060d3016886f65c1b865e6d2b33ee648816815b1.

**Comment by mwanner** [comment]
Thanks, cool. I'll try the patch with the next Debian revision I upload.
