### ISSUE TITLE
Requiring async_result<...>::return_type burdens overhead

### ISSUE THREAD

**Issue by Naios** [chriskohlhoff/asio#380]
The universal model improved in https://github.com/boostorg/asio/commit/0568d3bf0b49 currently requires a `return_type` to be exposed from the `async_result` specialization in order to be buildable:

```cpp
    template <typename CompletionToken, typename Signature>
    struct async_result
    {
      typedef /* ... */ return_type;
                        ^^^^^^^^^^^

      template <typename Initiation, typename RawCompletionToken, typename... Args>
      static return_type initiate(Initiation&& initiation, RawCompletionToken&& token, Args&&... args);
    };
```

The `return_type` is only allowed to depend on the Signature itself (`void()` for instance),
but not on the `Initiation` callable nor its arguments `Args`.

Due to this we are unable to return a `return_type` which doesn't do any type erasure underneath, and this burdens some unneccessary overhead and limitations.

For instance if we want to add a specialization which wraps the initiating function into a callable that requires the actual callback for the invocation we would have to implement it like this:

```cpp
template <typename Executor = asio::executor>
struct use_callable_t {
  constexpr use_callable_t() {
  }
};

constexpr use_callable_t<> use_callable;

namespace asio {
template <typename Executor, typename... Args>
class async_result<use_callable_t<Executor>, void(Args...)> {
public:
  using return_type = std::function<void(std::function<void(Args...)>)>;

  explicit async_result(use_callable_t<Executor>& h) {
    (void)h;
  }

  template <typename Initiation, typename... InitArgs>
  static return_type initiate(Initiation&& initiation,
                              use_callable_t<Executor>, InitArgs&&... args) {
    return [
      initiation = std::forward<Initiation>(initiation),
      init = std::make_tuple(std::forward<InitArgs>(args)...)
    ](auto&& callback) mutable {
      using callback_t = decltype(callback);
      std::apply(
          [&](auto&&... args) {
            std::invoke(std::forward<callback_t>(initiation),
                        std::forward<callback_t>(callback),
                        std::forward<decltype(args)>(args)...);
          },
          std::move(init));
    };
  }
};
} // namespace asio

//....

auto callable = deadline_timer.async_wait(use_callable);
callable([] (auto&&... args) {
    // Triggers the invocation
})
```

In this example we are requiring type erasures through `std::function` such that we can provide the actual `return_type` in front without to known the actual `initiate` aguments.

**It would be better if `async_result<>` doesn't require the `return_type` anymore and relies more on an auto deduced return type of `initiate` such that we actually can support such cases at zero cost**

If that would be supported we could drop the type erasure completly here,
such that every async* call would return the raw lambda instead.

I know that asio might want to support earlier versions than C++11/14 where `decltype` and `auto` deduction isn't available or well supported, but it would be great if this could be taken into account when working on the standard library specification for `async_result` or the universal model.

**Comment by raJeev-M** [comment]
>It would be better if async_result<> doesn't require the return_type anymore and relies more on an auto deduced return type of initiate such that we actually can support such cases at zero cost

Without having `return_type` alias , how do you get to know the return-type of your asynchronous model?

For example, if you want to know  `return_type `  of `use_continuation` and with the current approach 
we can do something like 

`typename async_result<use_continuation, void(Args...)>::return_type `

How do we do if it were to be figured from `initiate`?

`decltype(declval<async_result<use_continuation, void(Args...)>().initiate(declval<args>()..)>)` ?

**Comment by Naios** [comment]
Fixed in https://github.com/boostorg/asio/commit/77b14fff7f63ca69fbb80e6a9fe97ff56f661a43
