### ISSUE TITLE
Missing release 1.14.0 (Boost 1.70)?

### ISSUE THREAD

**Issue by phprus** [chriskohlhoff/asio#386]
Boost 1.70 (https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/history.html) has a newer asio version 1.14.0, but this version isn't released on Github.

**Comment by sdamm** [comment]
I am quite certain, that this is a typo in the boost docs and commit message in the boost repo, as the source matches that of ASIO 1.13 (except the boost namespaces, ...). I haven't checked every difference, but places i know changed from 1.12 to 1.13 have the 1.13 version and checking ~50 random files there seemed no differences between the boost 1.70 and ASIO 1.13 version.

https://github.com/chriskohlhoff/asio/releases - 1.13 Version
