### ISSUE TITLE
segmentation fault (core dumped) of epoll_reactor.ipp#L244

### ISSUE THREAD

**Issue by betachen** [chriskohlhoff/asio#407]
https://github.com/chriskohlhoff/asio/blob/2a1f68845adec11574bfd91a7f860e63edd529a5/asio/include/asio/detail/impl/epoll_reactor.ipp#L244

![image](https://user-images.githubusercontent.com/12060728/60942574-afc3db80-a315-11e9-91d4-90c939069aa3.png)

**Comment by betachen** [comment]
Boost 1.58 release.
Looking forward for response, Thanks a lot.

**Comment by raJeev-M** [comment]
what were you trying to do, If I may ask?

**Comment by betachen** [comment]
An exchange system, built a REST server based on ASIO.
It accepted over 1 millon request per day.

then I found program crashed today, gdb into this core dump file , I found crashed here. a normal day, normal requests.

**Comment by raJeev-M** [comment]
I think there must be a race in your code: when you see

```
if (true) {
....
return; //it should return, no way of going past return.
}
```

Possibility of two actors using same `descriptor_data` ?

**Comment by betachen** [comment]
I see, probably. what `descriptor_data` stand for ? the incoming buffer of epoll?

**Comment by raJeev-M** [comment]
Well.. I think, to put it simply (talk about epoll), It is a data that describes your interests (events you are looking for on a FD), plus, the operation you want to perform on-occurrence of that event.

**Comment by raJeev-M** [comment]
Nonetheless, I don't understand 

> the incoming buffer of epoll?

**Comment by arun11299** [comment]
@betachen Most likely you are using a Socket IO object from two threads. IO objects are not thread safe. Can you check your socket object use ?

**Comment by betachen** [comment]
@arun11299 @raJeev-M Thanks for replying.

I found this, may clear my issue: <https://svn.boost.org/trac10/ticket/7611#comment:15>
I think it's my code fault, I m doing socket close on the other thread, then I replaced it with socker.cancel.

Still in testing, if issue solved, I will report here again.

Thanks for all your help.

**Comment by betachen** [comment]
race issue of threading when access socket object within my code.
runing normally 1 month, so close issue.
