### ISSUE TITLE
Data may not be able to reach to the peer on Debian 9 (32 bits, newest)

### ISSUE THREAD

**Issue by youngwolf-project** [chriskohlhoff/asio#408]
I have an open source project (https://github.com/youngwolf-project/ascs) based on asio (standalone edition), clone it then cd to examples directory and execute make, then cd to echo_server and execute ./release/echo_server, then open a new window and cd to ../echo_client and execute ./release/echo_client, you'll see 16 links established, then type '10000 1024 0 0 5' in echo_client to start the performance test, sometime, the test cannot finish because some data can never reach to  echo_server (if you cannot reproduce this issue, try 100000), I don't know why, but following things are sure:
1. echo_client has called asio::async_write and the callback handler has not been invoked;
2. echo_server has called asio::async_read and the callback handler has not been invoked too;
3. Debian 7 (32 bits), Ubuntu 18.04 (64 bits), Fedora 29 (64 bits) , win7 (64 bits) and win10 (64 bits) don't have this issue.

Seems the asio on echo_server endpoint didn't put the socket to epoll to monitor it.

**Comment by raJeev-M** [comment]
your supposed problem...

>echo_client has called asio::async_write and the callback handler has not been invoked;
>echo_server has called asio::async_read and the callback handler has not been invoked too;

it doesn't follow your conclusion 

>asio on echo_server endpoint didn't put the socket to epoll to monitor it. (?)


your Inputs and registering socket for events has nothing in common to collide.. sounds even remotely impossible, can you justify why have you come to this conclusion (I am interested )

>...echo_server has called asio::async_read and the callback handler has not been invoked too...

It will be invoked when read has been finished (+ve case), so, for some reason read operation hasn't been finished (or returned)-- is anything wrong with the characters you've been passing? try change `async_read` to something like `read_until` or `read_some`....? and confirm your hypothesis.

**Comment by youngwolf-project** [comment]
I have two variable IsSending and IsReceiving (only in my local ENV, not in git repository), I assign true to IsSending before call asio::async_send, and assign false to it in the send callback, for IsReceiving, I assign true to it before call asio::async_read, and assign false to it in the recv callback.
When the performance test get stuck, I check IsSending and IsReceiving on the two endpoint, the server show it's receiving messages (no data been receipted) and the client show it's sending messages.

I used the edition of asio::async_read that needs a CompletionCondition, my protocol is length + body.

**Comment by raJeev-M** [comment]
Paste the version of `async_read` you used and the `CompletionCondition`-- based on the result of completionCondition an `async_read` could spin `for(;;)ever` without calling the `handler`.

**Comment by youngwolf-project** [comment]
Before, I meant just the behavior seems that asio not monitored the native SOCKET, data can be sent and receipt for quite a while before the transaction get stuck, I have 16 links, client send 10000 messages on each link, and each message‘s length is 2 + 1024 (length + body), server send every message back (echo test).
More strange thing is, only Debian 9 has such issue, I tried old asio on it, the issue still exists, I also tried the newest asio on Debian 7, no such issue was found.

There's a utility I call unpacker (https://github.com/youngwolf-project/ascs/blob/master/include/ascs/ext/unpacker.h) in my ascs project, it's responsible for parsing above messages, please just focus on "class unpacker" (there're many unpackers in that header file), it also provide the completion_condition, if completion_condition returns 0, the parse_msg(size_t , container_type&) virtual function will be called to move integrated messages to container_type (a std::list).

PS.
i_unpacker is a pure virtual interface, it declares all virtual functions that the unpacker implemented.
macro ASCS_SCATTERED_RECV_BUFFER is not defined.
macro ASCS_MSG_BUFFER_SIZE is defined as 4000.
After the performance test get stuck, the unpacker::cur_msg_len is -1, and the unpacker::remain_len is 0.
Since the unpacker born in 2012, no such issue was found until I upgraded my Debian 8 to Debian 9.
I'm also trying hard to find out the root cause from my code and will continue.

**Comment by youngwolf-project** [comment]
One more supplementation, I tried Debian 10 (64 bits) today, no such issue was found.

**Comment by youngwolf-project** [comment]
Replaced by #793
