### ISSUE TITLE
How to accept on one io_context, but perform on other ?

### ISSUE THREAD

**Issue by dmxvlx** [chriskohlhoff/asio#413]
Hi guys !

I have the acceptor in work thread and io_context (acceptor_io_).

And I have too few io_context (io_N) looped in their own threads.

But I can't get worked code: clients end up with timeouts while try to connect.

If you have tips/snippets, please just give me it.

I do next:

```c++
void server::work_thread(asio::io_context* io) {

  if (io == &acceptor_io_) {
    acceptor_.async_accept(
      io_N,
      std::bind(
        &server::handle_accept,
        this,
        std::placeholders::_1,
        std::placeholders::_2
      )
    );
  }

  while (is_open() && !io->stopped()) {
    if (!io->poll()) { std::this_thread::yield(); }
  }
}
```

And in server::handle_accept:

```c++
void server::handle_accept(const asio::error_code& err, asio::ip::tcp::socket peer) {

  if (!err) {
    // do assign peer socket to session object
  }

  acceptor_.async_accept(
    io_N,
    std::bind(
      &server::handle_accept,
      this,
      std::placeholders::_1,
      std::placeholders::_2
    )
  );

}
```

--
regards

**Comment by raJeev-M** [comment]
I am not sure about others, but I don't quite get what your ask is.
Secondly, not sure how it ended up under Issues.

And, for questions like these, I usually prefer  https://stackoverflow.com/

**Comment by ngrodzitski** [comment]
Hi @dmxvlx 

I've come across the same question. And found no standard solution (for some definition of standard). But it is still possible with passing native handle between socket abstractions given by ASIO.

Sample code showing the idea:
https://gist.github.com/ngrodzitski/0f542e63a3a87ad884b5e86269df1107

**Comment by raJeev-M** [comment]
@ngrodzitski , your reply kind-of helped me to understand what is the ask from OP... let me go through it and correct me if I am wrong in that.

OP wants to have acceptor with one io_context and handle the further events on the accepted socket via other io_context (?)

And, I looked at your code, the solution you've been proposing is, in the completion-token of `async_accept`
```
[&]( auto ec, auto socket ){
                if( !ec )
                {
                    std::cout << "[tid:" << std::this_thread::get_id() << "] "
                              << "Receive: connection from "
                              << socket.remote_endpoint() << std::endl;

                    tcp::socket handler_socket{ m_handler_io_context, // another ctx!
                                                tcp::v4(),
                                                socket.release() };

                    // Or push native handler to already initiated socket:
                    /*
                    tcp::socket handler_socket{ m_handler_io_context };
                    handler_socket.assign( tcp::v4(), socket.release() );
                    std::make_shared< echo_session_t >( std::move( handler_socket ) )
                        ->start();
                    */
```
I wonder why this is the only solution, IIRC, there is actually an another overload 
`acceptor.async_accept(socket, accept_handler); `  where `socket` object could be pre-constructed with whichever io_context we want and this overload accepts a new connection into 
`socket` ...so, could you tell me why this overload won't help us in this case or did I miss to notice anything?

**Comment by ngrodzitski** [comment]
@raJeev-M 
I've looked through the reference and you 90% wright. The minor correct is that you pass target `io_context` explicitly (not a `socket`):

https://chriskohlhoff.github.io/networking-ts-doc/doc/networking_ts/reference/basic_socket_acceptor/async_accept/overload2.html
http://think-async.com/Asio/asio-1.12.2/doc/asio/reference/basic_socket_acceptor/async_accept/overload4.html

Navigating one level up in the reference links above you can see all overloads and there is no overload receiving socket as an argument, but that is not essential difference. And clearly that looks much better than messing with native handle. 

PS I was not saying that my snippet shows the only way (now its clear that it is not).

**Comment by raJeev-M** [comment]
@ngrodzitski 

>there is no overload receiving socket as an argument

https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/basic_socket_acceptor.hpp#L1329 

Am I seeing anything wrong? this is the overload I was referring to.

**Comment by raJeev-M** [comment]
```
   * @par Example
   * @code
   * void accept_handler(const asio::error_code& error)
   * {
   *   if (!error)
   *   {
   *     // Accept succeeded.
   *   }
   * }
   *
   * ...
   *
   * asio::ip::tcp::acceptor acceptor(my_context);
   * ...
   * asio::ip::tcp::socket socket(my_context); // I hope we can have a different context here
   * acceptor.async_accept(socket, accept_handler);
   * @endcode
```

**Comment by dmxvlx** [comment]
@ngrodzitski, @raJeev-M,

thanks a lot for yours help/tips/links etc, and sorry for my english ))

**Comment by ngrodzitski** [comment]
@raJeev-M 
> Am I seeing anything wrong? this is the overload I was referring to.

Yep, my bad. Interestingly that it is not mentioned in Networking TS doc. Maybe it is considered less safe API as it allows one to keep an access to socket which is kind-of running accept operation. Anyway passing `io_context` looks better to me.

**Comment by raJeev-M** [comment]
@ngrodzitski , Thanks for acknowledging it, and I don't want to tail after a closed-issue, but

>Maybe it is considered less safe API as it allows one to keep an access to socket which is kind-of running accept operation

I am not sure about the validity of this proposition.
