### ISSUE TITLE
ip::address_v4(0x04030201u).to_string() returns '4.3.2.1' for Little Endian

### ISSUE THREAD

**Issue by dmxvlx** [chriskohlhoff/asio#416]
As described in the documentation, argument of constructor in host byte order.
But then it should be '1.2.3.4' by the to_string() method. Is not ?
Or may be I can't catch sense of work the to_string() ?

--
regards

**Comment by igsol** [comment]
The binary form of Internet host address traditionally is in network byte order. Thus that you get is correct. You can `man inet_aton` :wink:

**Comment by dmxvlx** [comment]
igsol, thank you very much !

2019-08-06 20:40 GMT+05:00, igsol <notifications@github.com>:

**Comment by dmxvlx** [comment]
I was noticed by igsol: 

> The binary form of Internet host address traditionally is in network byte order. Thus that you get is correct. You can man inet_aton

thanks !

Would be good to mention about it in the documentation ;)

**Comment by igsol** [comment]
@dmxvlx I get used to see such behavior a many years. So I gave the answer just automatically:)
But after that I put a look into docs and thought that your question makes sense, docs confuse me as well :) So I removed my answer, but you answered faster.

**Comment by dmxvlx** [comment]
@igsol Firstly my app not worked, after reading docs I had feeling like fool, and after your the answer I was surprised :) thanks again !

**Comment by igsol** [comment]
I had I time to put a look more on the current asio docs without rush:
```
  Construct an address from an unsigned integer in host byte order.
  address_v4(
    uint_type addr);
```
Little-endian 0x04030201 represents 4 in the highest and 1 in the lowest bytes.

The IP address "4.3.2.1" represents 4 in the highest octet, 1 in the lowest one.

Despite the internal representation of in_addr in the network order, I think the current docs are correct.

Usually I prefer to use more obvious `ip::address::make_address( "1.2.3.4" );` or `ip::address::make_address_{v4|v6}` functions.

**Comment by dmxvlx** [comment]
@igsol  thank you for the informing !
That is  not problem for me, for now I know how it works :)

Could you check this code, please:
```c++
inline static std::uint32_t to_uint(std::string_view s) noexcept {
  std::uint32_t ret = 0;
  if (!std::empty(s)) {
    asio::error_code ec;
    asio::ip::address addr = asio::ip::make_address(std::data(s), ec);
    if (!ec && addr.is_v4()) { ret = addr.to_v4().to_uint(); }
  } return ret;
}
```

If I do next (on Little Endian machine):
```c++
std::cerr << "0x" << std::hex << to_uint("1.2.3.4") << std::endl;
```

I'm getting '0x1020304', but docs says:
```c++
/// Get the address as an unsigned integer in host byte order
ASIO_DECL uint_type to_uint() const ASIO_NOEXCEPT;
```

**Comment by igsol** [comment]
> I'm getting '0x1020304'

All right. 
0x1 is highest byte.
In the address "1.2.3.4" 1 is in highest octet as well.

The little-endian representation of 0x01020304:

| | | | | |
|---|---:|---:|---:|---:|
| Byte  offset | 0    | 1 | 2 | 3 | 
| Value         | 0x4 | 0x3 | 0x2 | 0x1 |

**Comment by dmxvlx** [comment]
For now I exactly know how represented string<->ipv4 in memory LOL
I thinked inversely: 1 - is lowest byte :)

sorry for my misunderstand :(
