### ISSUE TITLE
signal_set concurrency bug

### ISSUE THREAD

**Issue by vinipsmaker** [chriskohlhoff/asio#418]
I found a scenario where the `detail::signal_set_service` will fail to deliver the signal notification to the appropriate handlers. I wrote a small example illustrating the problem: https://gist.github.com/vinipsmaker/2ec8027f64f4bec4e2bb7fbc70d27fa8

If you remove the extra thread, it'll work.

**Comment by vinipsmaker** [comment]
My example had a race. However that was not the problem. My original app didn't have this race.

I could fix the race in the example... However I'll just close the issue anyway given it no longer appears on Boost.Asio 1.76. I'll just reopen it with an updated example if it shows up again.

**Comment by timblechmann** [comment]
makes me wonder if this is related: https://github.com/boostorg/asio/issues/403
