### ISSUE TITLE
/doc/asio/tutorial/tuttimer5/src.html why is it necessary "io.run();"

### ISSUE THREAD

**Issue by demucin** [chriskohlhoff/asio#426]
Hello

This is not issue for me.
I try to understand basics of Asio.
 ...
  asio::thread t(boost::bind(&asio::io_context::run, &io));
  io.run(); ???? why this line is necessary?
...

http://think-async.com/Asio/asio-1.13.0/doc/asio/tutorial/tuttimer5/src.html

Thanks.

**Comment by igsol** [comment]
> `asio::thread t(boost::bind(&asio::io_context::run, &io));`
The line creates the second thread `t` and runs `io.run()` in context of this thread.

> `io.run();` 
This line just runs the same `io` context in the initial first thread  concurrently with second thread.

The used in the example timer executes its handlers in both threads.
After timer stops all its work, both `io.run()` are returned control and threads are finished.
Notice the synchronization: first thread waits second one via `t.join()`.

**Comment by demucin** [comment]
I dont use Boost library.
I tried this:
<
std::thread t([&io]() { io.run(); });
std::thread t2([&io]() { io.run(); });
std::thread t3([&io]() { io.run(); });
...
t2.join();
t3.join();
...
>
displayed thread id in handlers:
<
std::this_thread::get_id()
>
handlers run in different threads.
It seems I misunderstood the eample.
