### ISSUE TITLE
add_certificate_authority silently drops bad certificates

### ISSUE THREAD

**Issue by ichernev** [chriskohlhoff/asio#429]
If you pass a malformed certificate to `boost::asio::ssl::context::add_certificate_authority`, the function does not set an `error_code`. For example try loading a cert not ending with `-----END CERTIFICATE-----`.

If the underlying SSL function does not do proper validation it might be necessary to parse the cert first to make sure it's good.

**Comment by chriskohlhoff** [comment]
Addressed in asio version 1.16.1.
