### ISSUE TITLE
Bug leading to false report of SSL error on async_shutdown

### ISSUE THREAD

**Issue by byllyfish** [chriskohlhoff/asio#43]
In asio/ssl/detail/io.hpp, the io_op class has a subtle bug that leads async_shutdown to falsely report a SHORT_READ error. I'm using the source code from the latest master (18 December 2014).

The following code is called when a deadline timer is cancelled, and the value of `bytes_transferred` is very large ~size_t(0). The `core_.input_` buffer is set to 17K of junk, and then this junk is passed as input to the `core_.engine_`.

```c++
        switch (want_)
        {
        case engine::want_input_and_retry:

          // Add received data to the engine's input.
          core_.input_ = asio::buffer(
              core_.input_buffer_, bytes_transferred);
          core_.input_ = core_.engine_.put_input(core_.input_);
```

Here is my fix:

```diff
diff --git a/asio/include/asio/ssl/detail/io.hpp b/asio/include/asio/ssl/detail/io.hpp
index 0916bea..dfc808b 100644
--- a/asio/include/asio/ssl/detail/io.hpp
+++ b/asio/include/asio/ssl/detail/io.hpp
@@ -220,8 +220,12 @@ public:
         }
 
         default:
-        if (bytes_transferred != ~std::size_t(0) && !ec_)
+        if (bytes_transferred == ~std::size_t(0)) {
+          // No data transferred when deadline_timer cancelled.
+          bytes_transferred = 0;
+        } else if (!ec_) { 
           ec_ = ec;
+        }
 
         switch (want_)
         {
```

Here is a more detailed trace of the handlers. In this setup, two connections (3 and 4) are connected via SSL, and there is no data "in the pipe". 

1. I invoke async_shutdown on connection 4. Connection 4 sends a "finished" SSL record. (ASIO handler 63 is unrelated to either connection)

    TCP_Connection::shutdown started {connid: 4}
    @asio|1418924613.982898|63*64|socket@0x7faf9a802ae0.async_send
    @asio|1418924613.983189|<63|

2. Connection 4 is done sending the "finished" SSL record. It awaits the reply.

    @asio|1418924613.983223|>64|ec=system:0,bytes_transferred=31
    @asio|1418924613.983264|64*67|deadline_timer@0x7faf9a802b10.async_wait
    @asio|1418924613.983286|<64|

3. Connection 3 receives the "finished" SSL record and starts its own async_shutdown.

    @asio|1418924613.984085|>48|ec=system:0,bytes_transferred=31
    asyncReadHeader callback {connid: 3} {msg: End of file, err: 2}
    TCP_Connection::shutdown started {connid: 3}
    @asio|1418924613.984378|48*70|socket@0x7faf998070e0.async_send
    @asio|1418924613.984457|<48|

4. Connection 3 is done sending the "finished" SSL record. Connection 3's side of the async_shutdown completes successfully.

    @asio|1418924613.986886|>70|ec=system:0,bytes_transferred=31
    TCP_Connection::shutdown handler called {connid: 3}
    @asio|1418924613.987017|70|socket@0x7faf998070e0.close
    @asio|1418924613.987087|<70|

5. Connection 4 receives the "finished" SSL record. It cancels its timer.

    @asio|1418924613.988099|>60|ec=system:0,bytes_transferred=31
    @asio|1418924613.988127|60|deadline_timer@0x7faf9a802b10.cancel
    asyncReadHeader callback {connid: 4} {msg: End of file, err: 2}
    @asio|1418924613.988321|<60|

6. Connection 4's timer handler is called. The large value of `bytes_transferred` leads to garbage data in the input buffer, causing the SHORT_READ shutdown error.

    @asio|1418924613.988514|>67|ec=asio.system:89
    TCP_Connection::shutdown handler called {connid: 4}
    TCP_Connection::shutdown result {connid: 4} {msg: SHORT_READ, err: 268435706}
    @asio|1418924613.988693|67|socket@0x7faf9a802ae0.close
    @asio|1418924613.988767|<67|

**Comment by chriskohlhoff** [comment]
Thanks for the detailed report and patch. Fixed in 57d5b76ece1be3fa23e6c0ad0f7b00aed3338c0a.
