### ISSUE TITLE
async_resolve use strand resulting in wrong derefs of outstanding_work_

### ISSUE THREAD

**Issue by jyxjrh** [chriskohlhoff/asio#460]
example:

#define ASIO_STANDALONE 1
#include "asio.hpp"
void test()
{
  using tcp = asio::ip::tcp;
  asio::io_context test_io;
  asio::io_context::strand test_strand(test_io);
  tcp::resolver r(test_io);
  tcp::endpoint ep(asio::ip::address::from_string("127.0.0.1"),
                   4567);
  auto guard = asio::make_work_guard(test_io);
  auto handler =
    [=](const asio::error_code& error,
        tcp::resolver::results_type results){
    std::cout << "do nothing" << std::endl;
  };

  r.async_resolve(ep, asio::bind_executor(test_strand, handler));
  test_io.run();
  std::cout << "never to here!\n";
}

master:
#459 
branches-1-12:
#458

**Comment by chriskohlhoff** [comment]
Addressed in asio version 1.16.1.
