### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [chriskohlhoff/asio#467]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [thread_info_base](https://github.com/chriskohlhoff/asio/blob/51274de46a30e05f989d363da46ae304889641be/asio/include/asio/detail/thread_info_base.hpp#L52 "Destructor for thread_info_base")
- [winrt_ssocket_service_base::close](https://github.com/chriskohlhoff/asio/blob/8087252a0c3c2f0baad96ddbd6554db17a846376/asio/include/asio/detail/impl/winrt_ssocket_service_base.ipp#L138 "winrt_ssocket_service_base::close function")

**Comment by chriskohlhoff** [comment]
Addressed in asio version 1.16.1.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/chriskohlhoff/asio/commit/027a5249071236d3e8ea29f1c4267a5b647dfde9 "Deletion of two unnecessary checks").
