### ISSUE TITLE
Signal handler example won't compile

### ISSUE THREAD

**Issue by ruipacheco** [chriskohlhoff/asio#47]
I'm currently trying to add signal handling to an application that uses Asio without Boost. I tried to add a private method as my signal handler as explained at the bottom of [this](http://think-async.com/Asio/asio-1.10.2/doc/asio/reference/SignalHandler.html) page but I get the following error when compiling:

`error: no member named 'error' in namespace 'asio::placeholders'`

I've checked the namespace and error does seem to be there although wrapped in an #if:

`#if defined(GENERATING_DOCUMENTATION)`

Also, I'm using std::bind instead of boost::bind.

**Comment by ColinGilbert** [comment]
@ruipacheco
Did you find a solution to this problem?

**Comment by ruipacheco** [comment]
Nope, haven't checked this yet. Working on other parts of the project first.

**Comment by ruipacheco** [comment]
@ColinGilbert - try this: https://stackoverflow.com/questions/28486347/cant-use-asioplaceholderserror-in-non-boost-version-of-asio

**Comment by chriskohlhoff** [comment]
Commit 722f7e2be05a51c69644662ec514d6149b2b7ef8 adds examples to the documentation to show that `std::placeholders::_N` should be used with `std::bind`.
