### ISSUE TITLE
Trouble in detect accept event using tcp::acceptor::async_wait().

### ISSUE THREAD

**Issue by haquocviet** [chriskohlhoff/asio#478]
In order to make a listening socket accept new connection, I know how simple asyn_accept() is, but for some reasons, I have to use reactor mode with native socketNum in my application.

I follow the example described in basic_socket_acceptor.hpp. 

```
* @par Example
   * @code
   * void wait_handler(const boost::system::error_code& error)
   * {
   *   if (!error)
   *   {
   *     // Wait succeeded.
   *   }
   * }
   *
   * ...
   *
   * boost::asio::ip::tcp::acceptor acceptor(my_context);
   * ...
   * acceptor.async_wait(
   *     boost::asio::ip::tcp::acceptor::wait_read,
   *     wait_handler);
   * @endcode
   */
   
```

In Windows I do like this:

```
//	Elsewhere
int socketNum = createSocket(port, SOCK_STREAM, ..);

boost::system::error_code ec {};
acceptor_.assign(ip::tcp::v4(), socketNum, ec);
if (!ec) {
	acceptor_.non_blocking(true, ec);
	do_accept();
}

void do_accept() {
	acceptor_.async_wait(
		boost::asio::ip::tcp::acceptor::wait_read,
		[this](const boost::system::error_code& ec) {
			if (!ec) {
				// ready to accept(..)
				
				do_accept();
			}
			else {
				Log::error("The listener got an error ({}) {}", ec.value(), ec.message());
			}
		});
}

```
The async_wait() almost returns immediately with error= 10057.

Can you tell me what's wrong in my code?. I wondering if asio handles accept event like
the way 'select()' does.

**Comment by halx99** [comment]
Try write data to a incomplete TCP will trigger error: 10057
see refer: https://github.com/yasio/yasio/issues/22

**Comment by haquocviet** [comment]
What is your point when you refer the issue here to the irrelevant post?

Anyway I had given up the way of combination asio's io_context to native sockets. It is unnecessary complicated and unstable.

**Comment by lingyphone** [comment]
I have the same issue here with asio 1.30.2. Any new update?
