### ISSUE TITLE
How starvation & thundering herd are solved in boost.asio

### ISSUE THREAD

**Issue by ljhack** [chriskohlhoff/asio#491]
Not an issue. I'm wondering how problems like starvation & thundering herd are solved/avoided in boost.asio in Linux when epoll is used. Thanks.

**Comment by ona993** [comment]
Nobody knows that. It's magic.

**Comment by chriskohlhoff** [comment]
* Edge-trigged epoll
* Even if multiple threads `run` an `io_context`, only one thread calls `epoll_wait`

**Comment by mabrarov** [comment]
Per my experience (tests were made ~4 years ago, so old version of Boost.Asio was used) the most performant approach of using Asio in Linux (i.e. with epoll) is io_service (io_context) per CPU approach. Though this approach requires distribution of incoming connections among all instances of io_service... TS my find interesting this article - https://blog.cloudflare.com/the-sad-state-of-linux-socket-balancing.
