### ISSUE TITLE
available() returns 0, but there is no error and the connection was not closed on the other end

### ISSUE THREAD

**Issue by chreniuc** [chriskohlhoff/asio#502]
I'm using boost 1.71.0 and I noticed something strange.

The documentation for the `available()` method states that it returns: ` The number of bytes that may be read without blocking, or 0 if an error occurs. `.

Our scenario looks like this, we have a tcp socket on which we call `async_wait`, waiting a read event. When `async_wait`'s completion handler is called, it means that there are some bytes to be read or there has been an error. We call `available` to allocate a buffer and then we call `async_read` with that buffer 

We've noticed that, sometimes when there is a lot of data transferred, `available()` returns 0 bytes and we were closing the connection, because we thought there has been an error(just like the documentation states) or the connection was closed on the other end(some users from [stack-overflow](https://stackoverflow.com/questions/2416944/can-read-function-on-a-connected-socket-return-zero-bytes/2416979#2416979) were saying that if you get 0, it means that this is a normal disconnect and the socket should be closed). But after an investigation we've noticed that the connection on the other end was not closed, and we've commented the code that calls `close` on the socket when `available` returns 0 and everything works fine(we can still send and receive data). We've noticed that `available()` returns 0 when there is a lot of networking traffic.

Our code(simplified) looks like this:

```c++
// Tcp has this type:
::boost::asio::basic_stream_socket<boost::asio::ip::tcp,
    boost::asio::strand<boost::asio::io_context::executor_type>> tcp;


void tcp_interface::do_tcp_wait_read( )
{
  tcp->async_wait( boost::asio::ip::tcp::socket::wait_read,
    std::bind( &tcp_interface::on_tcp_wait_read, this,
      std::placeholders::_1 ) );
}

void tcp_interface::on_tcp_wait_read(boost::system::error_code ec )
{
  if ( ec )
  {
    tcp->close();
    return;
  }
  boost::system::error_code error_code;
  size_t bytes_available = tcp->available( error_code );

  if ( error_code )
  {
    // log
    return;
  }
  if ( bytes_available == 0 )
  {
    // tcp->close( );
    do_tcp_wait_read( );
    return;
  }
  ::boost::asio::post( tcp->get_executor(),
    std::bind( &tcp_interface::do_tcp_read_impl, this, size ) );
}

void tcp_interface::do_tcp_read_impl( size_t size )
{
  std::shared_ptr<std::string> message_ptr = std::make_shared<std::string>();
  // Temporary implementation of buffer
  message_ptr->resize( size );
 tcp->async_receive( boost::asio::buffer( *message_ptr ),
    std::bind( &tcp_interface::on_tcp_read, this, message_ptr,
      std::placeholders::_1, std::placeholders::_2 ) );
}
```

Is this a mistake in the documentation of the `available` method?

Is it a false-positive? If that's so, how can we detect when `available` returns 0 because of an error and when it returns `0` when it shouldn't?

Is it ok to avoid closing the connection when `available` returns 0?

Thanks :)

**Comment by chreniuc** [comment]
Using the method from above(not calling close), introduces another problem.

We've noticed some high cpu ussage lately, and when we investigated, we've noticed that now we can't detect when  the other end closes. Because, when that happens, `async_wait` with `wait_read` event, returns 0 bytes available, and we end up in an infinite loop: `do_tcp_wait_read -> on_tcp_wait_read -> do_tcp_wait_read -> on_tcp_wait_read -> etc..`

So, we've noticed that there is another event, that can be used for async_wait: `wait_error` and we though that this might detect that case when the other end closes the connection. But it didn't.

Another thing we've tried, is to call `do_tcp_read_impl` when in `on_tcp_wait_read` we have 0 bytes to be read, and we thought that we might get an error, that might notify us that the other end has been closed, but.. again, we received no error, and it got to another infinite loop: `do_tcp_wait_read -> on_tcp_wait_read -> do_tcp_read_impl -> on_tcp_read -> do_tcp_wait_read -> on_tcp_wait_read -> do_tcp_read_impl ->etc..`

To complete the code, I've added this:


```c++
void tcp_interface::on_tcp_read( const std::shared_ptr<std::string>& message_ptr, 
 boost::system::error_code ec, size_t bytes_transferred )
{
  if(ec)
  {
   // do something or close
  }
  
 // process the message

 // continue the reading loop
 do_tcp_wait_read();
}
```

We still do not understand why this happens. How can we know if the other end closed the connection? Because if we use the number of available bytes, that is wrong, you can see that in the first post. When there is a lot of activity, we end up with `on_tcp_wait_read` called when `tcp->available` returns 0.

___

As a temporary fix, we checked in the completion handler of async_receive, if we have read 0 bytes. And if that's so, we closed the connection. When we will do some stress tests again, just like the one from the first post, we will keep an eye on this(to see if we close the connections because we wanted to read 0 bytes, but that case was just a false-positive like in the first post).


___

LE:

The problem was that we were calling `async_receive` with a string that had 0 chars. So we needed to call it with at least 1 byte. And if we did that, we ended up receiving the `eof` error in the read completion handler. The working code looks like this:


```cpp
void tcp_interface::on_tcp_wait_read(boost::system::error_code ec )
{
  if ( ec )
  {
    tcp->close();
    return;
  }
  boost::system::error_code error_code;
  size_t bytes_available = tcp->available( error_code );

  if ( error_code )
  {
    // log
    return;
  }
  if ( bytes_available == 0 )
  {
    do_tcp_read_impl(1); // at least one byte. This will end up resulting in an error in the async read, if it can't read.
    return;
  }
  ::boost::asio::post( tcp->get_executor(),
    std::bind( &tcp_interface::do_tcp_read_impl, this, size ) );
}
```

The `on_tcp_read` remains the same, with this being the only change:

```cpp
  if ( ec )
  {
    tcp->close();
    return;
  }
```

I will close this issue. We still haven't stress tested this, but when we do, if we end up having problems, we will write here.

**Comment by autoantwort** [comment]
Imo this is a workaround and not a fix, so you can open it again (we have the similar problem)
