### ISSUE TITLE
Using ASIO with Unreal Engine prints "Do not compile Asio library source with ASIO_HEADER_ONLY defined"

### ISSUE THREAD

**Issue by Bunkerbewohner** [chriskohlhoff/asio#509]
Hi!

I'm trying to ASIO as a header-only lib in Unreal. I copied the contents of the "Include" folder (asio and asio.hpp) into my path and include like this:

```
#define ASIO_HEADER_ONLY
#define ASIO_STANDALONE
#include <asio.hpp>
```

Compiling fails with "CompilerResultsLog:   This file is deprecated. Please #include <asio/impl/src.hpp> instead." and "Source\...\ThirdParty\asio/impl/src.hpp(19): fatal error C1189: #error:  Do not compile Asio library source with ASIO_HEADER_ONLY defined".

I don't understand this error. ASIO is supposed to be a header-only library, but this error message seems to contradict that. Can someone explain what's going on?

Thanks in advance!

**Comment by youngwolf-project** [comment]
asio is header-only even macro ASIO_HEADER_ONLY not been defined.
Try not defining the macro.

**Comment by Bunkerbewohner** [comment]
Thanks @youngwolf-project ! But even if I don't define ASIO_HEADER_ONLY I get the same error. :-(

![grafik](https://user-images.githubusercontent.com/500529/87818162-6d0eda80-c86a-11ea-9add-e351ef31861c.png)

The error message about "this file is deprecated is also confusing" since that one also appears even if I use the import <asio/impl/src.hpp> like the error message says. I'm confused.

**Comment by Bunkerbewohner** [comment]
Figured part of it out: The Unreal Engine's build system included all files (e.g. impl/src.cpp) even though I didn't explicitly include them myself. To get it to compile I deleted those files.
