### ISSUE TITLE
Compile errors when using MSVS with clang-cl toolset

### ISSUE THREAD

**Issue by Eddie-cz** [chriskohlhoff/asio#511]
When using Microsoft Visual Studio with clang-cl toolset, it's not possible to compile current ASIO upstream.
Problem is with preprocessor ifdefs  like those below, under mentioned environment, BOTH are defined (_MSC_VER and \_\_clang\_\_).
Would be nice to fix in Boost 1.74.0, as current RC1 is affected by this issue.

#if defined(_MSC_VER) // Visual C++ wants the type to be qualified.
#elif !defined(\_\_clang\_\_) // Clang crashes if noexcept is used here.
#endif // !defined(\_\_clang\_\_)

**Comment by abique** [comment]
I confirm the issue. ASIO does not compile with clang-cl 10.0.0

**Comment by abique** [comment]
Do you know how to update app veyor to check visual studio 2019 + clang cl?

**Comment by abique** [comment]
I've created a ticket on llvm's bug tracker: https://bugs.llvm.org/show_bug.cgi?id=47011

**Comment by abique** [comment]
It seems that some fixes have already be done: e8459ab3f4986b8c5f69f828a4bfab9100babfb9
I'll check them later.

**Comment by abique** [comment]
I confirm that the change fixes this issue.
You can close the ticket.

**Comment by chriskohlhoff** [comment]
Fixed in asio 1.18.0.
