### ISSUE TITLE
basic_socket_acceptor's move constructor lacks ASIO_NOEXCEPT?

### ISSUE THREAD

**Issue by b-spencer** [chriskohlhoff/asio#514]
The move constructor of [`basic_socket_acceptor`](https://github.com/chriskohlhoff/asio/blob/2442078/asio/include/asio/basic_socket_acceptor.hpp#L356) is not marked `ASIO_NOEXCEPT`.  The move constructor of [`basic_socket`](https://github.com/chriskohlhoff/asio/blob/2442078/asio/include/asio/basic_socket.hpp#L297), [`basic_datagram_socket`](https://github.com/chriskohlhoff/asio/blob/2442078/asio/include/asio/basic_datagram_socket.hpp#L251), and [`basic_stream_socket`](https://github.com/chriskohlhoff/asio/blob/2442078/asio/include/asio/basic_stream_socket.hpp#L256) _are_ `ASIO_NOEXCEPT`.

Is there something special that prevents the acceptor move constructor from being noexcept, or is it just an oversight?

**Comment by chriskohlhoff** [comment]
Fixed in asio 1.18.0.
