### ISSUE TITLE
asio::ip::network_v4 does not read input correctly

### ISSUE THREAD

**Issue by petten** [chriskohlhoff/asio#524]
Code:
```
    auto net = make_network_v4("169.254/16");
    cout << net << endl;
```

Output (vs/2019 on win/10), which is wrong:
```
169.0.0.254/16
```

Expected (or the same as the input):
```
169.254.0.0/16
```

See: https://pubs.opengroup.org/onlinepubs/009695399/functions/inet_addr.html

**Comment by bbrice** [comment]
Hi @petten.  Unfortuantely, I think you may be incorrect on the understanding of `inet_addr`.  Here's a small snippet compiled on Linux (POSIX) with GCC:

    in_addr_t addr = ntohl(inet_addr("169.254"));
    printf("OK -- %d.%d.%d.%d\n",
        (addr & 0xff000000) >> 24,
        (addr & 0x00ff0000) >> 16,
        (addr & 0x0000ff00) >>  8,
        (addr & 0x000000ff) >>  0);

The output:

    OK -- 169.0.0.254

Testing with Visual Studio on a Windows 10 system as well, `inet_addr` behaves the same way:

    unsigned long addr = ntohl(inet_addr("169.254"));
    printf("OK -- %d.%d.%d.%d\n",
        (addr & 0xff000000) >> 24,
        (addr & 0x00ff0000) >> 16,
        (addr & 0x0000ff00) >>  8,
        (addr & 0x000000ff) >>  0);

The output:

    OK -- 169.0.0.254

According to the POSIX documentation of `inet_addr`, with the `a.b` format, the `b` part should be treated as the value of a 24-bit quantity.  The value in these examples is 254.  If you wanted it as `169.254.0.0`, then you'd have to give `169.16646144`.  I hope this makes sense...

**Comment by petten** [comment]
OK, I read the doc wrong. Sorry.

I got "169.254/16" from a Macbook I use. It's specified as one in a list of comma-delimited domain/host names/addresses and subnets, for which configured proxy shall be bypassed. That clearly means "169.254.0.0/16" as any address in it is a so-called "Automatic Private IP address."

I'm dropping the issue.
