### ISSUE TITLE
ssl::stream strictly breaks asio AsyncReadStream preconditions of underlying stream on zero-sized write

### ISSUE THREAD

**Issue by madmongo1** [chriskohlhoff/asio#540]
Hi Chris, 

This little gem came up a few days ago: https://github.com/boostorg/beast/issues/2065

beast::tcp_stream has code in a debug build to detect a precondition violation. The problem is with in these two lines:

```
        sslStream.async_read_some(asio::buffer(buffer), [](auto ec, auto size) {});
        sslStream.async_write_some(asio::buffer("", 0), [](auto ec, auto size) {});
```

The second line is a write. However, the underlying `io_op` detects that the write is zero-size and seeks to short-circuit completion. In order to do so, it executes a zero-sized _read_ against the underlying stream. Our implementation sees that, notices that there is already an outstanding read in progress and asserts.

We have a few options:

1. Code for the detection of the zero-sized write and avoid the precondition check in this case.
2. Remove the precondition check and hope for the best
3. Wait for an upstream fix

The initiating call that triggers the violation is at:

`boost/asio/ssl/detail/io.hpp:217` : 

```
        default:

          // The SSL operation is done and we can invoke the handler, but we
          // have to keep in mind that this function might be being called from
          // the async operation's initiating function. In this case we're not
          // allowed to call the handler directly. Instead, issue a zero-sized
          // read so the handler runs "as-if" posted using io_context::post().
          if (start)
          {
            next_layer_.async_read_some(                                // <<< ===== HERE =====
                boost::asio::buffer(core_.input_buffer_, 0),
                BOOST_ASIO_MOVE_CAST(io_op)(*this));

            // Yield control until asynchronous operation completes. Control
            // resumes at the "default:" label below.
            return;
          }
          else
          {
            // Continue on to run handler directly.
            break;
          }
        }
```

Your sage advice is sought.

R

**Comment by chriskohlhoff** [comment]
As zero-sized reads and writes are specifically called out as immediately-completing no-ops in the type requirements, my intent was that they should be callable at any time. That would mean your precondition should not track these as in-progress, nor prevent them if a non-zero-sized operations is already in progress.

**Comment by madmongo1** [comment]
Huh! It's amazing what you can miss when you don't fully read the documentation.

My apologies.

**Comment by TheStormN** [comment]
Close this issue?

**Comment by madmongo1** [comment]
Yes. Thank you.
