### ISSUE TITLE
Tons of ASIO unit tests fail on Android

### ISSUE THREAD

**Issue by ned14** [chriskohlhoff/asio#55]
Not sure if you've seen this: http://www.boost.org/development/tests/develop/developer/asio.html

He may have misconfigured the build of course.

Niall

**Comment by chriskohlhoff** [comment]
Looks like a non-Android-specific problem with the test framework. Have committed a workaround and will see what happens.

**Comment by ned14** [comment]
He says he'll upload results once per week from now on, so it'll be a while before we see what changes. Thanks for looking into the problem.
