### ISSUE TITLE
Wrong documentation about Windows specific implementation details.

### ISSUE THREAD

**Issue by TheStormN** [chriskohlhoff/asio#558]
As can be seen here: https://think-async.com/Asio/asio-1.18.0/doc/asio/overview/implementation.html

It's about `Demultiplexing mechanism:` which mentions that `select()` is used on Windows along with additional thread during asynchronous connect. From what I see in the sources this is not true unless `BOOST_ASIO_DISABLE_CONNECTEX` is defined during build.

Please fix that part, because it suggest that the Windows implementation is inferior when it comes to asynchronous connect which seems to be untrue.

**Comment by chriskohlhoff** [comment]
This was fixed in asio 1.18.1 / boost 1.75.

**Comment by TheStormN** [comment]
@chriskohlhoff I'm looking at the 1.18.1 docs and I don't see a change regarding that...
https://think-async.com/Asio/asio-1.18.1/doc/asio/overview/implementation.html

**Comment by chriskohlhoff** [comment]
> * An additional thread per io_context may be used for select demultiplexing. This thread is created on the first call to:
>   * A socket async_wait() function, except when using wait_read on a stream-oriented socket. (For wait_read on a stream-oriented socket, the overlapped I/O operation WSARecv is used and no additional thread is required.)
>   * A socket async_connect() operation, if the overlapped I/O operation ConnectEx is unavailable. (On recent versions of Windows, ConnectEx is used and no additional thread is required.)

**Comment by TheStormN** [comment]
@chriskohlhoff It's still confusing, because the top lines start with
```
Demultiplexing mechanism:

Uses overlapped I/O and I/O completion ports for all asynchronous socket operations except for asynchronous connect.
Uses select for emulating asynchronous connect.
```
