### ISSUE TITLE
Boost 1.58 beta 1 has old ASIO 1.10.5 instead of newer 1.11

### ISSUE THREAD

**Issue by ned14** [chriskohlhoff/asio#56]
I assume this is an oversight? Anyway, the merge window will close soon!

**Comment by chriskohlhoff** [comment]
Boost is going to stay on the stable 1.10.x branch for the moment. However, I've merged some important bug fixes across to the boost develop branch, which I plan to include in boost 1.58.

There are still new API changes to come on the 1.11.x development branch.

**Comment by ned14** [comment]
Thanks for letting me know.
