### ISSUE TITLE
Strand blocked after co_spawn is co_await-ed

### ISSUE THREAD

**Issue by MiSo1289** [chriskohlhoff/asio#563]
I've been experimenting with strands and coroutines, and noticed weird behaviour. When I spawn a coroutine on one strand, and inside it spawn another coroutine on a second strand, and await on it, when the control is returned to the outer coroutine, both strands are blocked. Is this intended behaviour? If so, how do I work around this?

Following code demonstrates the issue, tested with boost.asio, boost version 1.74.0, gcc version 10.2.0 on linux.

```c++
#include <thread>
#include <chrono>
#include <iostream>

#include <boost/asio.hpp>

namespace asio = boost::asio;
using namespace std::chrono_literals;

int main() {
    auto ioc = asio::io_context{};
    // Create two strands
    auto s1 = asio::make_strand(ioc);
    auto s2 = asio::make_strand(ioc);
    // Prevent the io context from stopping
    auto wg = asio::make_work_guard(ioc);
    // Over-provision threads just in case
    auto w1 = std::jthread{[&]() { ioc.run(); }};
    auto w2 = std::jthread{[&]() { ioc.run(); }};
    auto w3 = std::jthread{[&]() { ioc.run(); }};
    auto w4 = std::jthread{[&]() { ioc.run(); }};
    auto w5 = std::jthread{[&]() { ioc.run(); }};

    asio::co_spawn(s1, [&]() -> asio::awaitable<void> {
        std::cout << "a" << std::endl;
        co_await asio::co_spawn(s2, []() -> asio::awaitable<void> {
            // Works as intended
            // s2 is blocked, s1 is free (b will print)
            std::this_thread::sleep_for(2s);
            co_return;
        }, asio::use_awaitable);
        // Expected: s1 is blocked, s2 is free (d will print, e will wait 5s)
        // Reality: both s1 and s2 are blocked (after 5s, d and e print at the same time).
        // Why?
        std::cout << "c" << std::endl;
        std::this_thread::sleep_for(5s);
    }, asio::detached);

    std::this_thread::sleep_for(1s);

    asio::co_spawn(s1, []() -> asio::awaitable<void> {
        std::cout << "b" << std::endl;
        co_return;
    }, asio::detached);

    std::this_thread::sleep_for(2s);

    asio::co_spawn(s2, []() -> asio::awaitable<void> {
        std::cout << "d" << std::endl;
        co_return;
    }, asio::detached);

    asio::co_spawn(s1, []() -> asio::awaitable<void> {
        std::cout << "e" << std::endl;
        co_return;
    }, asio::detached);

    std::this_thread::sleep_for(10s);
    ioc.stop();
}

```

Expected behaviour:

```
t__0_1_2_3_4_5_6_7
s1 a_b_c_________e
s2 ______d________
``````

Actual behaviour:
```
t__0_1_2_3_4_5_6_7
s1 a_b_c_________e
s2 ______________d
```

**Comment by fairlyblank** [comment]
Hi @MiSo1289 , I think I have encountered same issues, did you have updates in the meanwhile?

Another behaviour also confused me, why 'b' is printed right after 'a'? 
I thought s1 was occupied by first 7 seconds, 'b' should been printed at 7s, cause when awaiting s2 for 2 seconds, s1 was also not finished. That behaviour I thought is consistent with strand used in callback way.
Am I misunderstanding something?

**Comment by MiSo1289** [comment]
Hi @fairlyblank , I understand now what was going on, and I can answer your problem as well.

First, why is 'b' printed right after 'a'?
Well, s1 is not occupied for 7 seconds continuously. If you spawn a coroutine on a strand, and co_await something, the strand becomes 'unlocked' - e.g. strands are only blocked between co_await's. This is because strands have no idea of the concept of coroutines: like every other executor, they only execute functions. A coroutine can be thought of as made-up of many functions, between each co_await expression. If you want to prevent two coroutines from overlapping, you need a more high-level synchronization primitive. I recommend you check out my library [asiochan](https://github.com/MiSo1289/asiochan), which allows multiple coroutines to synchronize by sending messages. It can also be used fairly easily to implement an 'async mutex', which makes preventing coroutines from overlapping even easier. If you are interested, I will send you the code or add it to asiochan.

Second, the original problem: why were both strands blocked by a single coroutine at the end?
This is simply because of the ugly misuse of coroutines for blocking tasks. When the strand executor sees that a task can be invoked immediately (because we are on a thread corresponding to the underlying executor, and the strand is not blocked currently), it does so (unless it is tagged with the blocking.never property). This is done to minimize the number of 'context switches'. Here, the co_return of the inner coroutine ends up invoking the strand executor of the outer coroutine, and the s1 strand decides that this can be done synchronously (the inner coroutine ends up at the bottom of the call-stack, and the outer on the top, inverting the control flow). If we would co_await an ASIO timer instead of a blocking sleep, both strands would get unblocked at the co_await, and after the timeout, only the s1 strand would be blocked. 

This just goes to illustrate that calling blocking code with coroutines is a bad idea.

**Comment by fairlyblank** [comment]
Hi @MiSo1289 , sorry for late reply.

> Hi @fairlyblank , I understand now what was going on, and I can answer your problem as well.
> 
> First, why is 'b' printed right after 'a'?
> Well, s1 is not occupied for 7 seconds continuously. If you spawn a coroutine on a strand, and co_await something, the strand becomes 'unlocked' - e.g. strands are only blocked between co_await's. This is because strands have no idea of the concept of coroutines: like every other executor, they only execute functions. 

OK,  I understand strand much better now. Strand donot own something like 'coroutine context'.
 
> A coroutine can be thought of as made-up of many functions, between each co_await expression. If you want to prevent two coroutines from overlapping, you need a more high-level synchronization primitive. I recommend you check out my library [asiochan](https://github.com/MiSo1289/asiochan), which allows multiple coroutines to synchronize by sending messages. It can also be used fairly easily to implement an 'async mutex', which makes preventing coroutines from overlapping even easier. If you are interested, I will send you the code or add it to asiochan.

I will check asiochan in couple days. Sample codes would be appreciated, thanks.

> 
> Second, the original problem: why were both strands blocked by a single coroutine at the end?
> This is simply because of the ugly misuse of coroutines for blocking tasks. When the strand executor sees that a task can be invoked immediately (because we are on a thread corresponding to the underlying executor, and the strand is not blocked currently), it does so (unless it is tagged with the blocking.never property). This is done to minimize the number of 'context switches'. Here, the co_return of the inner coroutine ends up invoking the strand executor of the outer coroutine, and the s1 strand decides that this can be done synchronously (the inner coroutine ends up at the bottom of the call-stack, and the outer on the top, inverting the control flow). If we would co_await an ASIO timer instead of a blocking sleep, both strands would get unblocked at the co_await, and after the timeout, only the s1 strand would be blocked.
> 

I think I partially understand it. Inner coroutine resume its 'continuation' when co_return, but before inner coroutine stack release, that means s2 is still occupied. Then outter coroutine uses thread sleep, both s1 and s2 blocked.
Right, coroutine await primitive should be used here, instead of thread synchronous primitive. 
Is this should be a c++20 coroutine issue, or an asio strand issue?

> This just goes to illustrate that calling blocking code with coroutines is a bad idea.
