### ISSUE TITLE
C++20 coroutines are not supported on Visual Studio 16.8 (error C2039: 'awaitable': is not a member of 'boost::asio')

### ISSUE THREAD

**Issue by ev-zhuravlev** [chriskohlhoff/asio#576]
VS 16.8 now supports C++20 coroutines which are different from <experimental/coroutine>.  To use them /std:c++latest switch without /await should be used. (See https://aka.ms/cpp/20coro).
But when compiling with this switches I'm getting "error C2039: 'awaitable': is not a member of 'boost::asio'" error.
Boost version is 1.74. 
VS version is 16.8.1.

**Comment by chriskohlhoff** [comment]
Fixed in asio 1.18.1 / boost 1.75.
