### ISSUE TITLE
boost 1.74 boost::asio::ip::tcp::resolver constructor not taking boost::asio::executor

### ISSUE THREAD

**Issue by neel** [chriskohlhoff/asio#583]
Just updated to boost 1.74. Some old code suddenly stopped working. `boost::asio::ip::tcp::resolver` constructor is not taking `boost::asio::executor`. Was that an intended change ? What is the backward compatible way of constructing the resolver ?

**Comment by neel** [comment]
Currently using this works.

```
#if BOOST_VERSION >= 107400
    using executor_type = boost::asio::any_io_executor;
#else
    using executor_type = boost::asio::executor;
#endif
```

**Comment by chriskohlhoff** [comment]
Relevant changes are described here:
* https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/std_executors.html
* https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/using.html#boost_asio.using.macros
