### ISSUE TITLE
boost::asio::detail::dummy_return for void is not a template specialization (MS VC++ specific)

### ISSUE THREAD

**Issue by h-bex** [chriskohlhoff/asio#585]
- asio as part of boost-1_75
- Compiling with Microsoft VC++: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29335 for x64 (debug and release)

Looking inside the code of `asio/impl/use_awaitable.hpp` if find the following code, which leads to an error at link time of my code with boost-1.75 (multiply defined symbols of dummy_return<void>):
```
#if defined(_MSC_VER)
template <typename T>
T dummy_return()
// ...

template <>
void dummy_return()
{
}
#endif // defined(_MSC_VER)
```
The problem is the `template <>void dummy_return(){...}` is not only a specialization but also a definition an explicit instantiation. The following is a correction of the code which prevents duplicate symbols:
```
#if defined(_MSC_VER)
// ...
template <>
inline void dummy_return()
{
}
#endif // defined(_MSC_VER)
```

**Comment by chriskohlhoff** [comment]
Fixed in 7377f941cc9831c4c3cba1e71d3bc29bddf1a700.
