### ISSUE TITLE
experimental::as_single doesn't compile with BOOST_ASIO_NO_DEPRECATED

### ISSUE THREAD

**Issue by ytimenkov** [chriskohlhoff/asio#589]
I get errors in `error_if_hook_is_defined` for `asio_handler_allocate` and `asio_handler_invoke`.

The only difference from the example is that I explicitly pass `experimental::as_single_t<use_awaitable_t<>>{}` as a completion instead of using a default.

When I guarded those definitions with `#if !defined(BOOST_ASIO_NO_DEPRECATED)` my code compiled.

I'm using asio from boost 1.75.0

**Comment by chriskohlhoff** [comment]
Fixed in 180bc40ea03ae95bf45dd6890e979ea9ffef54e8.
