### ISSUE TITLE
Standalone Asio `deadline_timer` depends on `boost::posix_time`

### ISSUE THREAD

**Issue by kenba** [chriskohlhoff/asio#59]
In attempting to port [via-httplib](https://github.com/kenba/via-httplib) to use standalone asio I was unable to remove all dependencies on the boost library because of `deadline_timer` and `basic_deadline_timer`:

    typedef basic_deadline_timer< boost::posix_time::ptime > deadline_timer;
    
I expected to be able to use the following instead:

    typedef basic_deadline_timer< std::chrono::ptime > deadline_timer;

However, this would not compile because Standalone Asio `basic_deadline_timer.hpp` tests the macro `ASIO_HAS_BOOST_DATE_TIME` just after the include guards...

**Comment by jpetso** [comment]
Can you use steady_timer instead, which works on `std::chrono` types?

**Comment by chriskohlhoff** [comment]
The basic_waitable_timer<> template is the chrono-compatible replacement for `deadline_timer`. Please see http://think-async.com/Asio/asio-1.10.6/doc/asio/overview/cpp2011/chrono.html.
