### ISSUE TITLE
Update Services examples to use basic_io_object class

### ISSUE THREAD

**Issue by merovingien** [chriskohlhoff/asio#67]
Hi,

I am trying to create a custom io service, and I am looking for best practice examples.

The "Services" example implements an io service for logging, but it does not use the basic_io_object class as base class for the I/O object (class basic_logger). Is there a good reason to not use this base class ?

Thank!

**Comment by chriskohlhoff** [comment]
The `basic_io_service` class is not part of the c++ standards proposal based on asio. It might eventually (in the very long term) be deprecated and disappear. It's really only a helper, and you don't strictly need it to implement I/O objects, so don't use it if you want to stay forwardly compatible.
