### ISSUE TITLE
compile error about std::move

### ISSUE THREAD

**Issue by huyuguang** [chriskohlhoff/asio#69]
MSVC 2015 RC
asio 1.10.6

```
Following code is ok:
  auto data = std::make_unique<std::string>("abc");
  auto buffer = asio::buffer(data->c_str(), data->size());
  std::shared_ptr<std::string> data2 = std::move(data);
  asio::async_write(s, buffer,
    [data2](const asio::error_code&,  size_t) { ...  });

But the following code can not be compiled:
  auto data = std::make_unique<std::string>("abc");
  auto buffer = asio::buffer(data->c_str(), data->size());
  // data2 is unique_ptr<string>
  asio::async_write(s, buffer,
    [data2 = std::move(data)](const asio::error_code& error,
      size_t byte_transferred) { ... });
```
Why I can not capture a unique_ptr here?
It's seems the handler object must be copyable?

**Comment by huyuguang** [comment]
I found something in document:
http://www.boost.org/doc/libs/1_58_0/doc/html/boost_asio/overview/cpp2011/move_handlers.html

"As an optimisation, user-defined completion handlers may provide move constructors, and Boost.Asio's implementation will use a handler's move constructor in preference to its copy constructor. In certain circumstances, Boost.Asio may be able to eliminate all calls to a handler's copy constructor. However, handler types are still required to be copy constructible."

How can I remove the "handler types are still required to be copy constructible" since asio always move but not copy the handlers in c++ 11 compiler?

I can use shared_ptr in lambda capture to workaround, but I do not know how can I convert the shared_ptr to unique_ptr (even the shared_ptr.unique() return true) if I want to call a do_something(std::unique_ptr<>) in lambda.

**Comment by huyuguang** [comment]
Now I wrapped unique_ptr<T> to shared_ptr<unique_ptr<T>> and capture the shared_ptr<unique_ptr<T>>. It works, but really ugly.

Hope the asio handler can remove the copyable requirement in c++14 compiler.

**Comment by chriskohlhoff** [comment]
Move-only handlers are supported on the master branch.

In older versions copyability is enforced because there are circumstances where copying of handlers is required by the implementation (e.g. when you use a strand), even if in many typical cases Asio is able to avoid it.

**Comment by marton78** [comment]
Or, in the meantime use [this workaround](http://stackoverflow.com/a/22891509/728847)
