### ISSUE TITLE
BOOST_WORKAROUND macro in buffer.hpp undefined

### ISSUE THREAD

**Issue by theSundayProgrammer** [chriskohlhoff/asio#71]
Line 52 of buffer.hpp generates an error:

if BOOST_WORKAROUND(__BORLANDC__, BOOST_TESTED_AT(0x582)) \
    || BOOST_WORKAROUND(__SUNPRO_CC, BOOST_TESTED_AT(0x590))
  define ASIO_ENABLE_ARRAY_BUFFER_WORKAROUND
 endif // BOOST_WORKAROUND(__BORLANDC__, BOOST_TESTED_AT(0x582))
        // || BOOST_WORKAROUND(__SUNPRO_CC, BOOST_TESTED_AT(0x590))

**Comment by chriskohlhoff** [comment]
Please provide a test case for the issue, including the compiler options you are using, and the errors you see.

**Comment by theSundayProgrammer** [comment]
Apologise for the inconvenience. I should have created a test case before I created the issue. My mistake.
