### ISSUE TITLE
asio::ssl::stream accesses deallocated memory if deleted with pending asynchronous read

### ISSUE THREAD

**Issue by Andrepuel** [chriskohlhoff/asio#77]
I've done some research and did not find if it is not allowed to delete an `asio::ssl::stream` object that has pending asynchronous operation. `asio::ip::tcp::socket` will just invoke any callback with operation aborted error and thats what I expected from the `asio::ssl::stream` object.

Using the following code I can reproduce a segmentation fault in `asio::ssl::stream` if I delete it with pending operations:

    #include <iostream>
    #include <asio.hpp>
    #include <asio/ssl.hpp>
    #include <memory>
    
    template <typename T>
    void debug(T& a)
    {
        for (unsigned int i = 0; i < sizeof(a); ++i)
        {
            if (i % 8 == 0) std::cout << std::endl << i << "\t";
            std::cout << unsigned(reinterpret_cast<unsigned char*>(&a)[i]) << " ";
        }
        std::cout << std::endl;
    }
    
    template <typename T>
    void destruct(T& a)
    {
        a.~T();
        // If I memset to zero I just get a write into the deleted object
        // If i memset to 0xff I get a segmentation fault
        memset(&a, 0xff, sizeof(a));
    }
    
    char buffer[4096];
    const char* to_write = "GET / HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n";
    
    int main()
    {
    
        asio::io_service io;
        asio::ssl::context ssl_context(asio::ssl::context::tlsv1);
        
        asio::ssl::stream<asio::ip::tcp::socket>* socket = new asio::ssl::stream<asio::ip::tcp::socket>(io, ssl_context);
        socket->set_verify_mode(asio::ssl::verify_none);
    
        asio::ip::tcp::resolver resolver(io);
        asio::ip::tcp::resolver::query query("stackoverflow.com", std::to_string(443));
        
        resolver.async_resolve(query, [socket](const asio::error_code& ec, asio::ip::tcp::resolver::iterator result)
        {
            if (ec) throw ec;
    
            socket->next_layer().async_connect(*result, [socket](const asio::error_code& ec)
            {
                if (ec) throw ec;
    
                socket->async_handshake(asio::ssl::stream_base::client, [socket](const asio::error_code& ec)
                {
                    if (ec) throw ec;
    
                    asio::async_write(*socket, asio::buffer(to_write, std::string(to_write).size()), [socket](const asio::error_code& ec, std::size_t)
                    {
                        if (ec) throw ec;
                       
                        
                        socket->async_read_some(asio::buffer(buffer, 4096), [socket](const asio::error_code& ec, std::size_t len)
                        {
                            if (ec) {
                                std::cout << ec.message() << std::endl;
                                return;
                            }
    
                            std::cout.write(buffer, len);
    
                            std::cout << std::endl << "End" << std::endl;
                        });
                        
                        destruct(*socket);
                        debug(*socket);
                    });
    
                }
                );
            });
        });
        io.run();
        
        debug(*socket);
    }

**Comment by chriskohlhoff** [comment]
It is not safe to delete an SSL stream in this case. This is true for the arguments to any "composed operation" such as async_read, async_write, etc. The ssl stream is just a wrapper object that provides composed asynchronous operation, so has the same requirements.

I've added a note to the documentation.
