### ISSUE TITLE
`asio::ip::tcp::socket::read_some` block even `asio::ip::tcp::socket::close` is called

### ISSUE THREAD

**Issue by xyz1001** [chriskohlhoff/asio#779]
I use asio( standalone, 1.12.2, client os is MacOS 10.15.7, server os is Manjaro Linux 20.2.1 or Android 9.0) `asio::ip::tcp::socket::read_some` to receive data. This method will return when I call `asio::ip::tcp::socket::close`. But sometimes will not. I use wireshark to capture the packet in abnormal situation.
![image](https://user-images.githubusercontent.com/14332136/104710042-93023280-575a-11eb-84be-5da9567c5d46.png)

Here is the stack when block.
![image](https://user-images.githubusercontent.com/14332136/104710145-b4631e80-575a-11eb-95f1-b3ec4f87d67a.png)

**Comment by tstenner** [comment]
Closing a socket another thread is performing a synchronous read on is not defined. In my experience, it works on all major OSes except macOS.
