### ISSUE TITLE
deadline_timer not available in standalone build

### ISSUE THREAD

**Issue by acmorrow** [chriskohlhoff/asio#82]
When ASIO_STANDALONE is defined, the deadline_timer class is not defined.

**Comment by huyuguang** [comment]
As my remember, it changed for quite a while, nowyou should use asio::steady_timer.

**Comment by acmorrow** [comment]
@huyuguang I think that is likely true, however, in this case I'm working with an existing piece of software that makes use of deadline timer with the boost ASIO, and would like it to work without modification against the standalone ASIO as well. Changing it to use steady_timer was not really in scope.

**Comment by chriskohlhoff** [comment]
The deadline_timer interface depends on the boost.date_time library and so can't be supported by Asio's standalone configuration. The basic_waitable_timer<> class is also available in Boost.Asio and so may be used with both the Boost and standalone variants.
