### ISSUE TITLE
asio::post with asio::use_awaitable did not post continuation to another io_context

### ISSUE THREAD

**Issue by omegacoleman** [chriskohlhoff/asio#856]
I was aware of that `asio::post(strand_, asio::use_awaitable);` will run the after lines of this coroutine inside the strand, but the similar `asio::post(another_ioc_, asio::use_awaitable);` seems useless when attempting to post the continuation to another io_context

with the following code:

```c++
#include "boost/asio.hpp"
#include <thread>
#include <iostream>
#include <chrono>

namespace asio = boost::asio;
namespace chrono = std::chrono;
using asio::awaitable;
using asio::steady_timer;
using asio::co_spawn;
using std::cout;
using std::endl;

asio::io_context ioc_a;
asio::io_context ioc_b;

awaitable<void> coro_a() {
	cout << "Coro A running on " << std::this_thread::get_id() << endl;
	steady_timer t{ioc_a};
	for (;;) {
		t.expires_after(chrono::seconds(1));
		co_await t.async_wait(asio::use_awaitable);
	}
}

awaitable<void> coro_b() {
	cout << "Coro B running on " << std::this_thread::get_id() << endl;
	steady_timer t{ioc_b};
	for (int i = 0; i < 3; i++) {
		t.expires_after(chrono::seconds(1));
		co_await t.async_wait(asio::use_awaitable);
	}

	co_await asio::post(ioc_a, asio::use_awaitable);
	cout << "After switching, Coro B running on " << std::this_thread::get_id() << endl;
	for (;;) {
		t.expires_after(chrono::seconds(1));
		co_await t.async_wait(asio::use_awaitable);
	}
}

int main(void) {
	co_spawn(ioc_a, coro_a, asio::detached);
	co_spawn(ioc_b, coro_b, asio::detached);
	std::thread th{[]() mutable {
		ioc_b.run();
	}};
	ioc_a.run();
	return 0;
}
```
The output is like:
```
Coro A running on 140623832897408
Coro B running on 140623727048448
After switching, Coro B running on 140623727048448
```
However, I expected the output to be like
```
Coro A running on 140623832897408
Coro B running on 140623727048448
After switching, Coro B running on 140623832897408
```
The tid of coro_b should be same as the one coro_a initially printed.

In the time of writing, this usage of asio::post never appeared in the docs, just ppl on stackoverflow inferred the original usage with strands, so
1. Is my expectations correct via the docs and the standard?
2. If yes, then this could be a bug in the current impl
3. If not, maybe this behaviour should get documented some way

p.s. I discovered this developing https://github.com/omegacoleman/zrp , could be useful if you want your home NAS behind firewalls exposed over internet

**Comment by linzj** [comment]
I have debugged the issue a bit and found that the key part lies in the following C++ code snippet:

```c++
    boost::asio::prefer(
        boost::asio::require(ex_, execution::blocking.never),
        execution::relationship.fork,
        execution::allocator(alloc)
      ).execute(
        detail::work_dispatcher<handler_t, handler_ex_t>(
          static_cast<CompletionHandler&&>(handler), handler_ex));
```

When the posted handler completes, it invokes:

```c++
template <typename Handler, typename Executor, typename = void>
class work_dispatcher
...
  void operator()()
  {
    associated_allocator_t<Handler> alloc((get_associated_allocator)(handler_));
    boost::asio::prefer(executor_, execution::allocator(alloc)).execute(
        boost::asio::detail::bind_handler(
          static_cast<Handler&&>(handler_)));
  }
```

This results in the completion handler being "ping-ponged" back to `ioc_b`.

**Comment by linzj** [comment]
If you need to post a task to another `io_context`, it is recommended to use the `co_spawn` function instead of `post`:

```c++
awaitable<void> coro_b() {
  cout << "Coro B running on " << std::this_thread::get_id() << endl;
  steady_timer t{ioc_b};
  for (int i = 0; i < 3; i++) {
    t.expires_after(chrono::seconds(1));
    co_await t.async_wait(asio::use_awaitable);
  }

  co_await asio::co_spawn(
      ioc_a,
      []() -> asio::awaitable<void> {
        cout << "Handling task, Coro B running on "
             << std::this_thread::get_id() << endl;
        co_return;
      },
      asio::use_awaitable);
  cout << "After switching, Coro B running on " << std::this_thread::get_id()
       << endl;
  for (;;) {
    t.expires_after(chrono::seconds(1));
    co_await t.async_wait(asio::use_awaitable);
  }
}
```

Using `co_spawn` ensures that the task is properly scheduled and executed on the specified `io_context`.

**Comment by omegacoleman** [comment]
> This results in the completion handler being "ping-ponged" back to `ioc_b`.

Thank you very much! Correct me if I'm wrong: In short, the awaitable itself is associated with an executor(`ioc_b`), which is the reason for `post()` to send the work_dispatcher back to it.

Does that make the usage with strands:

```
asio::post(strand_, asio::use_awaitable);
```

also faulty?

**Comment by linzj** [comment]
I believe that when asio::post was designed, C++20 coroutines had not yet emerged. Consequently, there are APIs that are not compatible with C++20 coroutines. Hence, when utilizing C++20 coroutines, we must refrain from using these incompatible APIs.

**Comment by klemens-morgenstern** [comment]
That's not correct. Post runs on the executor (`strand_`) in this case, and completes on the associated executor of the competion handler: which in the case of use_awaitable will be the executor of the awaiting coroutine. `bind_executor` might do the trick, but you'll be in UB land if you do that.

**Comment by linzj** [comment]
Thank you for your clarification, Klemens. You might be right. However, the behavior of switching executors via co_await + bind_executor seems quite peculiar and error-prone. It is highly not recommended to use co_await + bind_executor, even though it is possible, due to the increased likelihood of introducing errors. It is much safer and more reliable to use co_spawn to send tasks to the desired executor.

**Comment by omegacoleman** [comment]
Thanks klemens and linzj, that's all facts I wanted to know, I'll mark the issue as completed.

Out of curiosity, do you think it is a good design by nature? I mean associating the awaitable with the context in the first place. I was surprised by this behavior because I thought coroutines are (supposed to be) merely resume-able function objects generated at compile time.

I am doing a rewrite for my own IO framework -- https://github.com/omegacoleman/arkio , I didn't associate coroutines with contexts in the last version. Does this design serve a special purpose in asio, or is it just burden of historical reasons?
