### ISSUE TITLE
co_spawn with use_awaitable and lamba move-capture copies noncopyable

### ISSUE THREAD

**Issue by omegacoleman** [chriskohlhoff/asio#858]
Reproducible w/ boost 1.76 and gcc 11.1.0

```c++
#include "boost/asio.hpp"
#include <iostream>
#include <memory>

namespace asio = boost::asio;
using asio::awaitable;
using asio::co_spawn;
using std::cout;
using std::endl;

asio::io_context ioc;

struct X {
	X(){}
	~X() {
		cout << "the dtor of X is invoked" << endl;
	}
};

awaitable<void> run() {
	std::unique_ptr<X> v = std::make_unique<X>();
	co_await co_spawn(ioc, [v = std::move(v)]() mutable -> awaitable<void> {
		cout << "hello" << endl;
		co_return;
	}, asio::use_awaitable);
}

int main(void) {
	co_spawn(ioc, run, asio::detached);
	ioc.run();
	return 0;
}
```
It outputs:
```
hello
the dtor of X is invoked
the dtor of X is invoked
free(): double free detected in tcache 2
fish: Job 1, './b.out' terminated by signal SIGABRT (Abort)
```
and the whole program went up in flames.

I managed to get the output of gcc address sanitizer, and it's super-long so I pasted that into a gist, hope it giving some clue:

https://gist.github.com/omegacoleman/bfa479eb1a4bb64f6f6e74bbc2f044e0

p.s. allow me to advertise my toy project once more, https://github.com/omegacoleman/zrp, a nat-passthrough reverse proxy written in modern c++, that's where I experiment with all these exciting new features :)

**Comment by ngladitz** [comment]
Might be https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100611

**Comment by omegacoleman** [comment]
> Might be https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100611

right, I can confirm this to be gcc-only
