### ISSUE TITLE
How to determin local endpoint for incoming UDP packet

### ISSUE THREAD

**Issue by arekmd** [chriskohlhoff/asio#865]
Hi, 

I have the service that listens for UDP packets on multiple network interfaces. My service binds  socket to "0.0.0.0" address, so it is using all local interfaces. 
I need to determine local IP address (address of local network interface) for each incoming UDP packet.

Any ideas?

**Comment by kashirin-alex** [comment]
```C++
std::cout << "remote=" << sock->remote_endpoint()
          << " local=" sock->local_endpoint() << std::endl;
```
-- Is the local being 0.0.0.0 for the UDP-Socket? (with TCP it is the actual when binding on any)

**Comment by arekmd** [comment]
Service exception: remote_endpoint: Transport endpoint is not connected

local_endpoint is: "0.0.0.0:7110"

**Comment by kashirin-alex** [comment]
Yes, UDP is different, (UDP receive does not create a socket with the corresponding remote_endpoint )

One way I can think of , It is possible to determine the interface by the remote-endpoint network co-related to the local accessible network (but that is only when IP-bind/interfaces handle the specific net )
https://www.boost.org/doc/libs/1_76_0/doc/html/boost_asio/tutorial/tutdaytime5.html
-- Are you able to use `send_to` remote_endpoint whereas the socket bind is on any-IP (it must have definitions of the interface/network used at receiving) ?

**Comment by arekmd** [comment]
Yeah. Binding to local interface IP is a solution.  I hoped to find more simple one. 

Thank you for your suggestions kashirin-alex

**Comment by arekmd** [comment]
I found a promising solution.

When socket is created with IP_PKTINFO option, and packet is received by recvmsg function - local address can be found in in_pktinfo structure. So I'm going to create uDP socket by myself (not asio), then call  recvmsg inside async_wait handler.
