### ISSUE TITLE
New signal/slot classes break compilation with Qt

### ISSUE THREAD

**Issue by gjasny** [chriskohlhoff/asio#873]
Hello,

while testing Boost 1.77 RC1 Beta1 I noticed that the following does not compile:

```c++
#include <QObject>
#include <boost/asio.hpp>
```

```
In file included from ../modules/videoengine/test/VcEngineQtTestClient/Source/main.cpp:10:
In file included from /home/gregorj/.cache/cmake_build_system/ExternalLibs/boost/1.77.0-pre_1626091668/boost/asio.hpp:22:
In file included from /home/gregorj/.cache/cmake_build_system/ExternalLibs/boost/1.77.0-pre_1626091668/boost/asio/associated_cancellation_slot.hpp:20:
/home/gregorj/.cache/cmake_build_system/ExternalLibs/boost/1.77.0-pre_1626091668/boost/asio/cancellation_signal.hpp:120:33: error: expected ')'
  void emit(cancellation_type_t type)
```

My suspicion is that something like `signal`, `slot`, or `emit` within ASIO interferes with Qt.

Thanks,
Gregor

**Comment by gjasny** [comment]
If I rename `cancellation_signal::emit` into `emit_signal` compilation works, again. Would you be willing to change your code for enhanced Qt compatibility?

**Comment by madmongo1** [comment]
Perhaps Qt should make an effort not to hijack common computing terms in its macro definitions. 🤷

**Comment by chriskohlhoff** [comment]
I added changes to try to protect against this in 2d3a4c9fcdeeea48dc6974389b4c5167da9e34f7. Can you please confirm if it fixes the issue for you.

**Comment by gjasny** [comment]
Works like a charm. Thank you!
