### ISSUE TITLE
timers can time out after being cancelled 

### ISSUE THREAD

**Issue by timblechmann** [chriskohlhoff/asio#878]
i'm seeing a rather unexpected behaviour that timers can time out *after* they have been cancelled. afaict this happens then the timer is cancelled at the "same time" (as in "same event loop wakeup") as the timer is cancelled:

compare this reproducer where we delete the timer during `post`:
* if we use a timeout of 1s, the event handler will be called with `error==89` ... this is expected behaviour
* if we use a timeout of 0s, the event handler will be called with `error==0` ... this not expected, as the timer has been cancelled

```
int main()
{
    boost::asio::io_context ctx;
    auto timer = std::make_shared<boost::asio::steady_timer>(ctx);

    auto timeout = std::chrono::seconds(0);
//    timeout = std::chrono::seconds(1);

    timer->expires_after(timeout);
    timer->async_wait([&](boost::system::error_code error) {

        if (error)
            printf("timer %s\n", error.message().c_str());
        else {
            assert(timer);
            printf("timer expired\n");
        }
    });

    boost::asio::post(ctx, [&]{
        printf("cancelling timer\n");
        timer.reset();
    });

    ctx.run_for(std::chrono::seconds(10));
}
```

**Comment by kashirin-alex** [comment]
just looking into it, there is no actually issue behavior error.
as to the example, it is complex test case to have true concurrency for the cancel operation , as even the `reset` in this case is actually after 0s pass due of execution. 
Second subject is the `reset` which is actually the `cancel` that returns the number of operations that where cancelled at which case (ec in your test is Success) the expected cancelled is Zero.
-- to the example if the `cancel()` returns 1 and the timer called with Success error-code then it is a major Issue.

In manner of procedure (correct me if wrong), a Timer out of queue is at execution mode (the due in near-future) and cancel applied on timer that is still in queue (the N operations cancelled).

_some ref: 
https://www.boost.org/doc/libs/1_76_0/doc/html/boost_asio/reference/basic_waitable_timer/expires_after.html
https://www.boost.org/doc/libs/1_76_0/doc/html/boost_asio/reference/basic_waitable_timer/cancel.html_

**Comment by timblechmann** [comment]
hmm, it may not be an error, but it's certainly quite a surprising behavior
