### ISSUE TITLE
Wrong completion token called

### ISSUE THREAD

**Issue by vagran** [chriskohlhoff/asio#880]
Consider the following code:

```cpp
asio::awaitable<void>
MainTask()
{
    std::cout << "In main task\n";
    co_return;
}

int
main()
{
    asio::io_context mainCtx;
    int exitCode = 0;

    asio::signal_set signals(mainCtx, SIGINT, SIGTERM, SIGUSR1);
    asio::co_spawn(mainCtx, [&]() -> asio::awaitable<void> {
        while (true) {
            std::cout << "waiting signal\n";
            int sig = co_await signals.async_wait(asio::use_awaitable);
            if (sig == SIGINT || sig == SIGTERM) {
                std::cout << "Exiting on signal " << sig << "\n";
                mainCtx.stop();
                exitCode = 1;
                break;
            }
            std::cout << "Signal received: " << sig << "\n";
        }
    }, [&](std::exception_ptr error) {
        if (error) {
            std::cout << "signal error\n";
        }
        std::cout << "signal completed\n";
    });

    asio::co_spawn(mainCtx, MainTask(),
        [&](std::exception_ptr error) {

        if (error) {
            std::cout << "main error\n";
        }
        std::cout << "main complete\n";
        mainCtx.stop();
    });

    mainCtx.run();

    return exitCode;
}
```
It has the following output:
```
waiting signal
In main task
signal completed
<Ctrl+C pressed here>
^CExiting on signal 2
signal completed
```
As it is seen the completion handler for the first coroutine called twice, first time when MainTask() completed, second time, when signal received. I expect the second handler should be called when MainTask() completed, and also no handlers under no circumstances called twice.

Tested with version 1.19.1. Compiled with Clang 12 on Linux with `-std=c++20 -stdlib=libc++ -DASIO_STANDALONE -DASIO_NO_DEPRECATED`.

**Comment by gummif** [comment]
Appears to work fine with gcc 11 https://godbolt.org/z/rW8fbcss4
```
waiting signal
In main task
main complete
```
Could be an issue with coroutines in clang?

**Comment by vagran** [comment]
Seems the problem requires more exotic conditions for reproduction. I did not mention that I also used C++ modules (I thought it doesn't matter, but seems it does). I have created repository with the problem demonstation [here](https://github.com/vagran/asio-awaitable-modules-problem-demo). The problem appears only if modules are in use.

**Comment by vagran** [comment]
Found out that [replacing lambda handlers with dedicated functions](https://github.com/vagran/asio-awaitable-modules-problem-demo/compare/function_handlers) makes it work. May be the problem is with clang/modules/lambdas combo only, unrelated to the Asio itself. I will try to isolate it further.

**Comment by vagran** [comment]
OMG. This simple code fails with Clang modules:
```
export module callback;

import <functional>;

export class Callback {
public:
    template <typename F>
    Callback(F f):
        f(f)
    {}

    void
    operator()()
    {
        f();
    }

    std::function<void()> f;
};
```
```
export module main;

import callback;
import <iostream>;

export int
main()
{
    Callback cbk1([&]() {
        std::cout << "callback 1\n";
    });

    Callback cbk2([&]() {
        std::cout << "callback 2\n";
    });

    cbk1();
    cbk2();

    return 0;
}
```
Output:
```
callback 2
callback 2
```
Seems to be critical bug in Clang modules. Unrelated to Asio.

**Comment by vagran** [comment]
Clang bug reported: https://bugs.llvm.org/show_bug.cgi?id=51607
