### ISSUE TITLE
Incorrect MSVC detection in ASIO_STANDALONE mode

### ISSUE THREAD

**Issue by lhecker** [chriskohlhoff/asio#89]
If `ASIO_HAS_BOOST_CONFIG` is not defined asio tries to detect MSVC using `defined(_MSC_VER) && !defined(__MWERKS__) && !defined(__EDG_VERSION__)` (https://github.com/chriskohlhoff/asio/blob/722f7e2be05a51c69644662ec514d6149b2b7ef8/asio/include/asio/detail/config.hpp#L68) which is currently unfortunately incorrect.

While the code does compiles correctly (only `_MSC_VER` is defined) it does not work with IntelliSense because it sets `#define __EDG_VERSION__ 410` during code analysis, which affects not just asio itself (by disabling all C++11 related includes etc.), but can also affect _large_ parts of the rest of the code too. :confused:

I suggest the removal of the `!defined(__EDG_VERSION__)` test since, in my humble opinion, the issues caused by this in MSVC are far far more worse than the possible issues with more seldom used and possibly buggy compilers, which define `_MSC_VER` with a certain number X, but do not provide all of the features that MSVC offers with versions greater than that (e.g. if one of those compilers sets `_MSC_VER >= 1700` but does not offer move semantics even if it should).

**Comment by bbrice** [comment]
I'd like to second this.  I ran into this issue today.  My work around was to predefine `ASIO_MSVC` before including any ASIO headers:

` #define ASIO_MSVC _MSC_VER`

**Comment by rpavlik** [comment]
FWIW, this is fixed for the master branch in https://github.com/chriskohlhoff/asio/commit/a8f9b3cedce25cefb88cca8195f538f7e97b93f4 (by letting `__INTELLISENSE__` override detection of other compilers)

**Comment by lhecker** [comment]
Ah thank god finally... I'm closing this issue then. 😅
