### ISSUE TITLE
including <boost/asio/ssl.hpp> bloats the executable file size

### ISSUE THREAD

**Issue by Enhex** [chriskohlhoff/asio#929]
this applies to both boost and standalone Asio.

just including `<boost/asio/ssl.hpp>` even in a program that does nothing (empty `main()`) causes a >3MB executable.
inside `<boost/asio/ssl.hpp>` the offending include seems to be `<boost/asio/ssl/context.hpp>`.

I tried to use `BOOST_ASIO_SEPARATE_COMPILATION` but it didn't help.

if the SSL/TLS code is unused, why does it increase the file size so much?

**Comment by brjoha** [comment]
Try linking with -lto option and it should eliminate anything unused.

**Comment by Enhex** [comment]
using LTO didn't help.
here's a minimal example to reproduce it (using Conan and Premake):
[asio_bloat.zip](https://github.com/chriskohlhoff/asio/files/7532905/asio_bloat.zip)

**Comment by gotnone** [comment]
@Enhex did you ever find a solution for this bloated executable problem?  I am using ASIO for a non-SSL TCP application and noticed a very large executable size for what is essentially an echo server.  Even after stripping the executable, I am at 4.4MB.  I can confirm that LTO only reduces that size minimally, to 4.2MB.

It looks like you didn't find much support on your openssl [issue](https://github.com/openssl/openssl/issues/18765).

**Comment by Enhex** [comment]
@gotnone if you're not using OpenSSL maybe you can disable it.
other than that no solution to my original problem.
