### ISSUE TITLE
build failed with clang 3.6.1 and libstdc++

### ISSUE THREAD

**Issue by harrywong** [chriskohlhoff/asio#96]
Hi, I'm using asio on Linux, with the compiler clang++ 3.6.1 and use libstdc++(from gcc 5.3.0).
With this code: 
`            std::string echo;
            auto n = asio::read_until(socket, asio::dynamic_buffer(echo), "\r\n");`
I got this error: 

> In file included from .../asio/asio/include/asio/ts/buffer.hpp:18:
.../asio/asio/include/asio/buffer.hpp:1405:12: error: no viable conversion from 'asio::mutable_buffers_1' to 'const_buffers_type' (aka 'asio::const_buffers_1')
    return asio::buffer(string_, size_);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

> .../asio/asio/include/asio/impl/read_until.hpp:160:35: note: in instantiation of member function 'asio::dynamic_string_buffer<char, std::char_traits<char>, std::allocator<char> >::data' requested here
    buffers_type data_buffers = b.data();
                                  ^
>.../asio/asio/include/asio/impl/read_until.hpp:105:35: note: in instantiation of function template specialization 'asio::read_until<asio::basic_stream_socket<asio::ip::tcp, asio::stream_socket_service<asio::ip::tcp> >, asio::dynamic_string_buffer<char, std::char_traits<char>, std::allocator<char> > >' requested here
  std::size_t bytes_transferred = read_until(s,
                                  ^

Thanks

**Comment by harrywong** [comment]
Try to use gcc 5.3.0 to compile, also got this error. Am I using in a wrong way somewhere?

**Comment by chriskohlhoff** [comment]
Fixed in 6f86878ff75a8ed86dad9983a6415d35dea4e966.
