### ISSUE TITLE
possibility to use asio free functions with udp sockets

### ISSUE THREAD

**Issue by skorokhod** [chriskohlhoff/asio#98]
It's very convinient to have posibility to write data into udp sockets as tcp sockets and serial ports has. Simply:
```
asio::ip::udp::socket s;
asio::async_write(s, asio::buffer(data, size), handler);
```
Of course, there should be some limitations like:
- all the data should be sent in one go
- no possibility to use signature with complition condition
- so on

As for reading data, why one can't use asio::read to automatically accumulate data from several datagrams while receiving jpeg image splitted into several parts?
```
asio::ip::udp::socket s;
std::vector<uint8_t> image
asio::async_read(s, asio::dynamic_buffer(image), some_completion_analyzer, handler);
```

**Comment by chriskohlhoff** [comment]
Thanks for the suggestion but I don't think this makes sense. The async_read and async_write functions assume stream-oriented behaviour, but UDP sockets aren't like that as they can reorder and lose datagrams.
