### ISSUE TITLE
Why does io_service::post() require a copyable handler?

### ISSUE THREAD

**Issue by rustyx** [chriskohlhoff/asio#99]
It seems that most async handlers can be move-only now (according to [d25fa4e](https://github.com/chriskohlhoff/asio/commit/d25fa4e5dd21ed81427934d6192ceb3a8805b02a)) but the CompletionHandler must still be copyable.

Which is strange, because if I pass a handler without copy constructor/operator implementation to `io_service::post()`, it works fine, pointing to the fact that io_service never actually copies the handler.

Hence my question: why this requirement? Can it be relaxed so that I can finally pass an instance of `std::packaged_task` to `io_service::post()` ?

**Comment by sztomi** [comment]
I've just ran into this as well. I'm trying to do something along the lines of

                        auto b = get_movable_buffer();
                        io_->post(strand_.wrap(
                            [this, b = std::move(b)]() {
                                do_something(b);
                            }));
                    });

Which doesn't work because post needs a copyable handler.

**Comment by chriskohlhoff** [comment]
Use `asio::post(your_io_context, your_handler)` instead of `your_io_context.post(your_handler)`. The `io_context::post()` function is now deprecated.

**Comment by rustyx** [comment]
`asio::post(...)` also copies the handler, if it's an lvalue. Is that expected?

Example:

```
    auto mytask = std::packaged_task<int()>([] { return 1; });
    boost::asio::post(myservice, mytask); // error C2280: 'std::packaged_task<int (void)>::packaged_task(const std::packaged_task<int (void)> &)': attempting to reference a deleted function
```

But with an rvalue it seems to work:

```
    auto mytask = std::packaged_task<int()>([] { return 1; });
    boost::asio::post(myservice, std::move(mytask)); // OK
```
