### ISSUE TITLE
Handler type for CompletionToken via async_completion<>::completion_handler_type

### ISSUE THREAD

**Issue by ytimenkov** [chriskohlhoff/asio#993]
I'm trying to use coroutines and `awaitable<>` with existing libraries which take callbacks and writing an adapter, following patters in ASIO.

I would like to avoid type erasure (at least defer it) and for that I need to know the handler type which will be passed into my `InitiationFunction` to store later in the Operation.

I found that there is a `async_completion` class which could be used like this:
```c++
struct Op
{
    optional<async_completion<default_completion_token_type, void(error_code)>::completion_handler_type> coro_handler{};
};

struct initiate_op
{
    Op* op_;

    template<typename Handler> // This should be same as coro_handler::value_type
    void operator()(Handler && h)
    {
        op_->coro_handler.emplace(std::move(h));
        call_legacy_function(op_, [](void* data, error_code ec) { // Legacy callback, taking one void* "context"
            static_cast<Op*>(data)->coro_handler(ec); // More complicated, via dispatch of course.
        });
    }
};

awaitable<error_code> async_call_legacy(..., Op* op)
{
    default_completion_token_type token;
    return async_initiate<default_completion_token_type, void(error_code)>(initiate_op{op}, token);
}
```

Now the problem is that `async_result<use_awaitable_t...>` specialization does not define `completion_handler_type` but rather just `handler_type`.

So the question is: if it's a legal to use `async_completion<>::completion_handler_type` to deduce handler type in advance for such a use-case (in this case I guess `async_result<use_awaitable_t...>` needs to be updated)?

Or is it not and I have to use type-erasure to store handler in my operation context?

**Comment by Tradias** [comment]
We use something very similar in our code and it works perfectly. I think the fact that `awaitable` calls it `handler_type` instead of `completion_handler_type` is a bug. You might want to use a workaround like so:

```cpp
namespace asio = boost::asio;

template <class CompletionToken, class Signature, class = void>
struct CompletionHandlerType {
    using type =
        typename asio::async_result<CompletionToken,
                                    Signature>::completion_handler_type;
};

template <class CompletionToken, class Signature>
struct CompletionHandlerType<CompletionToken, Signature,
                             std::void_t<typename asio::async_result<
                                 CompletionToken, Signature>::handler_type>> {
    using type =
        typename asio::async_result<CompletionToken, Signature>::handler_type;
};

template <class CompletionToken, class Signature>
using CompletionHandlerTypeT =
    typename CompletionHandlerType<CompletionToken, Signature>::type;
```

See https://godbolt.org/z/36T9T87YW

Another thing we learned the hard way is to make sure to "deallocate" the completion handler before calling it. In your code that would be:

```cpp
        call_legacy_function(op_, [](void* data, error_code ec) {
            auto* self = static_cast<Op*>(data);
            auto handler = std::move(*self->coro_handler);
            self->coro_handler.reset();
            std::move(handler)(ec);
        });
```

Otherwise your program might crash later on and it becomes hard to track down the cause.

**Comment by ytimenkov** [comment]
>  I think the fact that awaitable calls it handler_type instead of completion_handler_type is a bug. 

That is exactly the point of this issue, a question to Chris - whether this is a bug or feature. 🙂

> Another thing we learned the hard way is to make sure to "deallocate" the completion handler before calling it. 

🙇‍♂️ Noted. I have some TODO's sprinkled at these places. Now valgrind tells me to go and fix 😁 (and honestly it's in ASIO documentation, that all associated allocations should be freed before calling the handler).

Another thought is that dispatching a handler may cause immediate deallocation of promise object in another thread, leaving currently executing function in state where it can't access non-local variables. I think few (including David Chen) blogged about it.

So yeah... many ways to cut oneself....

**Comment by chriskohlhoff** [comment]
I updated the documentation to reflect the current state of completion tokens and the `async_result` trait. In particular, the `completion_handler_type` is no longer part of the requirements (though backward compatibility is retained).

I also added some examples (which I see from your more recent issue that you've already noticed) that illustrate wrapping callback-based APIs.

In a nutshell, you should treat the concrete completion handler as an internal implementation detail of your async operation, and not try to expose it to the caller through the argument list. Instead, use the associated allocator to obtain the memory to store it.

Using the (newly added) `recycling_allocator` will optimise this sufficiently for most use cases, but a coroutine may also specify an allocator using the (newly added) `bind_allocator`:

```
awaitable<void> foo()
{
  my_pre_allocatated_storage_type my_storage;
  my_custom_allocator my_alloc(my_storage);
  ...
  co_await my_operation(/*...*/, bind_allocator(my_alloc, use_awaitable));
}
```

**Comment by ytimenkov** [comment]
Yes, I wrote the code quite close to your example for a simple wrapping.

However this particular case is a bit more complicated - I have a long-running asio-style operation (so it has user-provided-handler) and sometimes it delegates to a calback-style api, and sometimes to a coroutine. Therefore I need to allocate a data/context for that operation which contains both user handler and coroutine handler. At this point I know the type of user, but I don't know the type of coroutine handler. That's why I get it from `async_result`.

Sorry for unclear explanation :(

But in general I don't see a problem or harm if `async_result` also provides a type for the handler beforehand when it is known (even if it's an implementation detail) - of course it shouldn't be used directly, but in the end the handler is passed to initializing function, so it will be in the user code.

I will think about your suggestion with allocators. Being future-proof is more important.

**Comment by Tradias** [comment]
A potential option is to create an initialized fixed size storage and then use something like a [OneShotAllocator](https://github.com/Tradias/asio-grpc/blob/master/src/agrpc/detail/oneShotAllocator.hpp) to store the handler in it. E.g.:

```cpp
std::aligned_storage_t<MAX_HANDLER_SIZE> buffer;
co_await async(..., asio::bind_allocator(OneShotAllocator<MAX_HANDLER_SIZE>{&buffer}, asio::use_awaitable);
```
where the OneShotAllocator can have a static_assertion to check that the buffer is large enough. If the assertion triggers then you can simply increase MAX_HANDLER_SIZE.

I am using that in a more complex example [here](https://github.com/Tradias/asio-grpc/blob/master/example/file-transfer-client.cpp).

**Comment by chriskohlhoff** [comment]
> sometimes it delegates to a calback-style api, and sometimes to a coroutine.

I would suggest you wrap each of those in its own async operation (well actually you would just `co_spawn` as the async operation for the latter) as the building blocks, and then compose these building blocks into a third async operation using `async_compose` to do the sometimes-this/sometimes-that logic. The completion handler types shouldn't need to bleed out of each layer of the abstraction.

**Comment by ytimenkov** [comment]
I double-checked my code and you are right, it should be possible to wrap legacy functionality into its own async operation which does a small well-defined piece or work.

Also the whole thing is built around per-operation cancellation 😎.
