### ISSUE TITLE
co_spawn blocks from another coroutine

### ISSUE THREAD

**Issue by vkhristenko** [chriskohlhoff/asio#996]
This is a duplicate of [stackoverflow question](https://stackoverflow.com/questions/70619797/c20-coroutines-boost-asio-co-spawn-blocks-from-another-coroutine)

-----
I do not know if this is the expected behavior of boost::asio::co_spawn (I did check the docs 1.78.0...), but if i call (e.g. co_spawn(ctx, ..., detached)) from a function, this call is async, meaning that this call does not block waiting for the completion, but returns immediately. However, if i do the same call from within another coroutine, co_spawn will block until whatever that was spawned completes. Below is the a test compiled with g++ 11.2 with boost asio 1.78.

```cpp
#include <iostream>
#include <thread>
#include <chrono>
#include <coroutine>

#include <boost/asio.hpp>
#include <boost/asio/experimental/as_tuple.hpp>

using namespace boost;
using namespace boost::asio;

awaitable<void> TestCoro2(io_context& ctx) {
    std::cout << "test coro1 thread id = " << std::this_thread::get_id() << std::endl;
    co_return;
}

awaitable<void> TestCoro1(io_context& ctx) {
    std::cout << "test coro1 thread id = " << std::this_thread::get_id() << std::endl;
    std::cout << "333" << std::endl;
    //co_await TestCoro2(ctx);
    co_spawn(ctx, TestCoro2(ctx), detached);
    std::cout << "444" << std::endl;
    co_return;
}

awaitable<void> TestCoro(io_context& ctx) {
    std::cout << "test coro thread id = " << std::this_thread::get_id() << std::endl;
    std::cout << "111" << std::endl;
    co_spawn(ctx.get_executor(), TestCoro1(ctx), detached);
    std::cout << "222" << std::endl;
    co_return;
}

void Test1() {
    io_context ctx;
    auto work = require(ctx.get_executor(), execution::outstanding_work.tracked);

    std::cout << "before" << std::endl;
    co_spawn(ctx.get_executor(), TestCoro(ctx), detached);
    std::cout << "after" << std::endl;

    ctx.run();
}

int main() {
    Test1();

    return 0;
}
```

n the example above i had not yet called ctx.run() when spawking a coro... still semantics, I would expect, to be similar...

My understanding was that first it will schedule and return, and a currently running coroutine will proceed, however i guess i was wrong. I do understand that i can also just wrap this co_spawn into a post... but i'm a bit confused on the difference in behavior...

Is this the expected behavior?

thanks! VK

**Comment by kiwixz** [comment]
Yes, co_spawn doesnt guarantee the new coroutine will be runned after the current one.  Its more like `dispatch` than `defer`/`post`.

See what happens when you add a sleep: https://godbolt.org/z/4Ya8z5cE8

**Comment by vkhristenko** [comment]
thanks for confirming!
