### ISSUE TITLE
`basic_socket_iostream` is non-movable under clang

### ISSUE THREAD

**Issue by yeputons** [chriskohlhoff/asio#997]
The following code compiles successfully [with gcc 11.1.0](https://wandbox.org/permlink/6Efafe612j2SCNFk), but [not clang 13.0.0](https://wandbox.org/permlink/92fp5nUGbV1csoKq) when using Boost 1.78.0:

```c++
#include <boost/asio.hpp>
#include <sstream>
#include <utility>

int main() {
    std::stringstream s1;
    std::stringstream s2 = std::move(s1);
    
    boost::asio::ip::tcp::iostream asio1;
    boost::asio::ip::tcp::iostream asio2 = std::move(asio1);
}
```

Error message is:

```
prog.cc:10:36: error: call to deleted constructor of 'boost::asio::ip::tcp::iostream' (aka 'basic_socket_iostream<boost::asio::ip::tcp>')
    boost::asio::ip::tcp::iostream asio2 = std::move(asio1);
                                   ^       ~~~~~~~~~~~~~~~~
/opt/wandbox/boost-1.78.0-clang-13.0.0/include/boost/asio/basic_socket_iostream.hpp:392:3: note: 'basic_socket_iostream' has been explicitly marked deleted here
  basic_socket_iostream(const basic_socket_iostream&) BOOST_ASIO_DELETED;
  ^
1 error generated
```

It looks like move-constructor is [conditionally enabled on some compilers](https://github.com/boostorg/asio/blob/659c7e0923f34bd43a9a345b910fa75a8e6975ce/include/boost/asio/detail/config.hpp#L1182-L1184). Clang is not in the list, it only pretens to be GCC 4.2. Hence, move-constructor gets disabled. However, `std::basic_iostream` looks perfectly movable with Clang to me.

**Comment by chriskohlhoff** [comment]
Fixed in 1.22.1.
